README.md, src/CheckBox/CheckBox.test.jsx, src/CheckBox/README.md, src/asInput/index.jsx
I noticed a bug in the CheckBox component. The onChange function was only getting `"on"` passed to it instead of the actual checkbox state.
Let me know if I did something dumb, I'm new to all of this.
=> Fix the CheckBox component's onChange parameters

.gitignore, .storybook/__snapshots__/Storyshots.test.js.snap, src/Table/Table.stories.jsx, src/Table/Table.test.jsx, src/Table/index.jsx
Adds `sr-only` class to table headers that are marked hidden.
This PR needs to merge first so that I can release a new version of paragon.
=> Hide table headers when marked hidden

.storybook/__snapshots__/Storyshots.test.js.snap, package.json, src/RadioButtonGroup/RadioButtonGroup.stories.jsx, src/RadioButtonGroup/RadioButtonGroup.test.jsx, src/RadioButtonGroup/index.jsx, src/index.js
Implements a radio button group that fulfills the [WAI-ARIA Radio Group specifications](https://www.w3.org/TR/wai-aria-practices-1.1/#radiobutton) 
Chrome, Firefox, and Safari support keyboard accessibility for radio button groups so most of the additional accessibility features were around `aria` properties for HTML elements.
* [Accessible Examples](https://www.w3.org/TR/wai-aria-practices-1.1/examples/radio/radio-1/radio-1.html)
=> Implement Radio Button Group

package.json, src/RadioButtonGroup/index.jsx
I stumbled across [this great repository for React patterns / anti-patterns](https://github.com/vasanthk/react-bits/) and I realized that the current implementation of `RadioButton` and `RadioButtonGroup` is woefully guilty of
[this React bad practice](https://github.com/vasanthk/react-bits/blob/master/gotchas/01.pure-render-checks.md#bad-1)
```javascript
class App extends PureComponent {
render() {
return <MyInput
onChange={e => this.props.update(e.target.value)}/>;
}
}
```
Why is this bad? 
Because `e => this.props.update(e.target.value)` creates a new function, which has a different reference, which means that React's shallow equality check is always `false`, which means that this will __always__ re-render 😭 .
Just to make sure, I ran the debugger in `Storybook` and on any …
=> Prevent Unnecessary Radio Button and Radio Button Group Rerendering

README.md, package.json
I was seeing npm warnings for a missing repository field and for an unmet peer dev dependency (`@storybook/react^3.2.12`).
~~There are still two unmet peer dependency warnings for `jquery` and `popper.js` due to `@edx/edx-bootstrap`, which [I created a PR for](https://github.com/edx/edx-bootstrap/pull/22).~~ This should be merged in!
=> Fix missing repository warning and add unmet peer dev dependency

.storybook/__snapshots__/Storyshots.test.js.snap, package.json, src/Hyperlink/Hyperlink.stories.jsx, src/Hyperlink/Hyperlink.test.jsx, src/Hyperlink/index.jsx
Resolves #23 
It looks like the only necessary [accessibility specification](https://www.w3.org/TR/wai-aria-practices-1.1/#link) is
> Enter: Executes the link and moves focus to the link target.
This behavior is already supported on Chrome, Safari, and Firefox.
* Why `Hyperlink` vs. `Link`?
* This is more of a nitty specification on my part. Since you can create an `<a>` tag without an `href` attribute, when we require the `href` attribute, all our components will be hyperlinks, so why not use the more exact name? 
* I don't feel *that* strongly about this though...
* Why a `destination` prop instead of an `href` prop?
* In a similarly nitty vein, `href` seems like an implementation detail of a specific attribute that an `<a>` tag might need. 
* `destination` seems more descriptive.
* I …
=> Hyperlink Component

.travis.yml, package.json
* Installed [semantic-release](https://github.com/semantic-release/semantic-release) package
* Added convential commit analyzer
* [commitizen cli](https://github.com/commitizen/cz-cli)
* [conventional-changelog](https://github.com/conventional-changelog/conventional-changelog)
* Updated `travis.yml` to run `semantic-release` after build success
* Added email notifications
* In order to use `semantic-release` [__at least one Travis build must be Node 8+__](https://github.com/semantic-release/semantic-release#why-does-semantic-release-require-node-version--8). This doesn't seem to be a big issue for this project - there was one package I needed to install (`@storybook/channels`) in order to get the Node 8 build completing successfully
=> feat(semantic-release): implement semantic release

.storybook/__snapshots__/Storyshots.test.js.snap, src/Table/index.jsx
add aria-hidden tag to the table headings of sortable columns in a sortable Table so icons are not
read aloud to screen-reader users
=> fix(Table): add aria-hidden to sort icons in Table

.travis.yml, package.json
Related to #79 - we should only deploy GH Pages for the `master` branch
=> chore(travis): only run GitHub pages deploy for master branch

src/index.js
Related to #67. 
Forgot this because I'm a dummy. (I guess we (definitely) know that nobody is using the `Hyperlink` component (yet)).
=> fix(Hyperlink): Add Hyperlink component to exports

src/StatusAlert/index.jsx
StatusAlert requires a check for existence of xButton in componentDidUpdate to prevent errors when
displaying dismissible alerts.
=> fix(StatusAlert): Fix focus error for dismissible alert.

commitlint.config.js, package.json
The `commitmsg` hook fails when you try and add a commit message via `git commit` that does not follow conventional commit convention
=> fix(semantic-commit-linting): add semantic commit linting

.storybook/__snapshots__/Storyshots.test.js.snap, src/InputText/InputText.stories.jsx, src/InputText/index.jsx, src/TextArea/index.jsx, src/asInput/asInput.scss, src/asInput/asInput.test.jsx, src/asInput/index.jsx
Add danger theme to asInput component to add alert icon, red text for validation message, and red border to input element
=> fix(asinput): Add danger theme to asInput component

src/StatusAlert/StatusAlert.test.jsx, src/StatusAlert/index.jsx
In order to make focus management for accessible pages easier, expose a focus function on the component to allow parent to call focus on the component ref.
=> fix(statusalert): Expose focus function on StatusAlert component

src/asInput/asInput.test.jsx, src/asInput/index.jsx
asInput component was overriding state.value that was set by the parent component. This allows parent to call setState on input components.
=> fix(asinput): Remove control of state.value from asInput

.storybook/__snapshots__/Storyshots.test.js.snap, src/InputText/InputText.stories.jsx, src/asInput/asInput.scss, src/asInput/asInput.test.jsx, src/asInput/index.jsx
FYI: @edx/educator-dahlia 
This addresses [EDUCATOR-1952](https://openedx.atlassian.net/browse/EDUCATOR-1952).
- The `form-control-feedback` div referenced by `aria-describedby` must exist on the page when it is initially loaded for screen-readers. Bootstrap's css will hide it unless there is a validation error.
- I also added `aria-live="polite"` so that the error message is read out to the screen-reader user after validation happens.
- I added a `sr-only` div to the error span to describe the font awesome error icon. Users of paragon will have to pass in their own translated string `dangerIconDescription` for the description.
TODO
- Test in a screen-reader to see if this actually fixed the problems.
- Try using this branch in studio-frontend to verify integration works there.
=> fix(asinput): Accessibility fixes for asInput

src/Modal/Modal.stories.jsx, src/Modal/index.jsx, src/StatusAlert/StatusAlert.test.jsx, src/Table/Table.test.jsx, src/Tabs/index.jsx
When working on #101 I noticed that [the Travis build](https://travis-ci.org/edx/paragon/jobs/317368090) had eslint errors for `Node` `6`:
I confirmed these errors locally when I switched to `Node` `6.12.2` and `npm` `3.10.10`.
When I switched back to `Node` `8.9.3` and `npm` `5.5.1`, there weren't any linting errors.
=> fix(eslint): fix Node 6 eslint errors

.storybook/__snapshots__/Storyshots.test.js.snap, src/InputText/InputText.test.jsx, src/InputText/index.jsx, src/asInput/index.jsx
Follow up to [this comment](https://github.com/edx/paragon/pull/88#discussion_r153579701) from #88.
We should still do prop type checking for wrapped components.
=> fix(input-text): add prop types for the inner Text component

.storybook/Storyshots.test.js, package-lock.json, package.json
Add a `transformIgnorePatterns` for `lodash-es` per https://github.com/storybooks/storybook/issues/2570. Also mock `react-dom` per https://github.com/storybooks/storybook/issues/2522. If anybody around here feels like giving Storybook some help with Storyshots I'm sure they'd appreciate it.
Closes https://openedx.atlassian.net/browse/FEDX-491
Closes #104, #105, #106
=> fix(tests): upgrade *-jest-* packages and patch to work with storyshots

src/Table/Table.scss
UX would like the table headings to look like the standard bootstrap headings. When the column is sortable, the heading is a button. This PR makes those buttons look like headings.
@edx/educator-dahlia @arizzitano
=> fix(table): Buttons in table headings look like headings

.storybook/__snapshots__/Storyshots.test.js.snap, src/Table/Table.scss, src/Table/index.jsx
Studio-frontend munges the css names in order to isolate the styles from Studio as a whole. In order to apply the munged class names and thus styles, names need to be referenced from the code. This change renames the css class and provides that class to the table header's button.
@edx/educator-dahlia
=> fix(table): Use class name for button in table heading

.travis.yml
[Greenkeeper has lockfile support](https://github.com/greenkeeperio/greenkeeper-lockfile).
Basically, when a Greenkeeper branch / PR first runs on Travis (or another CI services), the [`greenkeeper-lockfile` `npm` package](https://www.npmjs.com/package/greenkeeper-lockfile) runs two commands that will lead to a commit to the pull request with the updated `package-lock.json` file.
I essentially just copied the `.travis.yml` updates from [the `greenkeeper-lockfile` `README`](https://github.com/greenkeeperio/greenkeeper-lockfile#npm).
One thing I omitted was installing `npm` in the `before_install` step like 
```yaml
before_install:
- npm install -g npm
```
I can explicitly add this command, but I was able to get `greenkeeper-lockfile` working without explicitly installing `npm` on a …
=> build(greenkeeper): add lockfile support for greenkeeper

src/Table/Table.test.jsx, src/Table/index.jsx
#118 fixed the `Button` class name for the `Table` component - this just adds tests for the updated class name. It also removes a redundant `classNames` call.
=> test(table): add button class name checks

.eslintrc.json, package-lock.json, package.json
I came across [`eslint-plugin-compat` ](https://github.com/amilajack/eslint-plugin-compat) that does browser compatibility linting.
I don't know if this is something we think would be a good idea to add, and also what browser versions we should try and support, but I'm opening this to start that discussion!
=> build(eslint): add browser compatibility linting

.storybook/__snapshots__/Storyshots.test.js.snap, src/InputText/InputText.stories.jsx, src/Modal/Modal.stories.jsx, src/TextArea/TextArea.stories.jsx, src/asInput/asInput.test.jsx, src/asInput/index.jsx
Extend input labels to accept elements as well as strings. The use case we are trying to handle is wrapping labels within spans specifying their language to manage i18n fallbacks correctly.
=> fix(input-label): extend asInput to allow label prop as element

.travis.yml
[`Greenkeeper`](https://greenkeeper.io) is great, [but part of how it works is that for in-range dependency updates that pass Travis, it deletes the branch](https://greenkeeper.io/docs.html#greenkeeper-step-by-step).
Currently emails are sent on success and failure (sorry @arizzitano) which leads to a lot of noise. We should only send emails on failure.
=> build(email): only send emails on failure

.storybook/__snapshots__/Storyshots.test.js.snap, .storybook/config.js, package-lock.json, package.json, src/Hyperlink/Hyperlink.stories.jsx
Ok, let's try this again (after #144 crashed and burned).
[`storybook/addon-info`](https://github.com/storybooks/storybook/tree/master/addons/info) allows you to build storybooks that look like
I would argue this is a significantly better user experience when looking at various stories.
=> build(storybook): use addon-info

README.md
Grabbed these from https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-angular#type
=> docs(readme): document non-changelog commit types

.storybook/__snapshots__/Storyshots.test.js.snap, src/InputText/InputText.stories.jsx, src/asInput/README.md, src/asInput/asInput.scss, src/asInput/asInput.test.jsx, src/asInput/index.jsx
Allows users of `asInput` to display [forms inline](https://v4-alpha.getbootstrap.com/components/forms/#inline-forms).
=> feat(asinput): add "inline" prop

.travis.yml
I thought #143 took care of this but apparently not.
When (if) this build succeeds I (and @arizzitano) shouldn't get a single damn email.
=> build(travis): suppress emails for successful builds

src/Hyperlink/Hyperlink.stories.jsx
Resolves #151 
**TL;DR** - **eslint: 1 - Bae Jadley: 0**
[You only need to import `addDecorator` from `@storybook/react` **when adding a decorator globally**](https://storybook.js.org/addons/introduction/#storybook-decorators). 
And when you do, you actually call the gosh darn method, vs. you know, not calling the imported method (`#chainedmethods`).
This import was a remnant from when I was thinking of installing it globally before deciding to just install it a Story at a time. 
This means I can change the `disable-line` in #160.
cc: @Mjloturco
=> style(import): remove unnecessary Hyperlink import

.storybook/__snapshots__/Storyshots.test.js.snap, src/RadioButtonGroup/RadioButtonGroup.stories.jsx, src/RadioButtonGroup/index.jsx
According to [the ARIA Radio Button Spec](https://www.w3.org/TR/2016/WD-wai-aria-practices-1.1-20160317/examples/radio/radio.html)
> The labels for the radio buttons are defined by the text nodes of each radio button. (e.g. “Regular Crust”, “Deep Dish”…)
That's why [the `a11y` Storybook add-on](https://github.com/storybooks/storybook/tree/master/addons/a11y) shows
This also updates the Radio Button Stories to use the [`centered`](https://github.com/storybooks/storybook/tree/master/addons/centered), [`info`](
https://github.com/storybooks/storybook/tree/master/addons/info), and [`a11y`](https://github.com/storybooks/storybook/tree/master/addons/a11y) Storybook add-ons.
Resolves #165
=> fix(radio-button): add aria-label

package-lock.json, package.json
As documented in #175, [`hapijs/isemail`](https://github.com/hapijs/isemail) is not `ES5` compliant.
I forked `isemail` to [`jaebradley/isemail`](https://github.com/jaebradley/isemail) and published an `ES5` compliant package at [`isemail-es5`](https://www.npmjs.com/package/isemail-es5).
I then updated [`email-prop-type` to `1.1.4`](https://github.com/jaebradley/email-prop-type/releases/tag/v1.1.4) which uses `isemail-es5` instead of `isemail`.
`static/index.js` and `themable/index.js` now seem to be `ES5` compliant.
=> fix(build): builds are now es5 compliant

webpack.config.js
I think that specifying the preset option in the webpack config will override whatever we have in the `.babelrc`, which was causing ES6 code to end up in the themeable target (the "env" preset compiles down to ES6 stuff by default).
=> build(webpack): keep babel config only in .babelrc

.storybook/__snapshots__/Storyshots.test.js.snap, src/Table/README.md, src/Table/Table.scss, src/Table/Table.stories.jsx, src/Table/Table.test.jsx, src/Table/index.jsx
This is a feature that studio-frontend needs so that long filenames will not make the columns jump around jarringly when filtering or paging. I pulled the classnames from this [stackoverflow answer](https://stackoverflow.com/a/37928581/6620612).
FYI @edx/educator-dahlia
=> feat(table): Add tableFixed option to set col widths

package-lock.json, package.json
`email-prop-type@1.1.5`, triggered by [`email-prop-type#22`](https://github.com/jaebradley/email-prop-type/pull/22), was verified to be `IE11`-compliant by @thallada. This updates the `email-prop-type` version in Paragon.
cc: @arizzitano
=> fix(email-prop-type): upgrade to IE11 compatible version

src/Table/README.md
=> docs(table): no hasFixedColumnWidths in IE11

src/Modal/Modal.test.jsx, src/Modal/index.jsx
Modal should re-open if a parent updates its props to `{open: true}`.
=> fix(modal): allow reopening after close

LICENSE, package.json
I noticed that we don't have a LICENSE file and that the [MIT](https://tldrlegal.com/license/mit-license) license is specified in the `package.json`.
I think that [Apache 2.0](https://tldrlegal.com/license/apache-license-2.0-(apache-2.0)) is preferred at edX for libraries that have a broad interest which we want other developers to use, see: https://openedx.atlassian.net/wiki/spaces/OPEN/pages/13959332/Licensing
I made this a `fix` so that semantic version will update the patch version for this change in case. If someone is already using this library and for whatever reason cannot comply with the Apache license then they can pin to the version of Paragon before this change.
FYI: @nedbat
=> fix(license): switch from MIT to Apache 2.0

.storybook/__snapshots__/Storyshots.test.js.snap, src/Table/Table.test.jsx, src/Table/index.jsx
This is some additional styling that I found out was needed when using `hasFixedColumnWidths` in studio-frontend's table. It doesn't visually change anything in storybook, but `display: inline` prevents the columns from shifting slightly when the cell contents changes in studio-frontend.
=> fix(table): fixed: add d-inline to thead & tbody

src/asInput/README.md, src/asInput/asInput.test.jsx, src/asInput/index.jsx
As discussed in IRC, we felt like this was a reasonable way to:
- Let a validator be async
- Let a container have dependencies between children validations (like invalidate child2 when child1 changes)
I decided to ignore these new properties if the older 'validator' property is set to a function.
I didn't modify the storybook, since we already had a validator and the form doesn't look any different than that. But am happy to add one if you folks like.
@arizzitano and @thallada, at least, were interested in this I believe.
=> feat(asinput): add "isValid" and "validationMessage" props

.storybook/__snapshots__/Storyshots.test.js.snap, src/InputText/InputText.stories.jsx, src/asInput/README.md, src/asInput/index.jsx
Input elements of type "number" have a Number value. React accepts a string or a number.
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number#Value
FYI: @MichaelRoytman I think that this will resolve the console errors we are seeing in studio-frontend.
=> fix(asinput): allow value of type number or string

.storybook/__snapshots__/Storyshots.test.js.snap, src/asInput/README.md, src/asInput/asInput.test.jsx, src/asInput/index.jsx
Also, allow passing `validationMessage` as an element.
These are some additions to the [PR](https://github.com/edx/paragon/pull/196) @mikix merged last week. I only noticed these things after I tried to use `isValid` and `validationMessage` in studio-frontend.
=> fix(asinput): add dangerIconDescription as prop

.storybook/__snapshots__/Storyshots.test.js.snap, src/StatusAlert/StatusAlert.stories.jsx, src/StatusAlert/StatusAlert.test.jsx, src/StatusAlert/index.jsx
This would allow the component to support i18n and enable the addition of context specific labels to the close button (e.g. 'Close the edX Cookie Policy alert.').
=> fix(status-alert): fix add ability to set close button aria-label

src/InputText/InputText.test.jsx, src/asInput/index.jsx
InputText was rendering array positions from the ```className``` array instead of the strings passed in. This PR resolves that issue.
=> fix(as-input): renders classNames to DOM

.storybook/Storyshots.test.js, .storybook/__snapshots__/Storyshots.test.js.snap, src/Modal/Modal.stories.jsx, src/Modal/Modal.test.jsx, src/Modal/README.md, src/Modal/index.jsx
Modal currently does not render on bootstrap pages, because paragon uses class names different from the default bootstrap class names. This PR brings the modal more in line with bootstrap's default modal and renders the modal via [```createPortal()```](https://reactjs.org/docs/portals.html)
=> feat(modal): add parentSelector prop, use portals

.storybook/__snapshots__/Storyshots.test.js.snap, src/InputText/InputText.stories.jsx, src/asInput/README.md, src/asInput/asInput.test.jsx, src/asInput/index.jsx
Per [Bootstrap 4's documention](https://getbootstrap.com/docs/4.0/components/input-group/#multiple-addons) for multiple input group addons, this PR adds the ability to pass in an array of elements to the `inputGroupPrepend` and `inputGroupAppend` props in the `asInput` component.
=> fix(as-input): support multiple input group addon elements

src/Modal/Modal.scss, src/Modal/Modal.stories.jsx, src/Modal/Modal.test.jsx, src/Modal/index.jsx
This PR fixes a few things:
1. Removes now-unused `.modal-open` styles (the class is now `.show`).
2. When modal body content overflows the screen height, it will now contain it to a scrollable container and still show the modal buttons at the bottom of the screen.
3. In IE11, which has bugs with the flexbox layout which breaks 2, always show a scrollbar when a modal is open which will allow scrolling of the entire modal when it overflows the screen. The scrollbar will be visible even when the modal does not overflow because `overflow: auto` was not working. This should only affect IE11.
4. Use `position: fixed` on the `.modal` div so that it does not push contents that are in the DOM after it down the page when it opens (the modal will now display over top of the background elements).
5. …
=> fix(modal): handle overflowing content

.storybook/__snapshots__/Storyshots.test.js.snap, src/InputText/index.jsx, src/SearchField/README.md, src/SearchField/SearchField.scss, src/SearchField/SearchField.stories.jsx, src/SearchField/SearchField.test.jsx, src/SearchField/index.jsx, src/asInput/README.md, src/asInput/asInput.test.jsx, src/asInput/index.jsx
Adds a `SearchField` component, which makes use of the `InputText`, `Button`, and `Icon` components.
**Example**
**Customizable Options**
The `SearchField` component is customizable in the following ways:
* _Callbacks_: Callback handlers for `onSubmit`, `onFocus`, `onBlur`, and `onChange` events;
* _Input label_: A string that is passed to the `InputText` component.
* _Placeholder_: Placeholder text for the `InputText` component.
* _Screenreader Text_: An object containing screenReaderText strings to use for the clear and submit search buttons.
* _Value_: An initial value to populate the input field with.
**Accessibility**
Since `SearchField` uses the `InputText` and `Button` components, most of the accessibility concerns are handled already. However, because `SearchField` can be …
=> feat(search-field): New SearchField component

src/Modal/index.jsx
Fixes: EDUCATOR-2999 (FYI: @edx/educator-dahlia)
Before, passing an element to the `closeText` prop would cause the modal's x
button's `aria-label` to be `[object Object]`. Now, the button is labelled by
the close button in the modal footer so that the screenreader reads out the same
text for both buttons.
=> fix(modal): x aria-labelledby closeText element

.storybook/__snapshots__/Storyshots.test.js.snap, package-lock.json, package.json, src/Button/index.jsx, src/Pagination/Pagination.scss, src/Pagination/Pagination.stories.jsx, src/Pagination/Pagination.test.jsx, src/Pagination/README.md, src/Pagination/index.jsx, src/Responsive/README.md, src/Responsive/Responsive.test.jsx, src/Responsive/index.jsx, src/index.js, src/utils/getTextFromElement.js, src/utils/reactResponsive.mock.js, src/utils/utils.test.js, src/utils/utils.test.jsx
This PR adds an accessible and responsive `Pagination` component ([view demo](http://stale-cause.surge.sh/?selectedKind=Pagination)):
To make the `Pagination` component responsive, I am using [`react-responsive`](https://github.com/contra/react-responsive) to create several wrapper components that render its children depending on window size, according to the [Bootstrap-defined breakpoints](https://getbootstrap.com/docs/4.0/layout/overview/#responsive-breakpoints) (e.g., `<ExtraSmall>` will only render its children for window sizes less than `576px`).
Another thing to note is that the `aria-label` attribute on buttons is dynamically created to be more understandable and descriptive for screen readers. For example, when tabbing between pages, the `aria-label` for a currently selected page …
=> feat(pagination): add Pagination and Responsive components

src/Pagination/index.jsx
Settings the focus in `componentDidUpdate` is for when a page button is clicked when there are ellipses included in the pagination. The buttons are re-rendered so the originally clicked button element no longer exists in the DOM, so the focus is lost. The logic in `componentDidUpdate` puts the focus back on the appropriate button.
However, the current logic puts the focus on the current page button when the `currentPage` prop is changed, which causes the `Pagination` component to "steal" the focus on the page incorrectly.
As such, this PR updates the `componentDidUpdate` logic to only set focus if a page button was explicitly clicked.
=> fix(pagination): set focus only for explicitly clicked pages

.eslintrc.json, .storybook/__snapshots__/Storyshots.test.js.snap, src/Dropdown/Dropdown.stories.jsx, src/Dropdown/Dropdown.test.jsx, src/Dropdown/README.md, src/Dropdown/index.jsx
Allows the user to pass in an array of elements to the `menuItems` prop. The use case for this is using the `Dropdown` component for navigation within a single-page application that uses `react-router` where the menu item should be a `Link` component, not an anchor tag.
Additionally, this makes it so that the user can trigger a click on a focused menu item (i.e., to actually be able to click the anchor tag/element).
=> fix(dropdown): select menu item by keyboard, menu items as elements

webpack.config.js
To support production builds you must pass 'production' as the process.env.NODE_ENV variable to webpack modules through DefinePlugin. This allows modules like react-dom to know they are building in a production environment.  This is outlined in the react documentation here: https://reactjs.org/docs/optimizing-performance.html#webpack
While we were setting the NODE_ENV when building in the package.json file, we weren't passing it through DefinePlugin.
This was resulting in bundles that included unexpected libraries such as react-dom, even though they were included as externals (react-dom-server.browser.development.js):
~~By fixing this, we are no longer including react-dom in our bundle.~~ Spoke too soon, looks like react-dom is still here, but at least its the production version. Still …
=> fix(webpack): pass process.env.NODE_ENV to DefinePlugin for prod builds

.storybook/__snapshots__/Storyshots.test.js.snap, src/InputText/InputText.stories.jsx, src/InputText/InputText.test.jsx, src/InputText/README.md, src/InputText/index.jsx
This work is done as part of [LEARNER-6116](https://openedx.atlassian.net/browse/LEARNER-6116). 
Adds an optional readOnly attribute to the inputText component since Firefox does not allow users to copy text from a disabled field.
**Storyboard**
If the reviewer decides that this doesn't need its own story, I'm happy to remove it.  Added just to give an idea of the UI.
=> feat(input-text): add readonly

.storybook/__snapshots__/Storyshots.test.js.snap, src/SearchField/SearchField.scss, src/SearchField/index.jsx
Nest search classes under `.search-field` for specificity such that search classes get precedence over Bootstrap's classes.
=> fix(searchfield): nest search classes under .search-field

.storybook/__snapshots__/Storyshots.test.js.snap, src/Tabs/README.md, src/Tabs/Tabs.test.jsx, src/Tabs/index.jsx
Tabs component didn't allow tab navigation or keyboard navigation. To meet accessibility best practices, it was determined to follow an implementation similar to:
http://pauljadam.com/demos/aria-tabpanel.html
=> fix(tabs): fix naviation in Tabs component

src/SearchField/SearchField.scss
One last style fix for the `SearchField` component. The `.focused` class `border-color` property requires `!important` to take precedence over Bootstrap.
=> fix(searchfield): .search-field.focused style fix

.storybook/__snapshots__/Storyshots.test.js.snap, src/Hyperlink/Hyperlink.stories.jsx, src/Icon/README.md
Update HyperLink story to use Icon component instead of inline span
Help to clarify https://github.com/edx/paragon/issues/325
FYI @edx/fedx-team
=> docs(hyperlinkicon): update HyperLink story to include example with Icon

docs/decisions/0001-record-architecture-decisions.rst
We'd like to use Architectural Decision Records to document decisions
made about the future direction of the paragon pattern library. This
was approved by a voice vote at a meeting of the FedX group on
Thursday, 10/18/18.
Would love to see thumbs all around once more on this PR from @edx/fedx-team! 
Pushing this up to get the ball rolling w.r.t. ADRs, another one incoming directly after this! Just also wanted to see whether semantic release/our CI more generally will treat it how I think it ought to be treated.
=> (docs): initial ADR about using ADRs

src/SearchField/index.jsx
This PR fixes the following issue: https://github.com/edx/paragon/issues/356
Now, the `SearchField` component keeps track of when a search has been submitted. The clear button will be rendered if a search has been submitted regardless of whether the input has a non-empty value. The `hasSubmitted` state is reset to `false` on clear.
I've also included a minor refactor to remove the use of `componentWillReceiveProps` (in favor of `componentDidUpdate`) as this lifecycle method will be become deprecated in React. I also moved the prop types configuration to the bottom of the file.
=> fix(searchfield): show clear btn after submit when input has no value

src/Dropdown/Dropdown.test.jsx, src/Dropdown/index.jsx
DropDown was getting **focused** for some unwanted scenarios, 
For example: on page load, if any parent component of DropDown updated, DropDown was getting focus,  as updates of DropDown was also getting called that was causing DropDown to get focus.  
Issue reference: [Story](https://openedx.atlassian.net/browse/WL-1828)
=> fix(dropdown): fixed DropDown focus on page load

src/index.js
Currently, we are not exporting the `ValidationMessage` component in Paragon. As such, consumers of Paragon can not use the `ValidationMessage` component or the established responsive breakpoints. 
Both of these are things I would like to be used in `edx-portal`.
=> feat(exports): export breakpoints & validationmessage

.storybook/__snapshots__/Storyshots.test.js.snap, src/InputSelect/InputSelect.stories.jsx, src/InputSelect/index.jsx
Adds support for disabling options within the `InputSelect` by passing in a `disabled` key to the options array of objects, e.g.:
```jsx
<InputSelect
name="fruits"
label="Fruits"
value="strawberry"
options={[
{ label: 'apple', value: 'apple' },
{ label: 'orange', value: 'orange', disabled: true },
{ label: 'banana', value: 'banana', disabled: true },
]}
/>
```
=> fix(inputselect): support disabled options

src/Modal/Modal.test.jsx
No need for an error boundary component.  Uses “shallow” to avoid full mounting in jsdom, which is what spits out an error to the console.
=> fix(tests): tests modal error throwing in a supported way

docs/decisions/0003-repository-ownership.rst, docs/decisions/0004-usage-of-bootstrap.rst, docs/decisions/0005-usage-of-reactstrap.rst
tl;dr -
1. Arch team will take "ownership" of Paragon.  (this is more an offer of coordination than anything else)
2. We use Bootstrap.
3. We will start using Reactstrap.
All three are obviously proposals - exact details are up for discussion.  None of this is expected to be controversial or ruffle any feathers - if it does, let's talk!  I must not have talked to you about it yet.
I intend to bring this up for discussion at the next Fedx meeting to solicit feedback.
=> Creation of three new ADRs for paragon

.storybook/Storyshots.test.js, .storybook/__snapshots__/Storyshots.test.js.snap, src/asInput/asInput.test.jsx, src/utils/newId.js, src/utils/utils.test.jsx
Previously, newId would prevent duplicates of ids within the same component, but if you used multiple of the same component on a page, the ids could end up being duplicated. This change should make it extremely unlikely that any two generated ids are the same
=> fix(utils): prevent newId from duplicating ids

.eslintignore, .gitignore, README.md, package.json, webpack.config.js
Eliminating the static build target provides us a simpler project setup and sets the stage to eliminate css modules and some of the problems caused by its current implementation.
The static build is used only in some places in edx-platform:
https://github.com/search?q=org%3Aedx+%22paragon%2Fstatic%22&type=Code
=> feat: remove static build output

.storybook/__snapshots__/Storyshots.test.js.snap, docs/decisions/0007-component-api-guidelines.rst, src/Button/index.jsx, src/Fieldset/index.jsx, src/Icon/index.jsx, src/InputSelect/index.jsx, src/InputText/index.jsx, src/ListBox/index.jsx, src/ListBoxOption/index.jsx, src/Pagination/Pagination.test.jsx, src/Pagination/index.jsx, src/StatusAlert/StatusAlert.test.jsx, src/StatusAlert/index.jsx, src/Table/Table.test.jsx, src/Table/index.jsx, src/TextArea/index.jsx, src/ValidationMessage/index.jsx, src/asInput/asInput.test.jsx, src/asInput/index.jsx, src/withDeprecatedProps.jsx
https://github.com/edx/paragon/blob/0ed00616ced96a194783199021a4053037482149/docs/decisions/0007-component-api-guidelines.rst
It also replaces all instances of className props that expected an array to expect a string. All component className props should be specified like this `<Button className="class-1 class-2" />`.
Done using a higher order component `withDeprecatedProps(Component, deprecatePropsObject)`. See here: https://github.com/edx/paragon/compare/abutterworth/change-classname-prop?expand=1#diff-ae4333267b91c362443ba82a15031f3a
=> ADR for Prop Naming and change classNames to strings

.storybook/__snapshots__/Storyshots.test.js.snap, src/Button/index.jsx, src/Hyperlink/Hyperlink.test.jsx, src/Hyperlink/index.jsx, src/MailtoLink/MailtoLink.test.jsx, src/MailtoLink/index.jsx, src/Modal/index.jsx
Leverage the withDeprecatedProps high order component to move Button `label` and Hyperlink `content` to `props.children` in a backward compatible way. Usage of these components with deprecated props will show warnings in development.
=> Prefer children over props

.storybook/__snapshots__/Storyshots.test.js.snap, package-lock.json, package.json, src/TransitionReplace/DemoTransitionReplace.jsx, src/TransitionReplace/README.md, src/TransitionReplace/TransitionReplace.scss, src/TransitionReplace/TransitionReplace.stories.jsx, src/TransitionReplace/TransitionReplace.test.jsx, src/TransitionReplace/index.jsx, src/index.js, src/index.scss, webpack.config.js
Manages a transition when replacing content. By default this component will transition the height and do a cross-fade. The transition can be customized.
TransitionReplace expects only one child at any time. Swap content inside the component (usually based on some state).
```jsx
<TransitionReplace>
{this.state.isEditing ? (
<form key="the-form">
<label htmlFor="name">First Name</label>
<input type="text" value={name} />
<button type="submit">Save</button>
</form>
): (
<div key="other">
<h4>First Name</h4>
<p>{name}</p>
</div>
)}
</TransitionReplace>
```
**IMPORTANT NOTE: You must provide the `key` prop for all children**, even when only rendering a single item. This is how React will determine that a child is new rather than just updated.
TransitionReplace uses [CSSTransition from the …
=> Add transition replace

.eslintignore, index.js, package.json, src/Button/index.jsx, src/Hyperlink/index.jsx, src/Icon/index.jsx, src/InputSelect/index.jsx, src/InputText/index.jsx, src/MailtoLink/index.jsx, src/StatusAlert/index.jsx, src/Table/index.jsx, src/TextArea/index.jsx, src/asInput/index.jsx, src/withDeprecatedProps.jsx
Deprecation warnings were not showing in consuming applications because Paragon was using `process.env.NODE_ENV` to determine if a warning should be logged. Since this is always 'production' in the built, consumed version of Paragon, no warnings would be shown.
Now, the entry point for Paragon is `/index.js` which will set a variable `PARAGON_ENV` on the window during development. Since this file is not built by webpack it has access to the parent application's `process.env.NODE_ENV` value.
Lastly, a small change to `withDeprecatedProps` adds a parameter to specify the component name as a string. This way warnings will show the specified component name and not a minified one.
Result:
=> Show warnings during development

.eslintignore, index.js, package.json, src/withDeprecatedProps.jsx, webpack.config.js
In order to gain access to `NODE_ENV` previously we had added a variable on the window. This approach is better and is hinted at here: https://github.com/webpack/webpack/issues/6673
=> fix: use webpack config to pass through NODE_ENV

.storybook/__snapshots__/Storyshots.test.js.snap, package-lock.json, src/CheckBox/CheckBox.test.jsx, src/CheckBox/index.jsx, src/InputSelect/index.jsx, src/InputText/index.jsx, src/TextArea/index.jsx, src/asInput/index.jsx
- Pulls unneeded properties out of props (and therefore out of `...other`). 
- Adds `aria-describedby={describedBy}` on checkboxes which seemed to be missing. @wittjeff do you know if this was intentional?
- Adds `asInput` prop types and then `withDeprecatedProps` to `Checkbox` to satisfy react/prop-types linting requirements
=> fix: pull unused vars out of props to prevent adding them to html tag

.storybook/__snapshots__/Storyshots.test.js.snap, package-lock.json, package.json, src/CheckBox/CheckBox.test.jsx, src/CheckBox/index.jsx, src/InputSelect/index.jsx, src/InputText/InputText.stories.jsx, src/InputText/index.jsx, src/TextArea/index.jsx, src/asInput/index.jsx
This way properties that we don't explicitly care about can still get through to the underlying input element. There are a lot of input props, seems unnecessary to gatekeep them.
In my immediate case, I was interested in using min and step - hence the new storybook that uses them.
I also set a version for jest-cli, which had an implicit version before at 20.x or something. I hit an error when updating the snapshot that was fixed in 22.x, so I set it's version to match the version we demand for just "jest".
=> fix: pass through unknown props for asInput components

.storybook/__snapshots__/Storyshots.test.js.snap, src/Input/Input.stories.jsx, src/Input/README.md, src/Input/index.jsx, src/ValidationFormGroup/ValidationFormGroup.stories.jsx, src/ValidationFormGroup/index.jsx
This PR illustrates an option regarding what to do about html inputs. We've discussed simply using the html directly. This represents another option, creating a single component interface for all user input html tags (select, textarea, input(s)). My thoughts on pros/cons:
Pros:
- No need to remember bootstrap class names
- It enforces labelling in development mode by checking if the html element has an associated label tag or aria-label attribute on `componentDidMount`
- A single component for all kinds of input elements would make some templated code easier to write (imagine iterating through an array for field definitions and choosing whether to render a select, text, or other input type)
- We could require users of the component specify an id, encouraging them to add an associated …
=> For discussion: One Input component to rule them all

.storybook/__snapshots__/Storyshots.test.js.snap, src/StatefulButton/__snapshots__/StatefulButtontest.test.jsx.snap, src/StatefulButton/index.jsx
- Change labels proptype to accept nodes instead of just strings. (helpful when using ReactIntl
- Instead throw away click events instead of using the disabled attribute to disable the button
=> fix: update proptypes change disabled behavior

.storybook/__snapshots__/Storyshots.test.js.snap, src/ValidationFormGroup/__snapshots__/ValidationFormGroup.test.jsx.snap, src/ValidationFormGroup/index.jsx
The red text conveys semantic emphasis using color and font weight. For WCAG 2.1, the semantics need to be exposed programmatically as well. To do this, we use <strong/> elements and attach the formatting classes to them.
=> fix: update invalid feedback to be strong

src/Input/index.jsx
Supplying a ref to an Input component no longer errors out in development. This is a better strategy at "merging" refs inspired by this thread: https://github.com/facebook/react/issues/13029#issuecomment-497315277
=> fix: successfully merge refs in Input

www/src/pages/components/modal.mdx
Modal is breaking in gatsby, therefore preventing the doc site from being built. This needs to be updated in the modal component in the future.
=> docs: remove interactive modal breaking gatsby build

scss/core/utilities-only.scss, scss/edx/utilities-only.scss, www/gatsby-node.js, www/package.json, www/src/components/CSSUtilitiesTable.jsx, www/src/components/navigation.jsx, www/src/pages/foundations/colors.mdx, www/src/pages/foundations/css-utilities.mdx, www/src/pages/foundations/layout.mdx, www/src/pages/foundations/spacing.mdx, www/src/pages/foundations/typography.mdx, www/src/utils/getCssSelectors.js
Guides and examples still need to be written above these tables, but together these are a pretty good index of all the css utils available.
=> docs: add CSS utility classes to doc pages

package.json
The `--copy-files` CLI option will cause babel to include all files that it didn't process, which will copy over the test.js and stories.js files we don't want in addition to the .scss files we _do_ want.  So after babelizing, `rm` the test and stories files from the dist directory.  
If this gets any more complex we may want to consider adding a build process again.
=> fix: include scss files in dist

Makefile, package.json
We were getting some test gunk in the `dist` directory.  This should tighten that up to include only the files we really want in `dist`.
=> build: tighten up dist directory

.storybook/__snapshots__/Storyshots.test.js.snap, src/Icon/Icon.test.jsx, src/Icon/index.jsx, src/StatefulButton/__snapshots__/StatefulButtontest.test.jsx.snap
Setting the `id` property in `Icon.defaultProps` to `newId('Icon')` makes every Icon that doesn't explicitly provide an id have an identical id property, since `newId('Icon')` gets eveluated at module load time. Duplicate `id`s are not valid HTML.
We are already invoking `newId('Icon')` inside the `Icon` component's render method if no id is provided, so we can safely set the `id` in `defaultProps` to `undefined` and let the default `id` get generated at render time.
**Testing instructions**
1. Without this patch: Render two or more `<Icon>` components on a page. Notice that they all have the same id (`'Span1'`).
2. Do the same with this patch. Notice that the `id`s are no longer identical.
**Reviewers**:
=> fix: do not set a default id for Icon component

src/Modal/Modal.test.jsx, src/Modal/index.jsx
@adamstankiewicz @abutterworth 
Changed the event handler from onClick to onMouseDown. Previous issue was that clicking on modal and dragging to outside modal closes the modal. Discussed that changing the even handler was an okay patch. 
This fix is related to sprint ticket in Enterprise: 
https://openedx.atlassian.net/browse/ENT-1966
edx-portal is currently using paragon version 3.8.1 (based on package.json)
=> fix: modal to not close when mouse drag from in modal to out

src/Button/index.jsx, src/CheckBox/index.jsx, src/InputSelect/index.jsx, src/InputText/index.jsx, src/TextArea/index.jsx, src/asInput/index.jsx
Ensuring that proptype validation if inputRef in asInput includes both functions and objects. This is because creating a previous ref used a function, where React.createRef will create an object
=> fix(asinput): proptype validation to include both func and obj

src/Button/index.jsx, src/CheckBox/index.jsx, src/InputSelect/index.jsx, src/InputText/index.jsx, src/TextArea/index.jsx, src/asInput/index.jsx
Our prop types fix was using `Element` instead of `PropTypes.element` causing our gatsby build to fail. This PR fixes that issue by using `PropTypes.element`.
=> fix(prop-types): use PropTypes.element instead of Element

scss/edx/_variables.scss
Updated to now be accessible (3:1 contrast).
=> fix: input focus color now accessible

.travis.yml
Builds complain of npm version 5 in concert with node 12. Use npm 6 for travis.
=> fix: update npm version in travis.yml

package-lock.json, package.json, www/package-lock.json
We accidentally re-added react as a normal dependency to the library. Now when people import it, they get two versions of react. This fix puts in into peer (for the library) and dev (for testing/travis).
=> fix: remove react from dependencies. Addback to peer/dev dependencies

scss/core/_extensions.scss, scss/core/extensions/_forms.scss, scss/edx/_overrides.scss, scss/edx/_variables.scss, scss/edx/overrides/_forms.scss
Add validation icons to help text:
Focus state:
=> fix: update field validation style

src/Modal/index.jsx
Because `closeModalButtonId` is defined outside of the class, new instances of a modal on the same page do not cause the id to update with an incrementing number, e.g. "paragonCloseModalButton3" --> "paragonCloseModalButton4". Instead, they all are set at ""paragonCloseModalButton1".
Also, the close button does not currently have an id on it so the close button was trying to be labelling by an unreferenced button.
=> fix(a11y): ensure close button gets an id and is referenced properly

package-lock.json, package.json, scss/core/extensions/_utilities.scss, src/Fieldset/Fieldset.scss
Eliminate this noise from builds:
```
WARNING: The `form-control-focus()` mixin has been deprecated as of v4.4.0. It will be removed entirely in v5.
on line 8 of node_modules/bootstrap/scss/mixins/_deprecate.scss, in mixin `deprecate`
from line 26 of node_modules/bootstrap/scss/mixins/_forms.scss, in mixin `form-control-focus`
from line 15 of node_modules/@edx/paragon/src/Fieldset/Fieldset.scss
from line 3 of node_modules/@edx/paragon/src/index.scss
from line 1 of node_modules/@edx/paragon/scss/core/_components.scss
from line 45 of node_modules/@edx/paragon/scss/core/core.scss
from line 2 of src/sass/base/_paragon.scss
from line 4 of stdin
WARNING: The `bg-variant` mixin has been deprecated as of v4.4.0. It will be removed entirely in v5.
on line 8 of …
```
=> fix: ignore deprecation warnings for bootstrap v5

package-lock.json, package.json
Not sure why this is still in here, but it's not needed.
=> fix: remove edx bootstrap from dependencies

src/SearchField/SearchField.scss
Turns out `role="searchbox"` on the input still adds the browser native "X" button to clear input. Adding back in the styles to override this behavior and hide the native "X" button.
=> fix(searchfield): remove browser "X" icon

src/SearchField/SearchFieldAdvanced.jsx
When using the `SearchField`, I realized the `value` prop I was passing in was not properly updating on successive component re-renders. To fix, I needed to set the state `value` anytime the prop `value` changes to force the prop `value` to be used.
=> fix(searchfield): update state value when prop value changes

docs/decisions/0008-abandon-reactstrap.rst, docs/decisions/0009-usage-of-react-bootstrap.rst
The gist: We will include react-bootstrap components in Paragon. Paragon will continue to contain custom-written components, but for any component that exists in react-bootstrap we will use the react-bootstrap version instead of building our own.
=> Adopt react-bootstrap ADR

src/Table/index.jsx
Fixes in appropriate primary button styling
Should now appear like this:
=> fix: update the usage of button internal to Table

README.md, www/src/components/layout.jsx, www/src/scss/_layout.scss
Satisfy the requirements in the Netlify Open Source Plan Policy: https://www.netlify.com/legal/open-source-policy/
- Adds a link to our code of conduct in the Readme and Documentation Site
- Adds a Netlify badge to the doc site footer
=> docs: add netlify open source plan requirements to documentation

www/src/pages/index.mdx
Add the npm version badge to the documentation landing page.
=> docs: add latest version number to doc landing

src/ValidationFormGroup/ValidationFormGroup.test.jsx, src/ValidationFormGroup/index.jsx, www/src/pages/components/validationformgroup.mdx
Adds support for FormControl (aka Form.Control) to the ValidationFormGroup
Adds docstrings for ValidationFormGroup props
=> feat: add support for FormControl

package-lock.json, package.json, scss/edx/overrides/_buttons.scss, scss/edx/overrides/_modals.scss, scss/edx/overrides/_typography.scss, src/Icon/index.jsx, src/Modal/Modal.scss, src/Modal/Modal.test.jsx, src/Modal/index.jsx, www/src/pages/components/modal.mdx
This PR updates the `Modal` component to:
* better handle focus management through the use of `react-focus-on` (and `react-focus-lock` under the hood). 
* re-order the default modal footer close button with the custom `buttons` passed in via a prop.
* fixes the docs site for the `Modal` page.
* removes a deprecated lifecycle method.
[Deploy Preview](https://deploy-preview-577--paragon-edx.netlify.app/components/modal)
=> fix(modal): focus trapping with `react-focus-on` and `tabbable`

scss/core/_variables.scss, scss/core/overrides/_buttons.scss, scss/core/variables/_colors.scss, www/src/pages/components/button.mdx, www/src/pages/foundations/colors.jsx
Add brand as a core theme-color. By default it is the same as primary.
```
$brand-100, $brand-200, $brand-300, $brand-400, $brand-500, $brand-600, $brand-700, $brand-800, $brand-900
```
Add a tertiary btn variant. It is configurable with these new theme variables:
```
$btn-tertiary-color:          $gray-700 !default;
$btn-tertiary-bg:             transparent !default;
$btn-tertiary-hover-bg:       $light-500 !default;
$btn-tertiary-active-bg:      $light-500 !default;
```
=> feat: add brand core color and tertiary buttons

www/gatsby-node.js, www/package-lock.json, www/package.json, www/src/scss/index.scss, www/src/scss/stub-theme/_overrides.scss, www/src/scss/stub-theme/_variables.scss, www/src/scss/stub-theme/fonts.scss
- Use npm aliases for swapping the themes
- Now uses the brand-openedx theme by default
=> docs: use brand-edx.org theme for themed doc site

src/IconButton/_IconButton.scss, src/IconButton/index.jsx, src/Toast/Toast.test.jsx, src/Toast/_Toast.scss, src/Toast/index.jsx
Update toast spacing, alignment, and button style.
Update icon buttons to have transparent backgrounds by default. This is configurable via the new SASS vars:
```
$icon-button-bg: transparent !default;
$icon-button-invert-bg: transparent !default;
```
=> fix: update style of buttons in toast

scss/core/overrides/_buttons.scss, www/src/pages/components/button.mdx
A new size for buttons: Inline means the button size is dictated by surrounding text so that it can fit comfortably aligned inline.
=> feat: add inline button size

scss/core/overrides/_buttons.scss
This prevents inline buttons from being a border width taller than surrounding text.
=> fix: remove border from inline buttons

package.json
Add icons directory which was missing in the package json files array: https://docs.npmjs.com/cli/v6/configuring-npm/package-json#files
=> fix: include icons directory in npm publish

scss/core/_variables.scss, scss/core/extensions/_utilities.scss, www/src/pages/foundations/typography.jsx
[PAR-260](https://openedx.atlassian.net/browse/PAR-260)
Adds a `.x-small` css utility class for extra small type size. Introduces a theme variable: `$x-small-font-size: 75% !default;`
The screenshot below is the appearance of the typography section with https://github.com/edx/brand-edx.org/pull/26 brand update applied.
=> feat: add extra small font size

package-lock.json, package.json, scss/core/_variables.scss, src/Dropdown/_variables.scss, src/Navbar/_variables.scss, src/Pagination/_variables.scss
Bootstrap has continued to add and use new SCSS variables since Bootstrap 4.4.1. Since we no longer pull in all of Bootstraps variables (in order for us to colocate them with component styles) this is causing SASS compilation errors.
This PR pulls in all new variables as of bootstrap 4.6.0 and pins the version.
=> fix: add missing bootstrap variables

package.json
Uncontrollable, a React Bootstrap dependency released a new version 7.2.0 yesterday that publishes in es6. This is causing downstream problems in micro-frontends that need to support IE11 and non es6 browsers. Pinning uncontrollable to 7.1.1 in Paragon will likely solve the issue in the near term since React Bootstrap's package.json requires `"uncontrollable": "^7.0.0",`
Issue in uncontrollable here: https://github.com/jquense/uncontrollable/issues/51
=> fix: pin uncontrollable to preserve es5 output

src/Alert/Alert.scss, src/Alert/_variables.scss
Swap bootstraps alert mixin with just the styles required in Paragon. Fixes https://openedx.atlassian.net/browse/PAR-257
=> fix: remove alert link styling

scss/core/_typography.scss, scss/core/_variables.scss, www/src/pages/foundations/typography.jsx
**Introduce `.inline-link` and `.muted-link` styles**
Adds the concepts of standalone and inline link styling. Adds SCSS variables for theming:
```
$inline-link-color:                       $info-500 !default;
$inline-link-decoration:                  underline !default;
$inline-link-decoration-color:            rgba($inline-link-color, .3) !default;
$inline-link-hover-color:                 darken($inline-link-color, 15%) !default;
$inline-link-hover-decoration:            underline !default;
$inline-link-hover-decoration-color:      rgba($inline-link-hover-color, 1) !default;
$muted-link-color:                              $primary-500 !default;
$muted-link-decoration:                         none !default;
$muted-link-hover-color:                        darken($muted-link-color, 15%) …
```
=> feat: add additional typography styles

scss/core/_variables.scss, src/Sheet/Sheet.scss, src/Sheet/Sheet.test.jsx, src/Sheet/SheetContainer.jsx, src/Sheet/SheetContainer.test.jsx, src/Sheet/__snapshots__/Sheet.test.jsx.snap, src/Sheet/index.jsx, src/index.js, src/index.scss, www/src/components/navigation.jsx, www/src/pages/components/sheet.mdx
Implements a basic "Sheet" component, which serves as a basic UI container element bound to and spanning one edge of the window.
Supports light/dark theming, as well as content-blocking.
https://www.figma.com/file/eGmDp94FlqEr4iSqy1Uc1K/Paragon-2021?node-id=7520%3A16719
=> feat: new sheet component

src/Sheet/Sheet.scss, www/src/pages/components/sheet.mdx
Update background css variable for sheet component dark mode to work better in unbranded environment. 
Minor stylistic updates to example page to make more readable.
=> fix: sheet css theming and example updates

src/Modal/index.jsx
Changing the icon based on these mocks
https://www.figma.com/file/B6AF4htYRdesPBNR08Fzvp/Celebratory-Milestones?node-id=312%3A23
and this slack thread
https://edx-internal.slack.com/archives/G019J2RMNEA/p1612878880015500
fyi @abutterworth @ekangedx 
(Changing the x icon)
before:
after:
=> [AA-304]  change modal close icon from font awesome to paragon close icon

src/DataTable/DataTable.scss, src/DataTable/TableFooter.jsx, src/DataTable/tests/TableFooter.test.jsx, src/index.js, www/src/pages/table/tablefooter.mdx
Users can pass whatever components they want to be displayed in the footer
Defaults to the current RowStatus component on the left and TablePagination on the right
=> feat: make TableFooter more composeable

.eslintignore, dependent-usage-analyzer/.gitignore, dependent-usage-analyzer/README.md, dependent-usage-analyzer/checkout-dependents.sh, dependent-usage-analyzer/index.js, dependent-usage-analyzer/package-lock.json, dependent-usage-analyzer/package.json, dependent-usage.json
Generate Paragon component usage information within a dependent projects with this command line tool. This tool uses babel to parse a series of javascript projects as an abstract syntax tree and walks through it to gather information about usage of Paragon components (version and file line numbers).
Generating the usage of Paragon components in Open edX frontend projects is the first step toward creating an automated dashboard for what components at what versions are used in which Open edX projects. 
This PR fill be followed up with additional Github action workflows to automate running this script.
Make sure you're in this `dependent-usage-analyzer` directory, and then:
```
npm install
```
```
npm run analyze path/to/projects -- --out path/to/output.json
```
=> Add dependent usage analyzer

src/Modal/ModalCloseButton.jsx, src/Modal/ModalCloseButton.test.jsx, src/Modal/ModalContext.jsx, src/Modal/ModalLayer.jsx, src/Modal/ModalLayer.test.jsx, src/Modal/ModalPopup.jsx, src/Modal/ModalPopup.test.jsx
This renames the “close” handler in ModalLayer, ModalPopup, and the ModalContext to be “onClose”, which is a more canonical name for a handler.
Technically this is a breaking change, but since we have no known consumers of this component yet, we’re not marking it as so.
=> fix: renames close handler to onClose

src/Toast/_Toast.scss, src/Toast/_variables.scss
@abutterworth 
Ticket on Jira: https://openedx.atlassian.net/browse/PAR-289
Update toast component according to the new design: https://www.figma.com/file/eGmDp94FlqEr4iSqy1Uc1K/Paragon-2021?node-id=7583%3A878
=> [BD-35] PAR-289 feat: change styles according to new toast component design

www/src/pages/components/modal-layer.mdx, www/src/pages/components/modal-popup.mdx
When changing the close -> onClose function for ModalLayer and ModalPopup, I forgot to update the associated mdx docs.
=> docs: update mdx docs to use onClose for modal

scss/core/_grid.scss
The edx.org org theme has a troublesome max-width override set on .container-fluid. Adding these `!important` declarations is the simplest upgrade path for open edx consumers. After open edx consumers no longer rely on the edx.org brand theme to handle max widths, we can remove the offending style declaration and remove these `important` flags.
The problem appearing in the edx.org theme.
=> fix: force container sizes to obey max width

scss/core/_variables.scss, src/Button/_variables.scss, src/Form/_variables.scss, www/src/components/layout.jsx, www/src/components/navigation.jsx
Give edx.org developers higher confidence that what they ship in open edx applications will look similar when the edx.org brand is applied by reducing major differences between paragon default styles and edx brand styles.:
- Match font sizes in the type ramp (though line-heights are slightly different)
- Update colors to utilize the the color system in a similar way to edx.org. Notably: adds a magenta “brand” color.
The differences we'll maintain:
- Font family (system default san-serif vs. edx.org's use of Inter)
- Border radii. (rounded buttons vs. edx.org's square)
=> fix: update default styles to be less different from edx.org brand

src/Breadcrumb/index.jsx
=> fix: vertically align breadcrumb spacer with text

src/StatefulButton/__snapshots__/StatefulButtontest.test.jsx.snap, src/StatefulButton/index.jsx
Fixes `Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.`
For more details see https://github.com/facebook/react/issues/11538#issuecomment-390386520
=> fix: google translate issue with text nodes

www/src/components/Header.jsx
Remove scrollbar gaps appearing for macs with particular settings:
=> docs: fix scrollbar display

scss/core/_variables.scss, scss/core/core.scss
These were incorrectly removed when collocating css and javascript components: https://github.com/edx/paragon/pull/606
=> fix: reintroduce list group and media css

src/Form/FormCheckbox.jsx, src/Form/FormCheckboxSet.jsx, src/Form/FormCheckboxSetContext.jsx, src/Form/FormGroupContext.jsx, src/Form/FormSwitch.jsx, src/Form/FormSwitchSet.jsx, src/Form/_Form.scss, src/Form/_FormCheckbox.scss, src/Form/_variables.scss, src/Form/form-checkbox.mdx, src/Form/form-radio.mdx, src/Form/form-switch.mdx, src/Form/index.jsx, src/Form/tests/FormCheckbox.test.jsx, src/Form/tests/FormCheckboxSet.test.jsx, src/Form/tests/FormSwitch.test.jsx, src/Form/tests/useCheckboxSetValues.test.jsx, src/Form/useCheckboxSetValues.jsx, src/index.js, www/src/components/Header.jsx
Add `Checkbox`, `Switch`, `CheckboxSet` and `useCheckboxSetValues` to facilitate check-style options.
Individual usage:
```
() => {
const [isChecked, setChecked] = useState(false);
const handleChange = e => setChecked(e.target.checked);
return (
<Form.Checkbox checked={isChecked} onChange={handleChange}>
I want pizza.
</Form.Checkbox>
);
}
```
Set usage
```
() => {
const [colorValues, { add, remove }] = useCheckboxSetValues(['green']);
const handleChange = e => {
if (e.target.checked) {
add(e.target.value);
} else {
remove(e.target.value);
}
}
return (
<Form.Group>
<Form.Label>Which Color?</Form.Label>
<Form.CheckboxSet
name="colors"
onChange={handleChange}
value={colorValues}
>
<Form.Checkbox value="red">Red</Form.Checkbox>
<Form.Checkbox value="green">Green</Form.Checkbox> …
```
=> feat: add Checkbox, Switch, and CheckboxSet

package-lock.json, package.json
Pull in the fix here: https://github.com/react-bootstrap/react-overlays/pull/883 which was released in 4.1.1 of react-overlays
=> feat: upgrade react-bootstrap and react-overlays

src/DataTable/IndeterminateCheckBox.jsx, src/Form/FormCheckbox.jsx, src/Form/FormSwitch.jsx
react-testing-renderer does not handle refs in the same way as the browser does, causing a large console error. This change resolves that error.
=> fix: resolve console error during testing with react-testing-renderer

src/DataTable/index.jsx, src/DataTable/utils/getVisibleColumns.jsx, src/DataTable/utils/tests/getVisibleColumns.test.js, src/index.js
This allows for the selection column to be manually added, which is necessary when storing selections in a context outside the DataTable context.
=> feat: enable manual selection for DataTable

src/Hyperlink/index.jsx
Update HyperLink styling
```We just need to nudge it down a bit so it’s aligned with the baseline of the text. This link is in a paragraph so it will also need the underline.```
**NOTE: HyperLink text here is for testing purpose**
=> [TNL-8132] - fix: update styling for HyperLink component

src/DataTable/SmartStatus.jsx, src/DataTable/TableControlBar.jsx, src/DataTable/index.jsx, src/DataTable/tests/SmartStatus.test.jsx
I've got a couple of tables where I need the selection state to be controlled from outside the table context, and therefore, I need the display of the selection state to also be controlled from outside of the table context. This allows me to do so, with some defensive programming added in to cover different ways someone might want to use the control bar.
=> Make TableControlBar more flexible

src/Button/index.jsx
Avoids errors when passing different types of elements as Button children and icons.
=> fix: update Proptypes to avoid errors

scss/core/_utilities.scss, src/StatefulButton/README.md, src/StatefulButton/__snapshots__/StatefulButtontest.test.jsx.snap, src/StatefulButton/index.jsx
Update `statefullbutton` component. 
This PR changes a couple of things. 
1. Use icons from Pargon rather than fontawsome
2. Adds the ability to spin the pending icon. 
[TNL-8320](https://openedx.atlassian.net/browse/TNL-8320)
=> refactor: update statefullbutton icons

src/Form/FormControl.jsx, src/Form/FormControlDecoratorGroup.jsx, src/Form/form-control.mdx
Fixes a problem where setting the size prop on a form control with a floating label wouldn't affect the label's size.
=> fix: make floating label react to size prop

src/Stepper/Stepper.scss, src/Stepper/StepperHeader.jsx
- Fixed stepper padding issue with figma. 
- Fixed text in stepper according to figma as **Step 1 of 2** instead of **1 of 2** 
general note: created this PR against PAR-441 and we can close TNL-8134 as well after that.
FYI : @awaisdar001
=> style: text and padding fix for stepper component

src/Button/__snapshots__/Button.test.jsx.snap, src/Icon/index.jsx, src/StatefulButton/__snapshots__/StatefulButtontest.test.jsx.snap
https://openedx.atlassian.net/browse/PAR-432
An svg with an "img" role must satisfy the following a11y requirements
* It needs a text alternative in the form of aria-label, aria-labelledby, or screen-reader only text.
* If no label is desired, aria-label will be set to an empty string and aria-hidden to "true".
* focusable is set to false on the svg in all cases as a workaround for an ie11 bug
=> fix: enforce text alternative rules for svg icon

src/Modal/tests/ModalDialog.test.jsx, src/hooks/useIsVisible.jsx
Put usage of `IntersectionObserver` in a try catch so it does not need to be mocked in tests.
=> fix: make useIsVisible hook more resilient

src/Pagination/constants.js, src/Pagination/getPaginationRange.js, src/Pagination/index.jsx
Refactor how Pagination determines what page ranges to display. No longer uses recursion that was causing a `RangeError: Maximum call stack size exceeded` error. Fixes part of https://openedx.atlassian.net/browse/PAR-346
=> fix: prevent exceeding call stack size with 5000+ pages

src/Nav/Nav.scss, src/Nav/_variables.scss, src/Tabs/README.md
Pulls in bootstrap nav sass into Paragon with some minor customizations. Adds a `button-group` variant for tabs
=> fix: update tab styling to match design system

scss/core/_typography.scss, scss/core/_variables.scss, src/Hyperlink/README.md, src/Hyperlink/index.jsx, src/StatefulButton/__snapshots__/StatefulButtontest.test.jsx.snap, src/StatefulButton/index.jsx
Changes:
- Added a new prop to Hyperlink component that gives us an option to update the style of hyperlink. 
-- Some designs require no underline under hyperlink component. 
- Added aria-label for spinner icon
-- This is added to for accessibility because sometime stateful button has a pending state that doesn't have a text and only spinner is shown.
=> feat: add underline prop to hyperlink

scss/core/_utilities.scss, scss/core/_variables.scss, src/StatefulButton/index.jsx, www/src/pages/foundations/typography.jsx
- Added a new class for disclaimer text
- Fixed the stateful button spinner alignment in cases when no text is provided to the button:
|Before|After|
------|-------
https://openedx.atlassian.net/browse/VAN-546
https://openedx.atlassian.net/browse/VAN-593
=> feat: add disclaimer text class

scss/core/_variables.scss
After update from design team, the line height for `.micro` class needs to be updated. 
Made line height for micro text to be 15px
|Before|After|
|----|-----|
=> fix: update line height for micro text class

src/Modal/_ModalDialog.scss
Restricts the border on the modal footer to just the fullscreen modal. It was erroneously applied to the marketing modal before. Fix:
=> fix: remove border from dark modal footers

src/IconButton/_IconButton.scss
[TNL-8419](https://openedx.atlassian.net/browse/TNL-8419)
Before Change:
After Change:
=> fix: iconbutton size issue when using Paragon Icons

src/DataTable/README.md
Minor fix so that the docs doesn't 404 when linking to react-table.
=> fix: react-table docs link

src/Stepper/Stepper.scss
Added min-height to stepper header so it does not change its height in case of error. and updated the example with an error message.
=> fix: added min height to stepper header

src/Modal/_ModalDialog.scss
Ticket: https://openedx.atlassian.net/browse/TNL-8405
Issue: The issue was in the modal component in which the box-shadow was appearing under the child component.  The issue is fixed now by removing box-shadow and adding before and after pseudo-element in the modal body class with the linear gradient.
=> fix: fixed modal box shadow above page content

src/Modal/_ModalDialog.scss
-In reference to the [ticket](https://openedx.atlassian.net/browse/TNL-8405) the shadow issue was fixed in [this](https://github.com/edx/paragon/pull/757) [PR](https://github.com/edx/paragon/pull/757) upon integration with course authoring MFE, it turns out that the top shadow still hides under the page content if some other component is passed as children, hence to fix that a positive z-index of 2 is passed in top shadow which seems to fix the issue in course authoring use cases.
=> fix: top shadow fix for showing above page content

src/Alert/Alert.scss, src/Form/_Form.scss
1. set icon button color gray-500 while render in form.
**Results:**
Before
After
Related ticket:
https://openedx.atlassian.net/browse/VAN-523
2. set alert child content div width 100 %.
**Results:**
Before fix in paragon 
Expected result
Related ticket:
https://openedx.atlassian.net/browse/VAN-601
=> fix: form field default icon color

scss/core/_utilities.scss, www/src/pages/foundations/css-utilities.mdx
Updated `w-` utility class to incorporate breakpoints. For example `w-sm-100`, `w-md-auto`.
**Format**
`w-{breakpoint}-{size}`
**Breakpoints**
`xs`: @media(min-width: 0)
`sm`: @media(min-width: 576px)
`md`: @media(min-width: 768px)
`lg`: @media(min-width: 992px)
`xl`: @media(min-width: 1200px)
**Sizes**
`25`: 25%
`50`: 50%
`75`: 75%
`100`: 100%
`auto`: auto
=> feat: add breakpoints to width utility class

src/DataTable/README.md
This was breaking the docs site.
=> docs: fix unescaped quote in docs test data

package-lock.json, package.json
sanitize-html v2.x drops ES5 support, which means all our es5 checks fail.  Downgrading to revert, and will fix forward by trying to remove our dependency if at all possible, or including the package in babel transpilation
=> fix: downgrade sanitize-html to 1.x for es5 support

src/StatefulButton/StatefulButton.scss
Remove the opacity on pending state of the stateful button so that a crisp original color would be displayed in pending state.
VAN-605
**Before the fix:**
**After the fix:**
=> fix: remove opacity on stateful button

src/Alert/Alert.scss, src/Alert/__snapshots__/Alert.test.jsx.snap, src/Alert/index.jsx
=> fix: remove last margin of elements in Alert

package-lock.json, package.json, src/Modal/ModalDialog.jsx, src/Modal/modal-dialog.mdx, src/Pagination/Pagination.test.jsx, src/Responsive/Responsive.test.jsx
This Pr is created in reference to the ticket (https://openedx.atlassian.net/browse/TNL-8477) which requires modal dialog to be fullscreen on mobile view and on desktop as modal. 
- react responsive version is updated to 8.2.0
- isFullscreenOnMobile prop is passed in the modal dialog component which will help calculate if the fullscreen design is needed on mobile view. 
- docs are updated to match requirements
- updated test case for responsive component
- updated test cases for pagination
=> Modal dialog responsive view

src/Form/_Form.scss
On small screens, longer text labels spilling out of the input field, added text-overflow ellipses.
[VAN-672](https://openedx.atlassian.net/browse/VAN-672)
=> fix: label text spilling out of the field

src/Form/_FormText.scss
Fix Field error spacing issue in safari. Following is the screenshot of the reported problem.
[VAN-619](https://openedx.atlassian.net/browse/VAN-619)
=> fix: fix field error spacing issue

src/Modal/ModalDialog.jsx
[TNL-8583](https://openedx.atlassian.net/browse/TNL-8583)
Update mobile responsive breakpoint value from `max-width: 768px`  to `max-width: 767.98px` in modal dialog  useMediaQuery.  768px breakpoint was making fullscreen display in tablet view. Modal Dial should only full screen in mobile view.
=> fix: mobile view breakpoint resolution in useMediaQuery

src/Hyperlink/index.jsx
[TNL-8566](https://openedx.atlassian.net/browse/TNL-8566)
Add 8px margin-left space between external link help text and launch icon in Hyperlink component.
=> style: add 8px margin between external link help text and launch icon

src/Modal/_ModalDialog.scss
[TNL-8563](https://openedx.atlassian.net/browse/TNL-8563)
Set `z-index: 0` in modal dialog body ::before selector for non scrollable modals.  Modal dialog body top shadow `z-index` and `negative margin` were overlaying the content/button of non-scrollable. Which were affecting content onClick action. Modal shadow will work as normal for scrollable body content.
=> fix: remove modal dialog body before z-index for non scrollable modal

src/Stepper/Stepper.scss
[TNL-8572](https://openedx.atlassian.net/browse/TNL-8572)
1. Fix step alignment issue for mobile view in the stepper header component
Before center align
After center align
=> style: set stepper header step center alignment for mobile view

src/Hyperlink/index.jsx
[TNL-8588](https://openedx.atlassian.net/browse/TNL-8588)
Fix launch icon and text alignment to the vertical center 
before 
after
=> fix: set launch icon and external text alignment to the vertical center

src/DataTable/DataTable.scss, src/DataTable/DataTableLayout.jsx, src/DataTable/README.md, src/DataTable/SidebarFilters.jsx, src/DataTable/SmartStatus.jsx, src/DataTable/TableControlBar.jsx, src/DataTable/filters/CheckboxFilter.jsx, src/DataTable/filters/LabelledCheckbox.jsx, src/DataTable/index.jsx
Adds `showFiltersInSidebar` prop to view filters in sidebar.
See examples below:
Clear filter appears below when a filter is selected:
=> DataTable side filter on side in large windows

src/Card/CardSelect.jsx, src/Card/CardSelect.test.jsx, src/Card/README.md, src/Card/__snapshots__/CardSelect.test.jsx.snap, src/Card/index.jsx, src/index.js
Description: This PR adds a radio selectable card form group.
JIRA: https://openedx.atlassian.net/browse/ENT-4799
=> feat: Added CardSelect component

src/DataTable/DataTable.scss, src/DataTable/TableCell.jsx, src/DataTable/tests/TableCell.test.jsx
- removes TableCell wrapper from `<td>`
=> fix: removes TableCell wrapper

src/Menu/Menu.scss, src/Menu/SelectMenu.jsx, src/Menu/__snapshots__/SelectMenu.test.jsx.snap
The SelectMenu had several odd behaviors:
- The trigger button had no max size and would wrap text, causing inconvenience.
- Giving each menuItem a unique random uuid created difficulty because of the birthday paradox. Changed to use refs instead in much cleaner form.
- The popper could shift left/right if the size of the trigger button changed.
- offset sometimes wasn't perfect.
Note: this does not fix the scroll the whole page on center item errors.
=> fix: clean up SelectMenu Scrolling

src/DataTable/selection/ControlledSelect.jsx, src/DataTable/utils/getVisibleColumns.jsx, src/DataTable/utils/useConvertIndeterminateProp.js
Resolves the following prop type warning regarding `indeterminate` checkboxes in the `DataTable` component.
=> fix: resolve PropType warning for indeterminate prop in DataTable

src/Collapsible/index.jsx
Update the default icons on the collapsible from +/- to up-carat/down-carat
=> feat: change the default icons for the Collapsible element

src/DataTable/filters/CheckboxFilter.jsx
Small conditional change to 0 is rendered properly on filter label.
Before:
After:
=> fix: filtercheckbox filterchoices properly renders number 0

src/Form/_Form.scss
Ticket ID: https://openedx.atlassian.net/browse/TNL-8726
Date/Time Fields were not showing value when blurred out of the field due to opacity set to 0 on blur.
This PR contains a fix that opacity will only be set to 0 when the field does not contain any value.
=> fix: date-time input fields on blur issue

dependent-usage-analyzer/checkout-dependents.sh, dependent-usage.json, www/src/pages/insights.jsx
* Pulls new data for Paragon usage insights, adding in a few other repos that have Paragon installed as a dependency.
* Adds a "Summary" tab to include a table of how many times each component has been used across all projects.
=> fix: update usage stats and add summary tab

package.json, src/Button/index.jsx
Changes the `Button` component's `iconAfter` prop type to `PropTypes.oneOfType` instead of `PropTypes.instanceOf` to match the `iconBefore` prop. Also, generally it doesn't seem `PropTypes.instanceOf` actually supports passing an array to it for multiple types per its implementation:
https://github.com/facebook/prop-types/blob/4de0644a10a554d0a556daa39f029369bc007ea5/factoryWithTypeCheckers.js#L297-L307
Also, configures Jest to ignore tests in the `dependent-usage-analyzer` directory (which may include Git checkouts of 30+ projects). Running tests with these projects checked out resulted in Jest attempting to run tests in all projects.
=> fix: update iconAfter prop type definition

src/IconButton/index.jsx
Make the IconButton's onClick prop optional (similar to Button Component) so that it doesn't complain when not passed one, if the IconButton is being used as target of a Popover or other similar component.
=> feat: make IconButton onClick prop optional

src/DataTable/index.jsx, src/DataTable/utils/propTypesUtils.js, src/Modal/AlertModal.jsx, src/Modal/MarketingModal.jsx, src/Modal/ModalDialog.jsx, src/utils/propTypesUtils.js
Move requiredWhen from DataTable/utils/propTypesUtils into a top-level utils dir, and generalize into `customPropTypeRequirement`
`requiredWhen` and new `requiredWhenNot` methods wrap `customPropTypeRequirement`.
ModalDialog now forwards the `isBlocking` prop to the ModalLayer, and thus its inheritors now have that prop notated.
for MarketingModal and AlertModal, the `onClose` method is marked as required only if `isBlocking` is false-y.
=> feat: forward isBlocking to Alert and Marketing modals

src/Modal/ModalPopup.jsx
fix: Change ModalPopup positionRef Proptype to prevent error before ref is hydrated
=> fix: Change ModalPopup positionRef Proptype to prevent error before ref is hydrated

www/src/components/PropsTable.jsx
Improve `PropsTable` component to add info message in case when component does not have any props.
Previously for components without props the table would be rendered as follows:
this PR changes it to:
=> [BD-46] docs: add info message to empty PropsTables

README.md, www/src/pages/guides/installation-and-usage.mdx
Update installation docs to explain order of imports when working with a theme and update README with local development guide
JIRA:
- [PAR-117](https://openedx.atlassian.net/browse/PAR-117)
- [PAR-259](https://openedx.atlassian.net/browse/PAR-259)
=> [BD-46] docs: improve local development information

scss/core/_variables.scss, src/Form/FormCheckbox.jsx, src/Form/FormSwitch.jsx, src/Form/_Form.scss, src/Form/_variables.scss, src/Form/form-checkbox.mdx, src/Form/form-switch.mdx, src/Form/tests/FormSwitch.test.jsx
- Support label on the left for form.switch
- Change background color for form switch (we only need to support success variant)
- Add support for helper text below the switch
- Remove outline color variations
=> feat: update form switch per figma

src/DataTable/ActionDisplay.jsx, src/DataTable/index.jsx
This change makes sure that if we pass a function it is always rendered.
In `DataTable`, when passing a function through `tableActions` and `bulkActions`, with no parameters it would not render the component. This happened because we were (unintentianlly) counting the number of parameters in a function, if the function supplied took zero arguments the code would flag `noBulkActions` or `noTableActions` as true.
=> Fixed Datatable ActionDisplay to support functions

src/SearchField/README.md, src/SearchField/SearchField.scss, src/SearchField/SearchField.test.jsx, src/SearchField/SearchFieldAdvanced.jsx, src/SearchField/SearchFieldClearButton.jsx, src/SearchField/SearchFieldInput.jsx, src/SearchField/SearchFieldSubmitButton.jsx, src/SearchField/_variables.scss, src/SearchField/constants.js, src/SearchField/index.jsx
- added constants for the `variant` and `submitButtonLocation` props
- added functionality for the new properties: `variant`, `disabled`, `buttonText`
- added styles according to the [Figma design](https://www.figma.com/file/eGmDp94FlqEr4iSqy1Uc1K/Paragon-Design-System?node-id=14061%3A21)
- implemented the `submitButtonLocation` feature
- updated and added tests
- added a small example in the `README.md`
JIRA: [PAR-281](https://openedx.atlassian.net/jira/software/projects/PAR/boards/654?selectedIssue=PAR-281)
=> [BD-46] feat: implement new searchfield component design

www/src/components/CodeBlock.jsx
=> docs: collapse codeblocks by default

src/DataTable/CollapsibleButtonGroup.jsx, src/DataTable/tests/BulkActions.test.jsx, src/DataTable/tests/TableActions.test.jsx, src/Dropdown/Dropdown.scss, src/Dropdown/README.md, src/Dropdown/index.jsx, src/IconButton/index.jsx, src/index.js
- allow using `IconButton` as a base element for `Dropdown.Toggle`
- refactor usage of `Dropdown.Toggle` in `DataTable` as a result of the first change
JIRA: [PAR-334](https://openedx.atlassian.net/browse/PAR-334)
Preview: https://deploy-preview-939--paragon-edx.netlify.app/components/dropdown/#with-iconbutton
=> [BD-46] feat: allow using IconButton as a base element for Dropdown.Toggle

src/IconButton/_IconButton.scss
Removes the default blue outline on the `IconButton` component when focused since it has its own custom focus styles.
**Before:**
**After:**
https://deploy-preview-972--paragon-edx.netlify.app/components/iconbutton/#basic-usage-with-paragon-icon
=> fix: remove default outline on btn-icon-variant mixin

src/Card/README.md, src/IconButton/_IconButton.scss, src/index.js, www/src/components/CodeBlock.jsx
* Update the "Show code example" collapsible to be a button link
* Resolve errors when using now-deleted responsive components
* Add some spacing between docs examples
* Update `IconButton` focus outline for High Contrast mode support
=> "Show code example" as button link, resolve errors and add spacing to docs

src/Button/README.md, src/Spinner/README.md, src/Spinner/Spinner.test.jsx, src/Spinner/__snapshots__/Spinner.test.jsx.snap, src/Spinner/index.jsx, www/src/components/CodeBlock.jsx
Paragon ticket: https://openedx.atlassian.net/browse/PAR-457
* Added optional `screenReaderText` prop to provide accessible screenreader-only text and a `role="status"`.
* Added additional (pre-existing) examples to the `Spinner` docs.
PR previews:
1. [brand-edx.org](https://deploy-preview-976--paragon-edx.netlify.app/components/spinner/)
2. [core](https://deploy-preview-976--paragon-openedx.netlify.app/components/spinner/)
=> fix: native a11y support for Spinner and improve docs

www/src/components/insights/ProjectNameWithComponentUsageModal.jsx, www/src/components/insights/ProjectNameWithUsageModal.jsx, www/src/components/insights/SummaryComponentNameWithUsageModal.jsx, www/src/pages/insights.jsx, www/src/utils/getGithubProjectUrl.js
[PAR-394](https://openedx.atlassian.net/browse/PAR-394)
Provide links to specific code examples of usages of Paragon components.
**Demo:** https://deploy-preview-983--paragon-edx.netlify.app/insights
**Known bugs**
* Hyperlinks to monorepo packages (e.g., `catalog-search`) will lead to a 404 on Github since they are linking to the root of the repository instead of the relative package path.
* Some repositories don't have a repository url specified, so there are no hyperlinks for their code usages.
* `edx/frontend-app-ora-enhanced-staff-grader` as a Github repository doesn't exist (the actual repository name is different), so links to it will lead to a 404 on Github.
=> docs: link to github code example of component usages

src/Collapsible/CollapsibleTrigger.jsx, src/Nav/index.jsx, src/Overlay/index.jsx, src/SearchField/SearchFieldClearButton.jsx, src/SearchField/SearchFieldInput.jsx, src/SearchField/index.jsx, www/src/components/Menu.jsx
* Allow non-string `tag` prop on `CollapsibleTrigger` component
* Straight passthru of react-bootstrap nav components/subcomponents to maintain `forwardRef`
* Fixed the `trigger` prop types for `OverlayTrigger` component
* Place focus on text input after clicking clear button
* Ensure `disabled` prop is properly passed into `SearchFieldInput`
* Pass required `id` prop to `Tooltip` in docs site.
=> Miscellaneous fixes

src/DataTable/DataTable.scss, src/DataTable/DataViewToggle.jsx, src/DataTable/README.md, src/DataTable/TableControlBar.jsx, src/DataTable/index.jsx, src/DataTable/tests/DataViewToggle.test.jsx, src/IconButtonToggle/IconButtonToggle.scss
Use an IconButtonToggle as a controlled component, which allows switching between multiple views, CardView and Table, using a state variable as desired by the user
There is one known bug here I could not figure out at first try, where filters if used, are cleared when switching view. Since it does not block Explore Catalog usage I am moving forward with feedback from Alena, Mariana and Adam S. But I created https://openedx.atlassian.net/browse/PAR-615 to track and fix that bug
Usage is seen in the DataTable demo page: https://deploy-preview-988--paragon-openedx.netlify.app/components/datatable/#view-switching
Did not add screenshots here since the preview page int he 'Checks' section has a live preview!
=> feat: add dataViewToggle within DataTable PAR-577

src/DataTable/DataTable.scss
Font size equals to `$font-size-sm` for all elements in the table.
JIRA: [PAR-609](https://openedx.atlassian.net/browse/PAR-609)
=> [BD-46] feat: update DataTable font size to be small

src/DataTable/CollapsibleButtonGroup.jsx, src/DataTable/tests/BulkActions.test.jsx, src/DataTable/tests/TableActions.test.jsx, src/IconButton/index.jsx
Resolves erroneous errors in the test suite(s) of at least one consuming repository. No longer passes through `attrs` to `IconComponent` in the `IconButton` component. This change prevents the error previously seen where props were unintentionally being added in 2 places, causing failures with test selectors (e.g., `wrapper.find(...)` was returning more nodes than the expected 1).
=> fix: no longer pass extra attrs to `IconComponent` in `IconButton`

src/DataTable/ExpandRow.jsx, src/IconButton/IconButton.test.jsx, src/IconButtonToggle/IconButtonToggle.test.jsx
* Simulate clicks to trigger `onClick` callback instead of calling the callback directly in tests.
* Fix a couple prop type warnings in tests
* Reduces size of `IconButton` in `ExpandRow` within `DataTable` to be inline
=> fix: test updates to reduce prop type warnings and reduces size of expand/collapse IconButton in DataTable

build-scss.js, package-lock.json, package.json, www/gatsby-node.js, www/package-lock.json, www/package.json
- Replaced deprecated LibSass (node-sass) package with Dart Sass (sass)
JIRA: https://openedx.atlassian.net/browse/PAR-629
=> [BD-46] feat: replace libsass with dart sass

src/Stepper/README.md, src/Stepper/StepperContext.jsx, src/Stepper/StepperStep.jsx, src/Stepper/tests/Stepper.test.jsx
- https://github.com/openedx/frontend-wg/issues/51
- https://openedx.atlassian.net/browse/PAR-638
Fixes a bug where steps would be rerendered at the end of the list upon state change, regardless of original position.
This solution adds an `index` prop to `StepperStep` which, when used, allows the steps to be sorted by `index` in the header when state is updated. This is required to avoid the aforementioned bug when using error states or conditionally rendering steps.
Also adds demo for the `hasError` prop on `StepperStep`:
https://user-images.githubusercontent.com/10442143/150027282-b11a84fb-ab51-4eda-9cea-8098530a76ab.mov
=> fix: Stepper errorState bug fix + documentation

src/DataTable/BulkActions.jsx, src/DataTable/CollapsibleButtonGroup.jsx, src/DataTable/DataTable.scss, src/DataTable/README.md, src/DataTable/TableActions.jsx, src/DataTable/tests/ActionDisplay.test.jsx, src/DataTable/tests/BulkActions.test.jsx, src/DataTable/tests/TableActions.test.jsx
Modifications to the `BulkActions` and `TableActions` as they are based on the same `CollapsibleButtonGroup`:
- `DataTable` accepts functional components for the `bulkActions` and `tableActions` props instead of objects
- The idea is to pass `as || anyComponent` to the `React.creatElement` so the `CollapsibleButtonGroup` can manage toggled and not toggled display of the buttons by itself
JIRA: [PAR-273](https://openedx.atlassian.net/browse/PAR-273)
=> [BD-46] feat: Make BulkAction buttons more configurable

www/src/context/SettingsContext.jsx
store theme choice in localStorage so theme does not get reset after page refresh
=> [BD-46] feat: use localStorage to persist theme choice on docs site

src/Card/Card.scss
fix max-width style for ImageCap which caused images to overflow other content
example:
=> [BD-46] fix: update styles for ImageCap component

www/gatsby-browser.js, www/gatsby-ssr.js, www/src/components/MeasuredItem.jsx, www/src/context/SettingsContext.jsx, www/src/pages/foundations/colors.jsx
Currently, the [color foundations page](https://paragon-openedx.netlify.app/foundations/colors/) does not update its hex color values upon theme change. This PR addresses this issue by:
* Adding openedx theme stylesheet to HTML `<head>` at build time instead of runtime via `gatsby-ssr.js`. This prevents a flash of unstyled content when developing locally.
* Refactored `MeasuredItem` class component to use functional hooks.
* Recalculate measurements when the `theme` from `SettingsContext` changes, with an increased timeout to allow for enough time to load new styles in the DOM.
* Ensures we hide the hex value until its measurements are re-calculated upon page load or theme change.
**Deploy preview**
https://deploy-preview-1066--paragon-openedx.netlify.app/foundations/colors/
=> docs: recalculate MeasuredItem measurements on theme change

src/Hyperlink/Hyperlink.scss, src/Hyperlink/Hyperlink.test.jsx, src/Hyperlink/index.jsx, src/index.scss
See the following Lighthouse a11y error regarding `Hyperlink` with external URLs:
This PR fixes the a11y error by removing `aria-label` from the `span` and instead simply passing its contents to the `screenReaderText` prop of `Icon` instead which has the same result.
=> fix: remove aria-label from span and move alt text to icon

src/IconButtonToggle/IconButtonToggle.test.jsx, src/IconButtonToggle/index.jsx
Update `IconButtonToggle` children to use `aria-selected=true|false` based on the current `activeValue`.
- https://github.com/openedx/frontend-wg/issues/50
- https://openedx.atlassian.net/browse/PAR-633
=> [PAR-633] Add aria-selected to IconButtonToggle children

src/Toast/_Toast.scss
On mobile screen the text is not wrapping correctly. 
|Before|After|
|-------|-----|
Ticket: https://openedx.atlassian.net/browse/VAN-847
=> fix: text wrapping issue for Toast

src/Pagination/index.jsx, www/src/pages/404.jsx, www/src/pages/foundations/colors.jsx, www/src/pages/foundations/spacing.jsx, www/src/pages/foundations/typography.jsx, www/src/pages/insights.jsx, www/src/pages/status.jsx, www/src/templates/component-page-template.jsx, www/src/templates/default-mdx-page-template.jsx
While upgrading Paragon, it was observed there's a prop type warning when using `DataTable`'s pagination, where `alt` prop is not passed to the `IconButton` components. This PR ensures we pass `alt` prop to `IconButton` components in `Pagination`.
It also disables an eslint rule when using the `SEO` component due to the component name.
=> fix: address Pagination prop type warning and resolve eslint errors in `www`

src/Nav/index.jsx
The issues with a11y were caused by incorrectly overriding `Nav`'s `defaultProps` from `react-bootstrap` (this component is used under the hood by `Tab` component).
JIRA: [PAR-665](https://openedx.atlassian.net/browse/PAR-665), [PAR-666](https://openedx.atlassian.net/browse/PAR-666)
=> [BD-46] Fix Tabs and Nav a11y issues

src/ProductTour/Checkpoint.jsx, src/ProductTour/Checkpoint.test.jsx, src/ProductTour/CheckpointActionRow.jsx, src/ProductTour/index.jsx
The `showDismissButton` prop in ProductTour checkpoints enforces visibility of the dismiss button under all circumstances. This change is required for [ENT-5184](https://openedx.atlassian.net/browse/ENT-5184).
=> Adds showDismissButton prop to ProductTour checkpoints

package.json
According to [Bundlephobia](https://bundlephobia.com/package/@edx/paragon@19.10.1) Paragon does not support tree-shaking, even though local tests say otherwise. One possible reason is that package.json has no `module` entry, as can be seen from these two issues ([first](https://github.com/pastelsky/bundlephobia/issues/377), [second](https://github.com/pastelsky/bundlephobia/issues/457)).
By adding `module` entry we might be able to help services such as Bundlephobia to detect tree-shakability more easily.
JIRA: [PAR-746](https://openedx.atlassian.net/browse/PAR-746)
=> [BD-46] Improve tree-shaking detectability

src/ProgressBar/ProgressBar.scss, src/ProgressBar/README.md, src/ProgressBar/_variables.scss, src/ProgressBar/index.jsx, src/ProgressBar/tests/ProgressBar.test.jsx, src/ProgressBar/tests/__snapshots__/ProgressBar.test.jsx.snap, src/ProgressBar/tests/utils.test.js, src/ProgressBar/utils.js
Added `ProgressBar.Annotated` component:
- component styling
- `threshold` interaction with the `current progress`
- new properties for `threshold`
- offset calculations for the annotation
- determine whether the hint is displayed before or after the annotation
JIRA: [PAR-462](https://openedx.atlassian.net/browse/PAR-462)
=> [BD-46] feat: annotated progress bar

www/src/pages/foundations/spacing.jsx
New table with `spacers` according to their pixel values
- `MeasuredItem` is used to measure margin of hidden block
- used DataTable to display the values
JIRA: [PAR-765](https://openedx.atlassian.net/browse/PAR-765)
=> [BD-46] feat: display spacing in pixels

.github/workflows/ci.yml
This will prevent the workflow from running on commits merged to master, where running the CI workflow is irrelevant because it is already being released via the Release github action workflow.
n/a
n/a
=> build: only run the CI github action workflow on pull_request triggers

scss/core/_variables.scss, src/Alert/Alert.scss
This is a new SCSS mixin, which gives consumers the ability to add elevation (i.e., elevation) based on the pre-defined elevation levels in addition to a direction/side (e.g., top, right, centered).
n/a (SCSS change only. There probably should be an `Elevation` foundations page in the documentation website. Taking an action item to file this ticket).
=> fix: rename box-shadow-control SCSS mixin to pgn-box-shadow

src/Form/_mixins.scss
Fixes an issue with `latest` Paragon, post `bootstrap@latest-4` upgrade to fix the `calc` deprecation warnings, that is causing issues with consuming MFEs.
n/a
=> fix: SCSS bug with calc

src/Modal/_ModalDialog.scss, www/src/components/Settings.jsx, www/src/config.js, www/src/pages/index.jsx
Use of `math.div` appears to be causing issues for at least one consumer. This fix replaces `math.div` with an equivalent `calc`. Note because of the negative values, we are multiplying the value by -1 to force it to be negative.
n/a
n/a
=> fix: no longer use math.div

src/Stack/README.md, src/Stack/Stack.scss
Fix auto stretching for the `Stack` component in the vertical mode
JIRA: [PAR-760](https://openedx.atlassian.net/browse/PAR-760)
=> [BD-46] fix: prevent stretching in Stack

docs/decisions/0017-runtime-a11y-validation.rst
Adds ADR for using `@axe-core/react` for automated a11y testing during development
n/a
n/a
=> Adds ADR for using `@axe-core/react` for automated a11y testing during development

src/Toast/index.jsx
The issue is related to https://openedx.atlassian.net/browse/VAN-906 where two toasts are appearing (one for the component that renders when desktop view is on and other for Mobile view)
The classes added to parent components in prospectus that dynamically show and hide the content `d-block d-md-none` and `d-none d-md-block` don't work on any children Toast elements. Adding a `div` with these classes around `Toast` also doesn't work. 
Solution:
Added a span around `BaseToast` which takes className as props. This doesn't change the appearance of Toast. 
=> feat: Add className prop to Toast

src/DataTable/index.jsx
`columns` prop types update:
- added `Cell`
- `accessor` is required when not `Cell`
- along with that I found 3 more filters fields that can be passed. I defined them and added description
JIRA: [PAR-699](https://openedx.atlassian.net/browse/PAR-699)
=> [BD-46] fix: accessor requirements update

src/Dropdown/Dropdown.test.jsx, src/Dropdown/README.md, src/Dropdown/index.jsx
* Possibly look into using `uncontrollable` NPM package here.
=> Asheehan edx/dropdown autoclose fork

package-lock.json, src/Card/Card.scss
* Increases spacing for `Card.Header` content
* Adds white background color to logo image cap
* Adds padding to match Figma spec to logo image cap
https://deploy-preview-1229--paragon-openedx.netlify.app/components/card/#with-image-cap
=> fix: add background-color and fix spacing for Card.ImageCap and Card.Header

package-lock.json, package.json, src/Tabs/index.jsx
=> fix: use React.cloneElement vs. React.createElement to prevent extra re-rendering and remove "key" warning.

src/Sheet/README.md, src/Sheet/Sheet.test.jsx, src/Sheet/__snapshots__/Sheet.test.jsx.snap, src/Sheet/index.jsx
Add processing of `Escape` press and backdrop click
- on `Escape` sheet is closed. New requirement - pass new `onClose` prop that will be called on `Escape`.
- on backdrop click. The same requirement as for `Escape`
- along with this task also [PAR-783](https://openedx.atlassian.net/browse/PAR-783) is completed. Backdrop click on the button that toggles `Sheet` has led to 2 actions at the same time - close on the backdrop event and open again on the button click. Changing `<FocusOn enabled={this.props.blocking} />` to `<FocusOn />` from `react-focus-on` always put focus inside the `Sheet` so that backdrop click can't trigger any event from outside of the `Sheet`.
- added tests for new functionality
JIRA: [PAR-784](https://openedx.atlassian.net/browse/PAR-784), …
=> [BD-46] feat: escape press, backdrop click for Sheet

src/DataTable/DataTable.scss, src/DataTable/index.jsx
- added `disableElevation` props,
- added hide box-shadow style.
JIRA: [PAR-781](https://openedx.atlassian.net/browse/PAR-781)
=> [BD-46] feat: added box-shadow toggle props

scss/core/_typography.scss, scss/core/_variables.scss
Increase display headings to 52px font size / 56px line height for mobile, so that they no longer lose hierarchy next to mobile H1.
Related ticket with more context: https://openedx.atlassian.net/browse/WS-2763
https://deploy-preview-1251--paragon-openedx.netlify.app/foundations/typography
=> fix: update display heading mobile sizes

www/gatsby-browser.js, www/src/templates/default-mdx-page-template.jsx
Fixes how anchor links are displayed when using default mdx page and updates scroll behaviour to those headings to include sticky header size
See [Installation and Usage page](https://deploy-preview-1274--paragon-openedx.netlify.app/guides/installation-and-usage/) for example, and its [version](https://paragon-openedx.netlify.app/guides/installation-and-usage) before this PR
=> [BD-46] docs: fix links to sections in default mdx page template

www/gatsby-config.js, www/gatsby-node.js, www/src/config.js, www/src/pages/insights.jsx
Insights routing update:
- tabs on the `insights` pages is linked with corresponding routes
- used search params for route changing
- added support for back button behavior
JIRA: [PAR-724](https://openedx.atlassian.net/browse/PAR-724)
=> [BD-46] feat: add insights tabs routing

package-lock.json, package.json, src/Collapsible/CollapsibleTrigger.jsx, src/DataTable/DataViewToggle.jsx, src/DataTable/index.jsx, src/DataTable/selection/ControlledSelect.jsx, src/DataTable/selection/ControlledSelectHeader.jsx, src/DataTable/selection/ControlledSelectionStatus.jsx, src/DataTable/utils/getVisibleColumns.jsx, src/Form/FormGroupContext.jsx, src/Form/fieldUtils.js, src/Menu/SelectMenu.jsx, src/ProductTour/Checkpoint.jsx, src/ProductTour/index.jsx, src/ProgressBar/index.jsx, src/SearchField/SearchFieldAdvanced.jsx, src/SelectableBox/index.jsx, src/Stepper/StepperStep.jsx, src/Sticky/index.jsx, src/hooks/useArrowKeyNavigation.js, src/hooks/useIsVisible.jsx
Most of hooks are updated due to ESLint rules and some are `eslint-disabled` because of big amount of refactor required. `ProductTour` component was refactored because of inefficient `useEffect` usage.
JIRA: https://openedx.atlassian.net/browse/PAR-804
[Preview](https://deploy-preview-1263--paragon-openedx.netlify.app/)
=> [BD-46] feat: eslint config upgrade, refactor

.stylelintrc.json, scss/core/_exports.module.scss, scss/core/_variables.scss, src/utils/breakpoints.js, www/gatsby-config.js, www/package-lock.json, www/package.json, www/src/components/Menu.jsx, www/src/pages/foundations/responsive.jsx
Implement single source of truth for breakpoints used in Paragon, this is the improved version of [reverted PR](https://github.com/openedx/paragon/pull/1242) that fixes issues with MFE's
JIRA: [PAR-813](https://openedx.atlassian.net/browse/PAR-813)
https://deploy-preview-1288--paragon-openedx.netlify.app/foundations/responsive
=> [BD-46] docs: add 'Responsive' page

src/Dropdown/Dropdown.scss
Fixes dropdown toggle icon that is cut off: 
**Before**
**After**
https://deploy-preview-1310--paragon-openedx.netlify.app/components/dropdown/
=> fix: add `border: 0` to dropdown toggle

src/Dropdown/Dropdown.scss, src/Tabs/README.md, src/Tabs/Tabs.scss, src/Tabs/Tabs.test.jsx, src/Tabs/__snapshots__/Tabs.test.jsx.snap, src/Tabs/index.jsx, src/hooks/tests/useIndexOfLastVisibleChild.test.jsx, src/hooks/useIndexOfLastVisibleChild.jsx, src/index.js
1. Added `useIndexOfLastVisibleChild` hook:
- got code from [code](https://github.com/openedx/frontend-app-learning/blob/907892e7bb1263d6b9b56d8acc7fe57abd34cbdd/src/generic/tabs/useIndexOfLastVisibleChild.js#L33) and modified
- added support for dynamic style changes on the site
- updated parameters for hook to be able to use it when it is not possible to pass ref straightly to the container element or to the overflow element
- added tests
2. Added code for the `Tabs` component to use new hook and support responsive
- `useMemo` for `children` to update them when hook returns different index
- click on the dropdown item activates corresponding tab
- observer tracks tab change and update active state in the tab
- tab styles
- interactions with tabs using keyboard
JIRA: …
=> [BD-46] feat: useIndexOfLastVisibleChild, responsive tabs

src/Form/form-group.mdx
https://github.com/openedx/paragon/issues/1306
example is using isValid, yet the feedback text says “incorrect” (it should say “correct”)
https://deploy-preview-1315--paragon-openedx.netlify.app/components/form/form-group/
=> [BD-46] docs: Form.Group example fix

src/hooks/useWindowSize.jsx
=> fix: update `useWindowSize` for `useLayoutEffect` instead of ` useEffect`

src/Popover/README.md
Update `Popover`'s description with note about usage of interactive elements.
https://deploy-preview-1346--paragon-openedx.netlify.app/components/popover/
=> [BD-46] docs: add a11y note to `Popover` description

src/hooks/useIndexOfLastVisibleChild.mdx
the documentation site for useIndexOfLastVisibleChild and sample usage
https://github.com/openedx/paragon/issues/1304
https://deploy-preview-1345--paragon-openedx.netlify.app/components/hooks/useindexoflastvisiblechild/
=> [BD-46] docs: documentation for useIndexOfLastVisibleChild

www/src/components/Header.jsx, www/src/components/Seach.jsx
We just recently merged a PR to add search to the Paragon documentation website, via Algolia `DocSearch`. However, there seems to be an issue with the environment variables configured in Netlify where they are not getting picked up (they are coming back as `undefined`).
To prevent a temporarily broken search from being on production, this PR will hide `DocSearch` until there are valid Algolia environment variables coming through.
This will also prevent search from appearing on the PR deploy previews, where the environment variables configured in Netlify are not applied.
Also included in this PR, though, is an attempt to fix the environment variables. Because the docs site is using Gatsby, we may actually need to prefix the environment variables with `GATSBY_` …
=> docs: only render DocSearch when algolia keys are set

.gitignore, www/src/components/Seach.jsx
It seems the prefix of `GATSBY_` was indeed the fix, but we weren't seeing the `DocSearch` appear because the conditional was using the wrong variable name...
=> docs: fix process.env variable name for Algolia env var

src/Menu/README.md
Made the `ModalPopup` properly positioned again.
[Include a direct link to your changes in this PR's deploy preview here (e.g., a specific component page).](https://deploy-preview-1347--paragon-openedx.netlify.app/components/menu/)
=> docs: fix modalpopup positioning in menu

www/src/components/Header.jsx, www/src/components/LinkedHeading.scss
Fixing the Header menu in RTL format
[Home page](https://deploy-preview-1359--paragon-openedx.netlify.app)
=> [BD-46] docs: fixing the Header menu in RTL format

www/src/components/Menu.scss
Fixing the number of columns in the All Components menu in the footer of the site on the mobile version.
- [Home page](https://deploy-preview-1333--paragon-openedx.netlify.app/)
=> [BD-46] docs: fixing the number of columns in the All Components menu

src/Breadcrumb/Breadcrumb.scss, src/Breadcrumb/README.md
Fixed display of the list of links in the Breadcrumb component on mobile devices.
[Breadcrumbs component](https://deploy-preview-1358--paragon-openedx.netlify.app/components/breadcrumb/)
=> [BD-46] feat: refactoring mobile view Breadcrumbs component

src/Button/README.md
Fixed margin buttons on the mobile version of the site.
- [Button component](https://deploy-preview-1334--paragon-openedx.netlify.app/components/button/)
=> [BD-46] docs: fixed margin buttons

src/IconButton/README.md
Fixed icon button on the mobile version of the site.
- [Icon button](https://deploy-preview-1336--paragon-openedx.netlify.app/components/iconbutton/)
=> [BD-46] fix: fixed Icon button component

src/Sheet/README.md
Fixed Sheet button gaps on the mobile version of the site.
- [Sheet component](https://deploy-preview-1335--paragon-openedx.netlify.app/components/sheet/)
=> [BD-46] fix: fixed Sheet button gaps

package-lock.json, package.json, src/DataTable/index.jsx, src/ListBox/index.jsx, src/Modal/AlertModal.jsx, src/Modal/MarketingModal.jsx, src/Pagination/index.jsx, src/utils/propTypes/greaterThan.js, src/utils/propTypes/index.js, src/utils/propTypes/nonNegativeInteger.js, src/utils/propTypes/utils.js, www/package-lock.json, www/package.json, www/src/components/PropsTable.jsx
Remove `airbnb-prop-types` dependency as it does not support React 17 (see [this issue](https://github.com/airbnb/prop-types/issues/73)), which caused build issues after node upgrade. 
We only used 2 prop types from that package anyway, so it should't be a big change.
=> [BD-46] chore: remove airbnb-prop-types dependency and upgrade eslint in docs project

src/Popover/Popover.test.jsx, src/ProgressBar/ProgressBar.scss, src/ProgressBar/index.jsx, src/ProgressBar/tests/__snapshots__/ProgressBar.test.jsx.snap, src/setupTest.js
=> fix: remove prop type warning and use only CSS for threshold dot

src/Card/Card.scss
Added a new box-shadow for the Card component.
[Figma](https://www.figma.com/file/eGmDp94FlqEr4iSqy1Uc1K/Paragon-Design-System?node-id=3460%3A286)
[Card component](https://deploy-preview-1364--paragon-openedx.netlify.app/components/card/)
=> [BD-46] feat: added a new box-shadow for the Card component

src/Breadcrumb/Breadcrumb.scss, src/Breadcrumb/_variables.scss, src/Chip/Chip.scss, src/Chip/_variables.scss, src/Form/_Form.scss, src/Form/_variables.scss, src/Pagination/Pagination.scss, src/Pagination/_variables.scss, src/SearchField/SearchField.scss, src/SearchField/_variables.scss
Added focus state for:
- Breadcrumbs, 
- Chip, 
- Dropdown, 
- Form.Checkbox, 
- Form.Radio, 
- Pagination, 
- SearchField components.
[JIRA](https://openedx.atlassian.net/browse/PAR-763)
[Figma](https://www.figma.com/file/eGmDp94FlqEr4iSqy1Uc1K/Paragon-Design-System?node-id=14061%3A5)
=> [BD-46] docs: added focus state in components

src/SelectableBox/README.md, src/SelectableBox/SelectableBoxSet.jsx
Fixed SelectableBox responsiveness.
[SelectableBox component](https://deploy-preview-1362--paragon-openedx.netlify.app/components/selectablebox/)
=> [BD-46] feat: fixed SelectableBox responsiveness

src/Modal/Modal.scss, src/Modal/ModalPopup.jsx, src/Modal/ModalPopup.test.jsx, src/Modal/PopperElement.jsx, src/Modal/modal-popup.mdx
Added caret for ModalPopup component.
[Modal popup component](https://deploy-preview-1363--paragon-openedx.netlify.app/components/modal/modal-popup/)
=> feat: [BD-46] adding caret for ModalPopup component

src/DataTable/DataTable.scss, src/DataTable/TableHeaderCell.jsx
* Flips the sort direction arrow for descending vs. ascending to be more in line with convention.
* Adds white background color behind the sidebar filters and table wrapper containers.
https://deploy-preview-1404--paragon-openedx.netlify.app/components/datatable/#frontend-filtering-and-sorting
=> fix: flip sort direction icons in TableHeaderCell and add white bg color

package-lock.json, package.json
Removes custom browserslist configuration in favor of using a [shared configuration](https://github.com/edx/browserslist-config).
This change reduces the resultant asset bundle size.
Created this PR due to some issues in rebasing the [older PR](https://github.com/openedx/paragon/pull/868)
=> build: use shared browserslist config

.stylelintrc.json, scss/core/_variables.scss, src/Alert/_variables.scss, src/Annotation/_variables.scss, src/Button/_variables.scss, src/Form/_variables.scss, src/Modal/Modal.scss, src/Popover/_variables.scss, src/ProductTour/Checkpoint.scss, src/Scrollable/Scrollable.scss, src/Sheet/Sheet.scss, src/Sticky/_variables.scss, src/Toast/_variables.scss, src/Tooltip/_variables.scss, www/src/components/Search.scss, www/src/components/_doc-elements.scss
TLDR; Make distinction between rgb and rgba because `edx-platform` doesn't support it. Update `stylelint` to maintain it.
When use sass compile on `edx-platform`, some of the modern syntax isn't supported. For example, `rgb(0 0 0 / 50%)` need to be convert to `rgba(0, 0, 0, 0.5)`.   See [color-function-notation](https://stylelint.io/user-guide/rules/list/color-function-notation/]
=> style: update linting to support paver sass compile

src/Card/README.md
CardDeck component is deprecated 
Github issue: https://github.com/openedx/paragon/issues/1375
https://deploy-preview-1377--paragon-openedx.netlify.app/components/card/#carddeckdeprecated
=> [BD-46] docs: deprecate CardDeck

src/Card/Card.scss, src/Card/README.md
Refactoring the display of the Card component page for mobile devices.
[Card component](https://deploy-preview-1381--paragon-openedx.netlify.app/components/card/)
=> [BD-46] docs: refactoring Card component on the mobile page styles #1314

src/DataTable/filters/TextFilter.jsx, src/DataTable/filters/tests/TextFilter.test.jsx
Allow function and components to passed as `Header` value to `TextFilter`.
https://deploy-preview-1441--paragon-openedx.netlify.app/components/datatable/
=> [BD-46] TextFilter component Header prop usage only handles string, not components (functions) 

src/Form/form-control.mdx
Each input type should have its own label.
https://paragon-openedx.netlify.app/components/form/form-control/#input-types
Labels in order from top to bottom:
- Default
- Textarea
- Select
- Password
- Date picker
- Number
- Time picker
GitHub issue: https://github.com/openedx/paragon/issues/1433
https://deploy-preview-1447--paragon-openedx.netlify.app/components/form/form-control/
=> [BD-46]: Add headers to form input components on docs site

src/Bubble/Bubble.scss, src/Bubble/Bubble.test.jsx, src/Bubble/README.md, src/Bubble/_variables.scss, src/Bubble/index.jsx, src/Tabs/__snapshots__/Tabs.test.jsx.snap, src/Tabs/index.jsx
- add `expandable` prop to `Bubble`
- add `scss` variables to control padding with `expandable={true}`
=> [BD-46] feat: add expandable bubble

src/Tabs/__snapshots__/Tabs.test.jsx.snap, src/Tabs/index.jsx
Added role="status" to Badge in notification in Tabs component.
[Tabs component](https://deploy-preview-1477--paragon-openedx.netlify.app/components/tabs/)
=> [BD-46] docs: added role for Bubble notification

scss/core/_variables.scss, www/src/pages/foundations/elevation.jsx
There are CSS utility classes and a SCSS mixin to implement shadows in all levels and directions, however, the SCSS variables only account for the level.
This PR ensure there are SCSS variables for each permutation of level and heading.
Github issue: https://github.com/openedx/paragon/issues/1385
https://deploy-preview-1443--paragon-openedx.netlify.app/foundations/elevation
=> [BD-46]: vars for elevation

src/DataTable/DataTable.scss
Fix incorrect display of tables in the DataTable component on the mobile version of the site.
- [DataTable](https://deploy-preview-1332--paragon-openedx.netlify.app/components/datatable/)
=> [BD-46] docs: fix incorrect display of tables in the DataTable component

src/Dropzone/DefaultContent.jsx, src/Dropzone/Dropzone.scss, src/Dropzone/README.md, src/Dropzone/_variables.scss, src/Dropzone/index.jsx, src/Dropzone/messages.js, src/Dropzone/tests/DefaultContent.test.jsx, src/Dropzone/tests/__snapshots__/Dropzone.test.jsx.snap
Auto-generate message about file restrictions in `Dropzone` component based on `accept`, `minSize` and `maxSize` props.
https://deploy-preview-1470--paragon-openedx.netlify.app/components/dropzone/
=> [BD-46] feat: add message about file restrictions to default state of `Dropzone`

src/Card/Card.scss, src/Card/README.md, src/Card/index.jsx
is-mutted props for Card component were added 
Github issue: https://github.com/openedx/paragon/issues/1376
https://deploy-preview-1455--paragon-openedx.netlify.app/components/card/
=> [BD-46] is-mutted props for card

src/DataTable/DataTable.scss
=> fix: filter break style is not align correctly

src/Collapsible/Collapsible.scss, src/Collapsible/Collapsible.test.jsx, src/Collapsible/CollapsibleAdvanced.jsx, src/Collapsible/CollapsibleBody.jsx, src/Collapsible/index.jsx, www/src/components/CodeBlock.jsx
Added `unmountOnExit` that uses Collapse inside if it is equal to false. React Bootstrap by default implements `unmountOnExit=false`. `TransitionReplace` is based on the children re-render so I decided to use `Collapse` instead of updating `TransitionReplace`
[Collapsible](https://deploy-preview-1502--paragon-openedx.netlify.app/components/collapsible/)
=> [BD-46] feat: add unmountOnExit

src/DataTable/README.md
Add section and example for Cell property.
https://github.com/openedx/paragon/issues/1524
[DataTable](https://deploy-preview-1538--paragon-openedx.netlify.app/components/datatable/#custom-cell-content)
=> [BD-46] feat: new docs for Cell prop

src/Modal/_ModalDialog.scss
The Modal scss was missing interpolation for calculated styles.
=> fix: correct missing interpolation

www/src/components/Search/Search.scss
After configuring sections for Algolia search markup issues were found
=> [BD-46] docs: fixing category margin gap

src/Modal/_ModalDialog.scss, src/Modal/_variables.scss
Modals have scroll bars when there isn't a need for a scroll bar.
[Marketing modal](https://deploy-preview-1594--paragon-openedx.netlify.app/components/modal/marketing-modal)
=> [BD-46] feat: fixed Marketing modal scroll

src/Tabs/index.jsx
Add `console.error` when non-`Tab` component is passed in `Tabs`
https://deploy-preview-1604--paragon-openedx.netlify.app/components/tabs/
=> [BD-46] fix: handle non-Tab component

src/Chip/_variables.scss
Increase left and right paddings for label.
https://deploy-preview-1606--paragon-openedx.netlify.app/components/chip/
=> [BD-46] fix: update styles for Chip

src/Form/_Form.scss
Fix expanding of floating label in the `Form.Control`.
https://deploy-preview-1605--paragon-openedx.netlify.app/components/form/form-control/
=> [BD-46] fix: floating label expand beyond input field

src/Modal/Modal.scss, src/Modal/ModalLayer.jsx
Due to some reason `react-remove-scroll-bar` library (child of `react-focus-on`) adds `padding-right` on modal open that equals to the scroll bar width. But there is already `margin-right` that also equals the same value. As result the library adds 2x scrollbar width to the `body` that creates width jumping and unwanted behavior.
As fix I provided `className` that is added to the `body` on modal open and sets `padding-right` to `0px`.
https://deploy-preview-1644--paragon-openedx.netlify.app/components/modal/marketing-modal/
=> [BD-46] fix: remove body width jumping on open

package-lock.json, src/Annotation/README.md, src/Card/README.md, src/Collapsible/README.md, www/src/components/PropsTable.tsx, www/src/components/Toc.tsx, www/src/components/exampleComponents/ExamplePropsForm.scss
- Add `ExamplePropsForm` for `Annotation`, `Card`, `Collapsible`
- Fix Table of Content
- Fix Props table text message padding
=> [BD-46] docs: docs improvements

src/Truncate/README.md, src/Truncate/Truncate.test.js, src/Truncate/index.jsx, src/Truncate/utils.js
Add processing not only plain text but also inner tags
https://deploy-preview-1642--paragon-openedx.netlify.app/components/truncate/
=> [BD-46] feat: truncate v2 supports inner tags

src/Annotation/README.md
- in the [example](https://paragon-openedx.netlify.app/components/annotation/#referring-to-other-elements) on the docs site the contents of Annotation should change depending on the `arrowPlacement` prop.
Github issue - https://github.com/openedx/paragon/issues/1667
[Annotation component page](https://deploy-preview-1681--paragon-openedx.netlify.app/components/annotation/)
=> [BD-46] feat: Resolved annotation placement message

src/Card/CardImageCap.jsx, src/Card/README.md, src/Card/tests/CardImageCap.test.jsx, src/Card/tests/__snapshots__/CardGrid.test.jsx.snap, src/Card/tests/__snapshots__/CardImageCap.test.jsx.snap, src/Form/tests/FormGroup.test.jsx, src/Modal/ModalLayer.test.jsx, src/Modal/ModalPopup.test.jsx, src/Modal/tests/ModalDialog.test.jsx, src/Sheet/Sheet.test.jsx, src/utils/propTypes/greaterThan.js, www/src/components/exampleComponents/ExamplePropsForm.jsx
- add `fallbackSrc` prop to the `Card.ImageCap` component, use this `url` for image if image from the src prop does not load;
- add `fallbackLogoSrc` prop to Card.ImageCap component, use this `url` for logo if image from the `logoSrc` prop does not load;
- add tests for these changes and examples on the component's page;
- fixed key error in `ExamplePropsForm.jsx`.
[Cards component](https://deploy-preview-1682--paragon-openedx.netlify.app/components/card/#with-fallback-image)
=> [BD-46] feat: Added fallback props to Card component

src/Card/README.md
Small cleanup to force the fallback image src `Card` example to use the fallback src instead of the default image src by providing invalid image URLs.
=> docs: update fallback image src example for Card component

src/PageBanner/PageBanner.scss, src/PageBanner/PageBanner.test.jsx, src/PageBanner/README.md, src/PageBanner/index.jsx
Feature Ticket: https://2u-internal.atlassian.net/browse/INF-599
Figma designs supporting required change: https://www.figma.com/file/LVFnO9oRHYiamoicZuXDAC/Discussions?node-id=6884%3A261359
Page banners do not accept background color classes hence we need to add a new variant that can help achieve a design requirement in discussion MFE. 
- accentB color background is added with variant name accentB.
- documentation is updated to state available variants
- test cases added to ensure the required color class is added in the background.
=> feat: added accentB background for page banner

src/Button/Button.test.jsx, src/Button/README.md, src/Button/__snapshots__/Button.test.jsx.snap
- add unit test to Button
- add example for disable Button 
=> chore: add test and example for button

src/Layout/Layout.test.jsx, src/Layout/README.md, src/Layout/index.jsx, src/index.js
Add `Layout` component that is wrapper for `Row` and `Col` from `react-bootstrap`. It provides interface to pass all breakpoints data to the `Layout` instead of to each component separately.
https://deploy-preview-1659--paragon-openedx.netlify.app/components/layout/
=> [BD-46] feat: add Layout component

example/babel.config.js, example/package-lock.json, example/package.json, example/webpack.dev.config.js
Remove TypeScript dependencies from example app, instead update `frontend-build` to version that supports TypeScript.
=> [BD-46] chore: remove TypeScript dependencies from example app

src/Form/FormAutosuggest.jsx, src/Form/messages.js, src/Form/tests/FormAutosuggest.test.jsx, src/i18n/messages/ar.json, src/i18n/messages/ca.json, src/i18n/messages/es_419.json, src/i18n/messages/fr.json, src/i18n/messages/he.json, src/i18n/messages/id.json, src/i18n/messages/ko_KR.json, src/i18n/messages/pl.json, src/i18n/messages/pt_BR.json, src/i18n/messages/ru.json, src/i18n/messages/th.json, src/i18n/messages/uk.json, src/i18n/messages/zh_CN.json
Paragon supports i18n, we should ensure all default English strings in the Form autosuggest component are marked for translation with react-intl.
[FormAutosuggest component](https://deploy-preview-1711--paragon-openedx.netlify.app/components/form/form-autosuggest/)
=> [BD-46] feat: added translations English strings in FormAutosuggest component

www/src/utils/getParagonComponentsTypes.js
Hooks are displayed in the production mode. `component?.name` always give undefined in production mode and replaced by `componentName`
https://deploy-preview-1715--paragon-openedx.netlify.app/insights
=> [BD-46] fix: move hooks to utils in the usage insights

src/Dropdown/index.jsx
- verify onToggle is called both on open and on close, with the appropriate function arguments (e.g., isOpen should be false is the dropdown was just closed);
- ensure onToggle is part of the props API on the documentation website.
[Dropdown component](https://deploy-preview-1719--paragon-openedx.netlify.app/components/dropdown/)
=> [BD-46] fix: fixed onToggle prop

src/Modal/_ModalDialog.scss, src/Modal/_variables.scss
- update the FullscreenModal component to have proper alignment in its header component;
- check other Modal components and verify they don't have the same issue.
[FullscreenModal component](https://deploy-preview-1733--paragon-openedx.netlify.app/components/modal/fullscreen-modal/)
[StandartModal component](https://deploy-preview-1733--paragon-openedx.netlify.app/components/modal/standard-modal/)
[ModalDialog component](https://deploy-preview-1733--paragon-openedx.netlify.app/components/modal/modal-dialog/)
=> [BD-46] fix: fixed close button in the Modal components

.github/workflows/analyze-dependents.yml, dependent-usage-analyzer/checkout-dependents.sh
Adds 2 newer MFEs to the "Usage Insights" analyzer (https://paragon-openedx.netlify.app/insights)
* `edx/frontend-app-communications`
* `edx/frontend-app-learner-dashboard`
After this PR merges, I plan to kick off the `dependent-usage-analyzer` Github Action workflow to re-generate the `dependent-usage.json` file to include any `@edx/paragon` imports from these repos.
=> docs: add additional dependents for Usage Insights

src/Card/README.md
On the Paragon documentation site in the [Card component](https://paragon-openedx.netlify.app/components/card/), fix the display of the skeleton on the horizontal version of the card.
[Card component](https://deploy-preview-1746--paragon-openedx.netlify.app/components/card/#with-loading-state)
=> [BD-46] fix: fixed skeletonHeight in Card component

src/Form/form-radio.mdx
On the Paragon documentation site in the Form.Radio component, fix the display of the [Radio standalone usage example](https://paragon-openedx.netlify.app/components/form/form-radio/#radio-standalone-usage).
[Form.Radio component](https://deploy-preview-1745--paragon-openedx.netlify.app/components/form/form-radio/#radio-standalone-usage)
=> [BD-46] fix: fixed Radio standalone example usage

www/src/components/Toc.scss, www/src/components/Toc.tsx
Table of content items are highlighted while user scrolls the page. Values inside `IntersectionObserver` was chosen by testing user experience. Clicking on anchors or table of content items can be not caught by observer because of component remount. Gatsby router thinks that it is like page reloading.
=> [BD-46] docs: highlight table of content elements while scrolling

www/src/components/PropType.tsx
Currently `PropsTable` adds `required` badge for every prop of the component, even if it is actually not required, see [Card](https://paragon-openedx.netlify.app/components/card/) for example
linking `Card` as an eamaple but it affects all components https://deploy-preview-1721--paragon-openedx.netlify.app/components/card/
=> [BD-46] docs: fix propstable always displaying 'required' badge

src/Tabs/index.jsx
Details: https://github.com/openedx/paragon/issues/1790
For non-tab component failures, added a check to conditionally throw the `console.error` for development environment only. 
https://deploy-preview-1792--paragon-openedx.netlify.app/components/tabs/
=> fix: throw non-tab component error for development env

src/DataTable/README.md, src/DataTable/SmartStatus.jsx, src/DataTable/index.jsx, src/DataTable/selection/BaseSelectionStatus.jsx, src/DataTable/selection/ControlledSelectionStatus.jsx, src/DataTable/selection/SelectionStatus.jsx, src/DataTable/selection/data/helpers.js, src/DataTable/selection/tests/ControlledSelectionStatus.test.jsx, src/DataTable/selection/tests/SelectionStatus.test.jsx, src/DataTable/tests/DataTable.test.jsx, src/DataTable/tests/SmartStatus.test.jsx
Currently, the `SmartStatus` component shows the `SelectionStatus` component based on `selectedFlatRows`. However, `selectedFlatRows` is only populated if/when the selected row is on the current page. It does _not_ support selections on other pages.
As such, the `SelectionStatus` component is hidden until a row is explicitly selected on page 2, even though there might be a row selection on page 1.
This PR changes the `SmartStatus` to determine selection count based on `selectedRowIds` from the table instance state rather than `selectedFlatRows`. It also updates the default `SelectionStatus` messaging to support selections across pages where data on other pages might not be known to the client yet.
https://deploy-preview-1815--paragon-openedx.netlify.app/components/datatable/
=> fix: ensure SmartStatus renders SelectionStatus based on selectedRowIds

www/src/components/ComponentVariablesTable.tsx, www/src/templates/component-page-template.tsx
Changes theme variables section to be a `DataTable` with computed CSS variables
=> [BD-46] Display computed CSS variables on component's page

src/DataTable/index.jsx, src/DataTable/selection/BaseSelectionStatus.jsx, src/DataTable/selection/SelectionStatus.jsx
This PR extends functionality added in https://github.com/openedx/paragon/pull/1815 and considers `isFilterable` flag as well when rendering selection message, i.e. previously if `DataTable` wasn't paginated filtering could result in misleading selection message
this PR fixes it to be
https://deploy-preview-1832--paragon-openedx.netlify.app/components/datatable/#view-switching
=> [BD-46] fix: update SelectionStatus message based on applied filters

src/Form/fieldUtils.js
Fix `useHasValue` (hook that checks whether input component has a value) to consider 0 as a truthy value.
https://deploy-preview-1848--paragon-openedx.netlify.app/components/form/form-control/
=> [BD-46] fix: consider 0 a truthy value in input components

www/src/components/LayoutGenerator.tsx, www/src/pages/foundations/spacing.scss, www/src/pages/foundations/spacing.tsx
1. Input fields on [Grid section of Layout page](https://paragon-openedx.netlify.app/foundations/layout#grid) have incorrect spacing around them.
3. Similarly, radio buttons are not properly aligned with their labels in the margins section of [Spacing page](https://paragon-openedx.netlify.app/foundations/spacing)
[GitHub issue](https://github.com/openedx/paragon/issues/1802)
[Spacing page](https://deploy-preview-1806--paragon-openedx.netlify.app/foundations/spacing)
[Layout page](https://deploy-preview-1806--paragon-openedx.netlify.app/foundations/layout)
=> [BD-46] docs: fixed markup issues in Layout and Spacing pages

src/Bubble/index.tsx, src/hooks/useIndexOfLastVisibleChild.jsx, src/hooks/useIndexOfLastVisibleChild.mdx
Initially this PR aimed to fix `ResizeObserver` error that got reported in #1811, but turned out to be a good clean up opportunity for `useIndexOfLastVisibleChild` hook which resulted in removing `ResizeObserver` altogether, fixing the reported issue.
https://deploy-preview-1842--paragon-openedx.netlify.app/components/hooks/useindexoflastvisiblechild/
**Note**: `ResizeObserver loop limit exceeded` error is not logged to browser's console by default (it still gets caught by New Relic though). To actually check that this error is not reproduced anymore do the following:
1. Go to the deploy-preview link above
2. Open your browser's console
3. Run `addEventListener('error', (e) => console.error(e))`
4. Try to resize your window in multiple ways
Notice that nothing gets logged to your console. …
=> [BD-46] fix: remove ResizeObserver from useIndexOfLastVisibleChild hook

.eslintignore, .gitignore, package.json, tokens/build-tokens.js
Install dependencies in tokens module after installing Paragon
=> [BD-46] fix: install dependencies in tokens module after installing Paragon

src/Card/Card.scss, src/Card/README.md
Ensures `Card.Footer`'s `textElement` prop turns white automatically when `variant="dark"` on the top-level `Card` component.
TBD
=> fix: ensure card footer switches to white when card variant is dark

src/Card/Card.scss, src/Card/README.md
Noticed that when passing a `title`/`subtitle` as a string vs. the `Hyperlink` element, the color doesn't flip to white as expected when `Card`'s `variant="dark"`:
=> fix: ensure CardHeader title and subtitle turn white with dark variant

src/SelectableBox/README.md, src/SelectableBox/SelectableBox.scss, www/src/components/Settings.tsx
* Ensure `SelectableBox` has a white background. Otherwise, the background color underlying the element will be visible.
* Ensures the "Settings" sheet closes on escape or blur.
https://deploy-preview-1863--paragon-openedx.netlify.app/components/selectablebox
=> fix: ensure `SelectableBox` has white background

src/Card/Card.scss
Ensures the `Card.Header` subtitle text also gets changed to `$white` when `<Card variant="dark" />`.
https://deploy-preview-1865--paragon-openedx.netlify.app/components/card/#card-variants
=> fix: ensure CardHeader subtitle is also changed to white

src/Breadcrumb/Breadcrumb.scss, src/Breadcrumb/Breadcrumb.test.jsx, src/Breadcrumb/BreadcrumbLink.jsx, src/Breadcrumb/README.md, src/Breadcrumb/index.jsx, www/src/components/CodeBlock.tsx
Add ability render `Breadcrumbs` with custom element, e.g. using react-router's `Link` instead of simple `a` tag.
related issue: https://github.com/openedx/paragon/issues/1836
https://deploy-preview-1867--paragon-openedx.netlify.app/components/breadcrumb/#with-custom-link-element
=> [BD-46] feat: add ability to render Breadcrumbs with custom elements

src/Pagination/Pagination.test.jsx, src/Pagination/index.jsx
https://2u-internal.atlassian.net/browse/ENT-6567
Fixes issue with pagination where if pageCount === (0 || 1) , allows for infinite pagination. This fix would disable the pagination buttons if the pageCount <= 1.  
Takes into account all variants, including the default. 
Testing WIP
=> fix: Takes into account pagination pageCount <=1 page

src/Card/Card.scss, src/Card/CardDeck.jsx, src/Card/README.md, src/Card/_variables.scss, src/Card/index.jsx, src/Card/tests/CardDeck.test.jsx, src/Card/tests/CardGrid.test.jsx, src/Card/tests/__snapshots__/CardDeck.test.jsx.snap, src/Card/tests/__snapshots__/CardGrid.test.jsx.snap, www/src/components/exampleComponents/HipsterIpsum.tsx
Updates `CardDeck` to be more applicable to valid use cases for such a component. `CardGrid` is intended to be used to display a grid of `Card` components; however, we had a need for showing a single horizontal row of `Card` components, with similar column/gutter behavior as `CardGrid` with horizontal scrolling for any `Card` components that overflow the container.
Migrates the original `CardDeck` (pass-thru from react-bootstrap`) to `CardDeck.Deprecated` to keep it available for the one consumer of the original `CardDeck`.
https://deploy-preview-1866--paragon-openedx.netlify.app/components/card/#carddeck
=> feat: updated CardDeck

src/Card/CardCarousel/CardCarouselItems.jsx, src/Card/CardCarousel/CardCarouselProvider.jsx, src/Card/README.md, src/Chip/README.md, src/OverflowScroll/OverflowScroll.jsx, src/OverflowScroll/OverflowScroll.mdx, src/OverflowScroll/data/getOverflowElementScrollLeft.js, src/OverflowScroll/data/tests/useOverflowScroll.test.jsx, src/OverflowScroll/data/tests/useOverflowScrollActions.test.jsx, src/OverflowScroll/data/tests/useOverflowScrollElementAttributes.test.jsx, src/OverflowScroll/data/tests/useOverflowScrollEventListeners.test.jsx, src/OverflowScroll/data/useOverflowScroll.js, src/OverflowScroll/data/useOverflowScrollActions.js, src/OverflowScroll/data/useOverflowScrollElementAttributes.js, src/OverflowScroll/data/useOverflowScrollEventListeners.js, src/OverflowScroll/useOverflowScroll.mdx
* Switches to use callback refs with `useOverflowScroll` instead of `useRef` per the guidance of the following documentation:
* https://reactjs.org/docs/refs-and-the-dom.html#callback-refs
* https://stackoverflow.com/questions/64668211/how-to-listen-to-ref-object-changes
* Resolves a couple outstanding bugs
TBD
=> fix: use callback refs instead of `useRef` and fallback to offsetLeft: 0 when first child element ref no longer exists

icons/es5/FeedbackOutline.js, icons/es5/index.js, icons/jsx/FeedbackOutline.jsx, icons/svg/feedback_outline.svg
This PR adds the outline variant of the feedback icon. This icon is needed by TNL for their problem editor rewrite.
=> feat: add feedbackOutline icon

src/SelectableBox/README.md
Quick fix to the Selectable box aria labels so they are unique and set a good example for future implementations. 
=> fix: aria label fix for SelectableBox

src/Form/README.md
Currently, old Switch and Checkbox components are displayed as examples on [Forms page](https://paragon-openedx.netlify.app/components/form/)
[Form component](https://deploy-preview-1920--paragon-openedx.netlify.app/components/form/)
=> [BD-46] docs: update Form.Switch and Form.Checkbox to the latest versions

src/Card/Card.scss
- use dark variant for Card that has a section title.
[Card component](https://deploy-preview-1919--paragon-openedx.netlify.app/components/card/#card-variants)
=> [BD-46] fix: added white color for section title in Card component

src/Card/Card.scss, www/src/components/PageLayout.tsx, www/src/components/Settings.tsx, www/src/context/SettingsContext.tsx, www/src/templates/component-page-template.tsx
- expose the Container width option in the Settings sheet;
- allow previewing components at different container widths.
[Paragon site](https://deploy-preview-1726--paragon-openedx.netlify.app/components/card/)
=> [BD-46] docs: added container width options in the Settings sheet

src/Button/Button.scss, src/Button/README.md, src/Button/_variables.scss
- for openedx theme fix obvious issues (e.g. tertiary button disappearing in disabled state)
1) ![Screenshot 2023-01-12 at 23 32 53](https://user-images.githubusercontent.com/93188219/212186044-e2138ab4-820b-4fe7-8594-d654e749a9eb.png)
2) ![Screenshot 2023-01-12 at 23 33 27](https://user-images.githubusercontent.com/93188219/212186054-bcc9a47b-cf1e-48c8-b234-959ccdad2a85.png)
[Button component](https://deploy-preview-1910--paragon-openedx.netlify.app/components/button/)
=> [BD-46] feat: fixed buttons inconsistencies with design

.github/workflows/ci.yml, package.json, tsconfig.json, www/src/components/LayoutGenerator.tsx, www/src/components/SEO.tsx, www/src/components/insights/SummaryUsageExamples.tsx, www/src/pages/insights.tsx, www/tsconfig.json
Adds type check step to CI, simplifies typescript configs and fixes `target` to be `es6`.
=> [BD-46] chore: add type-check step to CI and update typescript configs

www/src/context/SettingsContext.tsx
By default, the container width value equals `undefined` in the `Container width` property in the `Settings` menu. Need to indicate default value (`md`).
[Paragon site documentation](https://deploy-preview-1983--paragon-openedx.netlify.app/components/alert/)
=> [BD-46] fix: fixed default container width in Settings menu

www/netlify/functions/trackGenerateComponent.js, www/src/components/IconsTable.jsx, www/src/components/Menu.tsx, www/src/context/SettingsContext.tsx, www/src/pages/foundations/elevation.jsx, www/src/pages/insights.tsx
Rename Segment events to follow a common convention: `openedx.paragon.{module}.{event descriptor}.{action} # action in past tense`
=> [BD-46] docs: renamed Paragon Segment events

CONTRIBUTING.md, README.md
Updates README.md and adds CONTRIBUTING.md.
https://github.com/openedx/paragon/issues/1971
N/A
=> docs: update README and add CONTRIBUTING

scss/core/css/utility-classes.css, scss/core/css/variables.css, tokens/build-tokens.js, tokens/style-dictionary.js
By default, style-dictionary appears to include a file header at the top of its automatically generated output files to indicate to contributors that those output files are not intended to be manually edited.
Example:
```
// Do not edit directly
// Generated on Fri, 27 Jan 2023 16:54:59 GMT
```
```
:root {
--pgn-color-primary-base: #FF0000FF;
}
```
Consider creating a custom file header with more details as well.
Without the file header, we run the risk of contributors wanting to manually edit the output files instead of editing the underlying design tokens instead.
The below config option may be related:
```
options: {
showFileHeader: false,
},
```
=> [BD-46] feat: added custom title for CSS output files

src/Card/Card.scss, src/Card/CardCarousel/tests/__snapshots__/CardCarousel.test.jsx.snap, src/Card/CardImageCap.jsx, src/Card/README.md, src/Card/tests/CardImageCap.test.jsx, src/Card/tests/__snapshots__/CardDeck.test.jsx.snap, src/Card/tests/__snapshots__/CardGrid.test.jsx.snap, src/Card/tests/__snapshots__/CardImageCap.test.jsx.snap
The fallbackLogoSrc is incorrectly calling the image URL when the logoSrc prop is not correctly fetching the image.
Issue: https://github.com/openedx/paragon/issues/1967
[Card Fallback example](https://deploy-preview-1994--paragon-openedx.netlify.app/components/card/#fallback-image)
=> [BD-46] fix: fixed undefined/null image logo src

.github/workflows/analyze-dependents.yml, .github/workflows/sync-alpha-master.yml
We are maintaining an `alpha` branch for the design tokens project. This PR proposes setting up automation to sync `alpha` whenever there are changes to `master` by automatically opening a PR that gets auto-merged to `master` once CI status checks pass.
Uses this Github Action: https://github.com/TreTuna/sync-branches
N/A
=> build: add GH workflow to sync alpha with master automatically

.github/workflows/commitlint.yml, .github/workflows/sync-alpha-master.yml
The previously generated PR failed CI due to failing commit lint. This PR excludes running the commit lint check on the `automation/sync-alpha-master` branch that is used to generate the PR.
=> build: skip CI for automation sync PR

.github/workflows/sync-alpha-master.yml
`alpha` branch is now in a good place where there are no conflicts with `master` and latest `master` is on `alpha`. This PR attempts to use https://github.com/TreTuna/sync-branches again to bring commits to `master` into `alpha` branch automatically.
N/A
=> build: another attempt to auto-sync changes from master to alpha

.github/workflows/sync-alpha-master.yml
Another attempt to automatically sync changes from `master` to `alpha`
N/A
=> build: switch base to trying a rebase

.github/workflows/sync-alpha-master.yml
Sets `base` branch to `alpha` to ensure the changes are added on top of `alpha` as it exists today.
n/a
=> build: set base branch to alpha

.github/workflows/sync-master-alpha.yml
Adds a Github Action workflow file for syncing `alpha` with `master` on any commit to `master` (using https://github.com/TreTuna/sync-branches)
N/A
=> build: use tretuna/sync-branches to sync alpha with master

.github/workflows/sync-master-alpha.yml
Removes an unnecessary `if` conditional preventing the auto-merge set up on generated PRs from `tretuna/sync-branches`.
=> build: remove unnecessary conditional on enabling auto merge

src/Form/FormAutosuggest.jsx, src/Form/tests/FormAutosuggest.test.jsx
This PR is to update the `Form.Autosuggest` component.
The `onSelected` function is being called during any `onChange` event. See below:
`onChange` => `setDisplayValue` => `setValue` => `onSelected` — we only want to call `onSelected` when a selection is made, not during every onChange.
Unless the user's input is an exact match for an option, `onSelected` will be passed a `null` value.  Meaning after each character is entered in the input, `onSelected(null)` is called. 
In addition, if "Teacher" is an option, entering the word "teacher" will then call `onSelected("Teacher")` — auto-selecting "Teacher". Technically, the user hasn't actually made the selection at this point. This can lead to unintended results — imagine if "Teacher Assistant" was another option the user wanted to select. …
=> fix: onChange behavior for `Form.Autosuggest`

src/Button/index.jsx, src/Icon/Icon.scss, src/Icon/README.md, src/Icon/_variables.scss, src/Icon/index.jsx
Adds a `size` parameter to the Icon class so that the user can choose from one of the predefined sizes: `xs`, `sm', 'md', `lg`. Updated the button component to use this parameter instead for `iconBefore` and `iconAfter`
- https://deploy-preview-2149--paragon-openedx.netlify.app/components/icon
- https://deploy-preview-2149--paragon-openedx.netlify.app/components/button/
=> feat: add icon size xs that looks good against a 1rem font

src/Button/Button.test.jsx, src/Button/ButtonGroup.test.jsx, src/Button/ButtonToolbar.test.jsx, src/Button/__snapshots__/Button.test.jsx.snap, src/Button/__snapshots__/ButtonGroup.test.jsx.snap, src/Button/__snapshots__/ButtonToolbar.test.jsx.snap, src/Icon/Icon.test.jsx
Fixes the decrease in test coverage introduced by https://github.com/openedx/paragon/pull/2149
=> test: fix coverage for Button class

src/Form/_FormText.scss
The Form.Group component allows you to include a form validation message under the Form.Control. However, the icon (either an "X" or a check) is not vertically aligned with each other (in both Open edX theme and edX.org theme).
Issue: https://github.com/openedx/paragon/issues/2197
[Form.Group component](https://deploy-preview-2202--paragon-openedx.netlify.app/components/form/form-group/)
=> [BD-46] fix: fixed misaligned form validation text with icon

src/DataTable/selection/BaseSelectionStatus.jsx, src/DataTable/selection/tests/SelectionStatus.test.jsx
- "Select all" button has "Select all 7" label even though there are only 2 rows displayed after applying filters
Issue: https://github.com/openedx/paragon/issues/1837
[Data Table](https://deploy-preview-2020--paragon-openedx.netlify.app/components/datatable/#frontend-filtering-and-sorting)
=> [BD-46] fix: fixed incorrect label in Select All button

www/src/components/CodeBlock.tsx, www/src/components/_CodeBlock.scss
Issue: https://github.com/openedx/paragon/issues/1981
[Paragon](https://deploy-preview-2194--paragon-openedx.netlify.app/components/actionrow/)
=> [BD-46] docs: new component examples and editable live code blocks

src/DataTable/DataTable.scss, src/DataTable/_variables.scss, www/src/components/insights/SummaryUsageExamples.tsx
https://deploy-preview-2006--paragon-openedx.netlify.app/
=> [BD-46] fix: fixed links width in Usage Insights Summary tables

www/src/components/IconsTable.jsx
Issue: https://github.com/openedx/paragon/issues/1936
[Icons page](https://deploy-preview-2011--paragon-openedx.netlify.app/foundations/icons)
=> [BD-46] fix: Segment event catches empty strings

src/Form/FormText.jsx
=> fix: wrap FormText children in div for flex styling

src/Button/README.md, src/Card/README.md, src/DataTable/tablefooter.mdx, src/Dropdown/README.md, src/Form/form-group.mdx, src/Icon/README.md, src/Menu/README.md, src/Menu/select-menu.md, src/Modal/alert-modal.mdx, src/Modal/fullscreen-modal.mdx, src/Modal/modal-dialog.mdx, src/Modal/modal-layer.mdx, src/Modal/modal-popup.mdx, src/Pagination/README.md, src/SelectableBox/README.md, src/Tabs/README.md, src/TransitionReplace/README.md, www/src/components/CodeBlock.tsx
Issue https://github.com/openedx/paragon/issues/1937
=> [BD-46] docs: add Segment event for when the 'Show code' block is opened/closed

src/Modal/PopperElement.jsx, src/Modal/PopperElement.test.jsx
Changes in #2226 broke `ModalPopup` positioning.
Reverting them to fix it.
=> [BD-46] fix: revert PopperElement changes

src/Card/Card.scss
Add stretching the message block to the full width
=> [BD-46] fix: stretch the message block to the full width

src/Stepper/README.md, src/Stepper/Stepper.jsx, src/Stepper/Stepper.scss, src/Stepper/StepperContext.jsx, src/Stepper/StepperHeader.jsx, src/Stepper/StepperHeaderStep.jsx, src/Stepper/StepperStep.jsx, src/Stepper/tests/Stepper.test.jsx
Make steps clickable after the user visits them, clicking should navigate the user to clicked step.
[Stepper component](https://deploy-preview-1712--paragon-openedx.netlify.app/components/stepper/)
=> [BD-46] feat: Clickable steps in Stepper component

package-lock.json, www/package.json, www/src/components/CodeBlock.tsx
- Rename `openedx.ui.example-code-block.{closed|opened}` Segment event to `openedx.paragon.docs.ui.example-code-block.{closed|opened}`
Issue: https://github.com/openedx/paragon/issues/2261
=> [BD-46] docs: renamed code example Segment event

www/src/components/CodeBlock.tsx
Issue: https://github.com/openedx/paragon/issues/2263
=> [BD-46] fix: fixed Copy code example button

src/Card/Card.scss, src/Card/CardCarousel/tests/__snapshots__/CardCarousel.test.jsx.snap, src/Card/CardDeck.jsx, src/Card/CardGrid.jsx, src/Card/README.md, src/Card/tests/CardDeck.test.jsx, src/Card/tests/CardGrid.test.jsx, src/Card/tests/__snapshots__/CardDeck.test.jsx.snap, src/Card/tests/__snapshots__/CardGrid.test.jsx.snap
Ran into a use case where it seems valid to use `CardGrid` _without_ equal height cards in each row. For example, in the case of using a grid of cards where only one or more cards may have a `Card.Status`, e.g.:
Lots of unnecessary whitespace in the card since it expands to take up the full height of the row.
```jsx
<CardGrid>
{/* cards */}
</CardGrid>
```
Each card only takes up the height it needs on its own.
```jsx
<CardGrid enableEqualColumnHeights={false}>
{/* cards */}
</CardGrid>
```
https://deploy-preview-2287--paragon-openedx.netlify.app/components/card/#cardgrid
https://deploy-preview-2287--paragon-openedx.netlify.app/components/card/#carddeck
=> feat: add `enableEqualColumnHeights` prop to `CardGrid` and `CardDeck`

package.json, src/Form/FormAutosuggest.jsx, src/Form/form-autosuggest.mdx, src/Modal/AlertModal.jsx
Fixes a bug with `Form.Autosuggest` component where clicking on `MenuItem`'s children would pass incorrect selected value to the `onSelected` function
https://deploy-preview-2304--paragon-openedx.netlify.app/components/form/form-autosuggest/
=> [BD-46] fix: use `currentTarget` in `FormAutosuggest` component to get selected option

src/Menu/SelectMenu.jsx, src/Menu/SelectMenu.test.jsx, src/Menu/__snapshots__/SelectMenu.test.jsx.snap, src/Menu/select-menu.md
Issue: https://github.com/openedx/paragon/issues/2275
[Select Menu](https://deploy-preview-2291--paragon-openedx.netlify.app/components/menu/select-menu/)
=> [BD-46] feat: added variants for the Select Menu component

src/Alert/index.jsx, src/Button/deprecated/index.jsx, src/Button/index.jsx, src/Card/CardCarousel/CardCarouselSubtitle.jsx, src/Card/index.jsx, src/Collapsible/index.jsx, src/DataTable/DataTableLayout.jsx, src/Form/FormControlSet.jsx, src/Form/FormRadioSet.jsx, src/Modal/ModalLayer.jsx, src/Nav/index.jsx, src/OverflowScroll/OverflowScroll.jsx, src/StatusAlert/index.jsx, src/Tabs/index.jsx, src/Toast/ToastContainer.jsx, src/ValidationFormGroup/index.jsx, www/src/components/header/Navbar.tsx
Issue: https://github.com/openedx/paragon/issues/2111
=> [BD-46] docs: added missing props on the documentation site

src/Stack/README.md, www/src/pages/foundations/responsive.jsx
This is a quick fix for two typos that were found while browsing the Paragon site. 
1. The [Responsive breakpoints](https://paragon-openedx.netlify.app/foundations/responsive) have the identifier for "Small" set to "xs" when it should be "sm". 
2. The link for the `Stack` component in Bootstrap's documentation has been updated
=> fix: link typo for bootstrap Stack

package-lock.json, www/package.json, www/playroom.config.js, www/playroom/constants.js, www/src/components/header/Header.scss, www/src/components/header/SiteTitle.tsx, www/src/pages/playground.tsx
Adds `Copy URL` and `Reset` buttons to the Playground page.
https://deploy-preview-2323--paragon-openedx.netlify.app/playground
=> [BD-46] docs: add copy URL and reset buttons to playground page

src/Form/FormCheckbox.jsx, src/Form/FormRadio.jsx, src/Form/FormRadioSetContext.jsx, src/Form/form-radio.mdx, src/Form/index.jsx, src/SelectableBox/tests/SelectableBox.test.jsx, src/SelectableBox/tests/__snapshots__/SelectableBox.test.jsx.snap, src/SelectableBox/tests/__snapshots__/SelectableBoxSet.test.jsx.snap, src/SelectableBox/tests/utils.test.js, src/SelectableBox/utils.js, src/index.js
Fixes `SelectableBox` props warning by using unlabeled variants of `Form.Checkbox` and `Form.Radio` components.
https://deploy-preview-1988--paragon-openedx.netlify.app/components/form/form-radio/#unlabeled-control
https://deploy-preview-1988--paragon-openedx.netlify.app/components/selectablebox/
=> [BD-46] feat: add ability to use unlabeled Radio and Checkbox components in respective Form sets

src/Stepper/StepperHeader.jsx, src/Stepper/tests/Stepper.test.jsx, src/utils/breakpoints.js, src/utils/constants.js
=> feat: add customizability to the stepper header's compact view, so preferred max width can determine when compact view occurs

src/Button/Button.test.jsx, src/Button/index.jsx
Quick fix that allows buttons formatted as hyperlinks to be clickable. 
=> fix: hyperlink button bug fix

scss/core/core.scss
Folks are seeing errors like this in MFEs:
```
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Can't find stylesheet to import.
╷
8 │ @import "~react-loading-skeleton/dist/skeleton";
│         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
╵
node_modules/@edx/paragon/scss/core/core.scss 8:9  @import
src/index.scss 3:9                                 root stylesheet
```
react-loading-skeleton defines an exports field in its package.json which looks like this:
```
"exports": {
".": {
"types": "./dist/index.d.ts",
"require": "./dist/index.cjs",
"import": "./dist/index.js"
},
"./dist/skeleton.css": "./dist/skeleton.css"
},
```
The webpack documentation states that if an exports field is defined in package.json, it replaces the default module loading behavior and any …
=> fix: use .css extension on react-loading-skeleton import

src/OverflowScroll/OverflowScroll.jsx, src/OverflowScroll/data/tests/useOverflowScrollActions.test.jsx, src/OverflowScroll/data/useOverflowScroll.js, src/OverflowScroll/data/useOverflowScrollActions.js, src/OverflowScroll/useOverflowScroll.mdx
Added fixed increment scroll behavior to useOverflowScroll
-  https://github.com/openedx/paragon/issues/1950
=> [BD-46] Add fixed increment scroll behavior to useOverflowScroll

docs/decisions/0009-usage-of-react-bootstrap.rst, src/Alert/README.md, src/Badge/README.md, src/Button/README.md, src/Button/button-group.mdx, src/Card/README.md, src/Carousel/README.md, src/Container/README.md, src/Dropdown/README.md, src/Figure/README.md, src/Form/input-group.mdx, src/Hyperlink/README.md, src/Image/README.md, src/Nav/README.md, src/Navbar/README.md, src/Overlay/README.md, src/ProgressBar/README.md, src/Spinner/README.md, src/Tabs/README.md, www/src/pages/foundations/layout.mdx
Issue: https://github.com/openedx/paragon/issues/2365
=> [BD-46] docs: fixed links leading to React Bootstrap

www/src/pages/foundations/responsive.jsx
Add question mark icon and tooltip with text for the `xs` min-width breakpoint
https://deploy-preview-2400--paragon-openedx.netlify.app/
=> [BD-46] docs: add info about xs min-width

icons/package.json
Currently, all of the Paragon icons are included into the bundle if at least one icon is used in the project. This PR adds tree-shaking support to include only used icons into the bundle.
Previously, using `SearchField` component (that uses couple of icons internally) would result in following Paragon bundle, which included all of the icons
this PR reduced the bundle to this
=> fix: make icons package tree-shakeable

src/Container/index.jsx
Description:
Add react ref support in container component
related to : [VAN-1537](https://2u-internal.atlassian.net/browse/VAN-1537)
=> feat: add ref support in container

src/Nav/_mixins.scss, src/Nav/_variables.scss, src/Nav/index.scss, src/Tabs/_variables.scss, src/Tabs/index.scss
Issues: 
- https://github.com/openedx/paragon/issues/2370
- https://github.com/openedx/paragon/issues/2368
[Tabs component](https://deploy-preview-2377--paragon-openedx.netlify.app/components/tabs/)
=> [BD-46] fix: fixed odd trapezoid-like underline on active tab in Tabs component

src/Form/FormControl.jsx, src/Form/tests/FormControl.test.jsx
Add initial autoResize to support e.g. `defaultValue` or `value`
=> [BD-46] fix: initial autoResize functionality

src/Popover/_mixins.scss, src/Popover/index.scss
Issue: https://github.com/openedx/paragon/issues/2422
[Popover component](https://deploy-preview-2477--paragon-openedx.netlify.app/components/popover/#state-variants)
=> [BD-46] feat: added arrow bg color for Popover component

src/Card/_variables.scss, src/Card/index.scss
Fixed border-radius of the Card img
Issue: https://github.com/openedx/paragon/issues/2498
[Card component](https://deploy-preview-2511--paragon-openedx.netlify.app/components/card/)
=> [BD-46] fix: fixed border-radius of the card img

src/Card/index.scss
=> fix: add border-bottom-right-radius to card image cap styles

src/SelectableBox/README.md, src/SelectableBox/SelectableBoxSet.jsx, src/SelectableBox/tests/SelectableBoxSet.test.jsx, src/SelectableBox/tests/__snapshots__/SelectableBoxSet.test.jsx.snap
This sets up the ability to forward props directly to the root element of the `SelectableBoxSet` component. This came up originally to enable to ability to provide an `aria-labelledby` attribute to the `SelectableBoxSet`. This will support adding other attributes should the need come up in the future.
[Preview of changes](https://deploy-preview-2461--paragon-openedx.netlify.app/components/selectablebox/)
=> fix: selectable box set props forwarding

package-lock.json, package.json
Allowing a peer dependency to react-intl@^6.4. The current version @^5.25.1 is incompatible with [Piral](https://piral.io/) which is being used as a the base framework for [OEP65 - currently still known as OEPXXXX](https://github.com/openedx/open-edx-proposals/blob/426f6e09ffe615e77aa9205281d77012385a08d4/oeps/architectural-decisions/oep-XXXX-modular-micro-frontend-domains.rst).
=> fix(deps): OEP65. updating to react-intl 6.4.4

src/Form/FormAutosuggest.jsx, src/Form/tests/FormAutosuggest.test.jsx
Fixes #2535 
https://deploy-preview-2547--paragon-openedx.netlify.app/components/form/form-autosuggest/
=> fix: filtered dropdown items by display value instead of event target

scss/core/core.scss
The issue was that in the prod environment Skeleton didn't show up. The fix is to use `@use` instead of `@import`.
https://github.com/openedx/paragon/issues/2420
https://deploy-preview-2531--paragon-openedx.netlify.app/components/skeleton/
=> [BD-46] fix: skeleton.css for both dev and prod

scss/core/core.scss
This reverts commit 7e96a0a6bba91f3a00a85d3fd40a7c3afb26b4d1.
Reverts #2531 as it still seems to be causing issues for consuming MFEs (e.g., frontend-template-application). That is, an MFE was unable to start/build with the changes in this prior commit even though testing the same MFE through module.config.js worked without issue.
n/a
=> Revert "fix: [BD-46] skeleton.css for both dev and prod (#2531)"

src/CheckBoxGroup/README.md, src/InputSelect/README.md, src/InputText/README.md, src/RadioButtonGroup/README.md, src/Table/README.md, src/TextArea/README.md
Updates documentation for deprecated components to give more accurate replacement options.
=> docs: update documentation for deprecated components

src/Form/FormAutosuggest.jsx, src/Form/FormAutosuggestOption.jsx, src/Form/_index.scss, src/Form/form-autosuggest.mdx, src/Form/tests/FormAutosuggest.test.jsx
Add attributes to `input` element to disable browser autocomplete on autosuggest component and change the div that houses the dropdown items to be a `ul`, change the button elements that render the list to be `li`. add new `role` to each element
Resolves [#2435](https://github.com/openedx/paragon/issues/2435) and resolves #2557.
We had to make more changes than anticipated here given that we previously relied on the `button` value attribute. After changing button elements to `li`, we realized that `li`'s value attribute is an integer value, which posed some problems.
Note that this doesn't fix the issue where if you try to tab out while in the dropdown, the menu is still displayed. (#2437)
https://deploy-preview-2513--paragon-openedx.netlify.app/components/form/form-autosuggest/
=> fix: disable browser autocomplete and edit dropdown items elements

src/DataTable/index.scss
Add overflow:hidden to spinner`s container to avoid height glitch during the animation
[Issue](https://github.com/openedx/paragon/issues/2551)
=> [BD-46] fix glitch on loading spinner

src/DataTable/README.md
Fix  display of number in DataTable
[Issue](https://github.com/openedx/paragon/issues/2548)
[View Switching](https://deploy-preview-2598--paragon-openedx.netlify.app/components/datatable/#view-switching)
=> [BD-46] Fix incorrect number of items in DataTable component

src/Form/FormAutosuggest.jsx
state.dropDownItems.length > 0 used to determine if an autosuggest component was active or not which was inaccurate. Found an alternative way to specify which component is being interacted with through setting a new bool isActive on the state.
Resolves : #2510 
https://deploy-preview-2517--paragon-openedx.netlify.app/components/form/form-autosuggest/
=> fix: add isActive to FormAutosuggest state

src/Form/FormAutosuggest.jsx, src/Form/FormAutosuggestOption.jsx, src/Form/tests/FormAutosuggest.test.jsx
Move autosuggest tests from Enzyme to RTL
N/A
=> chore: move autosuggest tests from Enzyme to RTL

src/Card/_variables.scss
- fixed Card border-radius and color.
**Issue:** https://github.com/openedx/paragon/issues/2549
=> [BD-46] fix: fixed Card border-radius and color

www/src/scss/_variables.scss
- fixed [Tooltip](https://paragon-openedx.netlify.app/components/tooltip/) zindex in [FullscreenModal](https://paragon-openedx.netlify.app/components/modal/fullscreen-modal/).
=> [BD-46] fix: fixed Tooltip zindex in FullscreenModal

src/DataTable/README.md
- Replaced the link to the bootstrap documentation for the DataTable component.
[Issue](https://github.com/openedx/paragon/issues/2552)
[DataTable component](https://deploy-preview-2606--paragon-openedx.netlify.app/components/datatable/#customizing-number-of-cards-shown-per-row)
=> [BD-46] fix: fixed link to bootstrap for the DataTable

src/Truncate/utils.js
- Fixed issue with truncating a whole string without spaces by adding 'word-break: break-word' style.
_This style is added to the newElement which is a copy of element on which all calculations are made._
[Issue](https://github.com/openedx/paragon/issues/2475)
[Truncate](https://deploy-preview-2584--paragon-openedx.netlify.app/components/truncate/)
=> [BD-46] fix: truncating a whole text

src/DataTable/index.scss, src/Form/_index.scss
Aligned DataTable checkboxes
[Issue](https://github.com/openedx/paragon/issues/2589)
[Deploy preview 2610](https://deploy-preview-2610--paragon-openedx.netlify.app/components/datatable/#frontend-filtering-and-sorting)
=> [BD-46] fix: align DataTable checkboxes

dependent-usage-analyzer/index.js, dependent-usage.json
Fixes Paragon's version value in dependent-usage.json to be `""` when it was not found in the cloned repo. Previously we defaulted to `{}` in such cases which breaks docs site build.
=> [BD-46] docs: fix Paragon's version generation in dependent-usage.json

src/Dropzone/README.md
=> chore: adding a read into memory example to the Dropzone component template

src/ProgressBar/index.jsx, src/ProgressBar/index.scss, src/ProgressBar/tests/ProgressBar.test.jsx, src/ProgressBar/tests/utils.test.js, src/ProgressBar/utils.js
- fixed `rtl` direction in ProgressBar component
**Issue:** https://github.com/openedx/paragon/issues/2594
[ProgressBar component](https://deploy-preview-2641--paragon-openedx.netlify.app/components/progressbar/#annotated-variant)
=> [BD-46] fix: fixed rtl direction in ProgressBar

src/Dropzone/README.md
Adding filename display to https://paragon-openedx.netlify.app/components/dropzone/#reading-file-contents-into-memory
[Deployed Preview](https://deploy-preview-2682--paragon-openedx.netlify.app/components/dropzone/#reading-file-contents-into-memory)
=> chore: adding file name to in-memory Dropzone upload example

www/gatsby-node.js, www/src/components/PageEditBtn/index.tsx, www/src/components/PageLayout.tsx, www/src/pages/404.tsx, www/src/pages/foundations/colors.tsx, www/src/pages/foundations/elevation.jsx, www/src/pages/foundations/responsive.jsx, www/src/pages/foundations/spacing.tsx, www/src/pages/foundations/typography.tsx, www/src/pages/insights.tsx, www/src/pages/playground.tsx, www/src/pages/status.tsx, www/src/templates/default-mdx-page-template.tsx, www/utils/createPages.js, www/utils/onCreatePage.js
- added Edit this page CTA to non-component pages;
- some refactoring.
Issue: https://github.com/openedx/paragon/issues/2625
[Paragon site documentations](https://deploy-preview-2667--paragon-openedx.netlify.app/foundations/layout)
=> [BD-46] feat: added Edit this page CTA to non-component pages

src/Stack/README.md, src/Stack/Stack.test.jsx, src/Stack/__snapshots__/Stack.test.jsx.snap, src/Stack/index.jsx, src/Stack/index.scss
Add reverse prop to the Stack component
[Issue](https://github.com/openedx/paragon/issues/2627)
[Deploy](https://deploy-preview-2678--paragon-openedx.netlify.app/components/stack/)
=> [BD-46] feat: add reverse prop to the stack component

src/Form/FormAutosuggest.jsx, src/Form/tests/FormAutosuggest.test.jsx
Resolves #2438. 
- Create IDs for items in dropdown
- Add `aria-activedescendant` attribute to `input` to identify to assistive technologies which item in the dropdown is being focused
- Add `aria-live=”assertive”` to wrapper component to allow screen readers to read out the number of options in the dropdown
https://deploy-preview-2570--paragon-openedx.netlify.app/components/form/form-autosuggest/
=> feat: add attributes to input and wrapper component

src/Form/FormAutosuggest.jsx, src/Form/tests/FormAutosuggest.test.jsx
Resolves: https://github.com/openedx/paragon/issues/2437
Before:
- When user tabbed the focus would jump to the drop down icon arrow
- Tabbing out doesn't hide the dropdown
After:
- When hitting tab, the focus jumps to the next control of the DOM 
- Dropdown is then closed
=> fix: run leave control logic when tabbing out

src/Form/FormAutosuggest.jsx, src/Form/tests/FormAutosuggest.test.jsx
=> Auto Suggest Fix: allows focus to return to input after hitting esc

src/Form/tests/FormAutosuggest.test.jsx
https://github.com/openedx/paragon/pull/2556 didn't have conflicts and all tests had passed when I merged it, but the test was using old test ids (snake_case instead of kebab-case).
This fixes the test by updating the ids used to kebab-case.
=> fix: use kebab-case-ids in autosuggest esc test

src/Form/FormCheckbox.jsx, src/Form/FormRadio.jsx, src/Form/tests/FormCheckboxSet.test.jsx, src/Form/tests/FormRadioSet.test.jsx, src/Menu/__snapshots__/Menu.test.jsx.snap
- fixed the problem of duplicate calls during `onChange` for the `Form.RadioSet` and `Form.CheckboxSet` components.
**Issue:** https://github.com/openedx/paragon/issues/2683
[Playground demo](https://deploy-preview-2705--paragon-openedx.netlify.app/playground?code=N4Igxg9gJgpiBcJgApkEoAEBeAfB4AOgHYYaREDOALhgNoBuAhgDYCuMANBhTFQGot2AXWwZWPAMpVGVGMgDkAcwBOMGEXloA3MVLlqdAJYUAwgAsYYANYwoXHlXOWbUEVjGTps5ADMWPbV0yCEoaM0YiKGYYcwjFGFEE3HwgvRCKCGiAOmYIRQUAMQhlAFsAJUYoQwgMcMjo2KJ4gEJW%2BS4YLOlleKospjYYQJJSbl4BQeRO7t7%2BwSGdEYBfRbTQ2oiomItrACMIAA9G%2BMTsPEIRtYzs3Pz5ItKnPcON%2Bu24mFbm9oxpxh7eHNBsNRmNHDsXFMuv9ZmAIbY0EEVkFVFRWMoSMhUhgADw4bGg0g4h4lLIAcWUEFYAAd8ZdRsTiqSADKMXYwZg4ADqZkMcIwJkyxQA-DiAPQkrKs9mcgm4yUVKoQCS8OWkIiMEowLAEcBC5QUXVqjAhY7a4B1LZmpbGgbsLDAO0wG300h0wkMhWVaoYJ06kCqKC6nBlWzir1K90e%2BVMrKK …
=> [BD-46] fix: fixed duplicate calls in FormRadioSet and FormCheckboxSet

bin/paragon-scripts.js, example/package.json, lib/install-theme.js, package-lock.json, www/package.json, www/src/scss/openedx-theme.scss
We've moved the dependency to the `openedx` scope so update the
dependency and re-build package-lock.json where applicable.
=> chore: Update openedx brand dependency.

src/SelectableBox/tests/SelectableBoxSet.test.jsx
Every PR post https://github.com/openedx/paragon/pull/2581 is showing
It seems a test was added that was setting an invalid type on `SelectableBoxSet` and eating the error to make the test pass. 
Before https://github.com/openedx/paragon/pull/2581, there were comments explaining this and `eslint-disable`s.
https://github.com/openedx/paragon/blob/1d6f95ecf845393fc4c7084e719f0b35c5bb4318/src/SelectableBox/tests/SelectableBoxSet.test.jsx#L74-L76
I decided, instead of bringing back the `eslint-disable`s, to
* Pass *no* type into the component instead of an invalid type
* I believe this properly tests if it "renders with radio type if neither checkbox nor radio is passed"
* Remove the console error eating
=> fix: properly test untyped selectable box sets

README.md
This is a part of https://github.com/openedx/axim-engineering/issues/23
=> fix: Update docs for a final publish before we move this package.

www/src/components/Menu.tsx
- added link to Contrast Checker tool;
- added segment event.
**Issue:** https://github.com/openedx/paragon/issues/2647
=> [BD-46] docs: added link to Contrast Checker tool

icons/es5/VideocamOutlined.js, icons/es5/index.js, icons/jsx/VideocamOutlined.jsx, icons/jsx/index.jsx, icons/svg/videocam_outlined.svg
Add VideoCamOutline icon.
https://deploy-preview-2750--paragon-openedx.netlify.app/
=> feat: add outlined videoCam icon

src/Breadcrumb/README.md
Change links for the Basic Usage example
[Issue](https://github.com/openedx/paragon/issues/2684)
=> [BD-46] docs: change breadcrumbs links for the basic usage example

src/Menu/README.md
Remove duplicated menu title
[Issue](https://github.com/openedx/paragon/issues/2689)
[https://deploy-preview-2756--paragon-openedx.netlify.app/](https://deploy-preview-2756--paragon-openedx.netlify.app/components/menu/)
=> [BD-46] docs: remove duplicated menu title

src/DataTable/FilterStatus.jsx, src/DataTable/tests/FilterStatus.test.jsx, src/DataTable/tests/SmartStatus.test.jsx
Update DataTable's filter status bar's messaging by replacing the accessor with the header name
[Issue](https://github.com/openedx/paragon/issues/2676)
[https://deploy-preview-2757--paragon-openedx.netlify.app/](https://deploy-preview-2757--paragon-openedx.netlify.app/components/datatable/#frontend-filtering-and-sorting)
=> [BD-46] fix: replace filter names with header names

package.json, src/ProductTour/Checkpoint.jsx, src/ProductTour/Checkpoint.test.jsx, src/ProductTour/ProductTour.test.jsx, src/i18n/messages/ar.json, src/i18n/messages/ca.json, src/i18n/messages/es_419.json, src/i18n/messages/es_AR.json, src/i18n/messages/es_ES.json, src/i18n/messages/fr.json, src/i18n/messages/he.json, src/i18n/messages/id.json, src/i18n/messages/it_IT.json, src/i18n/messages/ko_KR.json, src/i18n/messages/pl.json, src/i18n/messages/pt_BR.json, src/i18n/messages/pt_PT.json, src/i18n/messages/ru.json, src/i18n/messages/th.json, src/i18n/messages/tr_TR.json, src/i18n/messages/uk.json, src/i18n/messages/zh_CN.json
Add i18n support for ProductTour Checkpoint sr-only message
[Issue](https://github.com/openedx/paragon/issues/2706)
=> [BD-46] feat: add i18n support for ProductTour Checkpoint sr-only message

src/DataTable/ExpandRow.jsx, src/DataTable/selection/ControlledSelect.jsx, src/DataTable/selection/ControlledSelectHeader.jsx, src/DataTable/selection/ControlledSelectionStatus.jsx, src/DataTable/tests/ExpandRow.test.jsx
Removes redundant props spreading in DataTable subcomponents that cause a lot of console errors during development, more details in https://github.com/openedx/paragon/issues/2751
=> [BD-46] fix: remove props spreading in `DataTable` components

README.md, www/src/components/header/SiteTitle.tsx, www/src/pages/index.tsx
[Issue](https://github.com/openedx/paragon/issues/2775)
- Removed the "Technical documentation" label.
- README moved the "Getting Help" above the "Getting started".
=> [BD-46] docs: remove technical documentation label update readme

src/Card/_variables.scss, src/Nav/_variables.scss, src/Pagination/_variables.scss, src/SearchField/_variables.scss
- removed unused SCSS variables.
=> [BD-46] refactor: removed unused SCSS variables

.github/workflows/ci.yml
- replaced `set-output`
**Issue:** https://github.com/openedx/paragon/issues/2718
=> [BD-46] refactor: replaced set-output in CI/CD configuration

.github/workflows/release.yml
Simply removes the Github Pages deploy step from `release.yml` as mentioned in #2465
This is one of a couple `help-wanted` issues I'm going to grab as part of an application to come work with you folks! :smile: 
~~_Note: I'm waiting on my Contributor Agreement to be sent, but this seems pretty benign_~~
_CLA has been executed as of 1100 MST (GMT-7) Nov 16th_
(Wow actually _none_ of them apply)
=> ci(deploy): Remove pages deploy step

src/Dropzone/_variables.scss, src/Dropzone/index.scss
- fixed borders for the Dropzone component.
**Issue:** https://github.com/openedx/paragon/issues/2796
[Dropzone component](https://deploy-preview-2855--paragon-openedx.netlify.app/components/dropzone/)
=> [BD-46] fix: fixed borders for the Dropzone component

src/DataTable/RowStatus.jsx, src/DataTable/tests/DataTable.test.jsx, src/DataTable/tests/RowStatus.test.jsx, src/DataTable/tests/SmartStatus.test.jsx
Modifies the DataTable RowStatus to read, e.g. "Showing 1 - 10 of 500" instead of just "Showing 10 of 500".
Closes https://github.com/openedx/modular-learning/issues/111
Private-ref: [FAL-3534](https://tasks.opencraft.com/browse/FAL-3534)
https://deploy-preview-2838--paragon-openedx.netlify.app/components/datatable/#frontend-filtering-and-sorting
1. Visit the [deploy preview for the DataTable component](https://deploy-preview-2838--paragon-openedx.netlify.app/components/datatable/#frontend-filtering-and-sorting)
2. Navigate the table using the various pagination controls
3. Ensure that the modified "Showing ..." text is accurate and updates as the page changes.
=> Improves the DataTable RowStatus [FC-0036]

www/src/scss/base.scss
- added skeleton display on the documentation site.
[Skeleton component](https://deploy-preview-2865--paragon-openedx.netlify.app/components/skeleton/)
=> [BD-46] docs: added skeleton display on the documentation site

.github/workflows/ci.yml, src/ActionRow/README.md
- removed semantic release version preview.
**Issue:** https://github.com/openedx/paragon/issues/2778
=> [BD-46] refactor: removed semantic release version preview

package-lock.json, package.json, src/DataTable/tests/TableActions.test.jsx, src/Form/FormControl.jsx, src/Form/form-control.mdx, src/Form/tests/FormControl.test.jsx
- added FormControl input mask.
**Issue:** https://github.com/openedx/paragon/issues/2458
[Form.Control component](https://deploy-preview-2626--paragon-openedx.netlify.app/components/form/form-control/)
=> [BD-46] feat: added FormControl input mask

src/SearchField/index.scss
add hover styles for dark button
[Issue](https://github.com/openedx/paragon/issues/2650)
=> [BD-46] fix: hover for danger button

src/ProductTour/Checkpoint.jsx
Fixes a bug with `ProductTour`'s positioning.
https://github.com/openedx/paragon/assets/52399399/0fd3385b-fd14-4831-a99e-887e2ff21ab5
https://deploy-preview-2863--paragon-openedx.netlify.app/components/producttour/
=> [BD-46] fix: use fixed position for ProductTour Checkpoints's

src/DataTable/README.md
**Issue:** https://github.com/openedx/paragon/issues/2843
https://deploy-preview-2917--paragon-openedx.netlify.app/components/datatable/#with-a-default-active-state-specified
=> [BD-46] docs: fixed itemCount in the DataTable code example

src/Button/README.md
**Issue:** https://github.com/openedx/paragon/issues/2908
[Button component](https://deploy-preview-2926--paragon-openedx.netlify.app/components/button/#stateful-buttons)
=> [BD-46] docs: updated the Button documentation site section

www/src/components/LayoutGenerator.tsx, www/src/pages/foundations/colors.tsx, www/src/pages/foundations/elevation.jsx
**Issue:** https://github.com/openedx/paragon/issues/2849
[Colors page](https://deploy-preview-2924--paragon-openedx.netlify.app/foundations/colors/)
[Elevation page](https://deploy-preview-2924--paragon-openedx.netlify.app/foundations/elevation/)
=> [BD-46] docs: fixed large font in code examples

src/SelectableBox/README.md, src/SelectableBox/index.jsx, src/SelectableBox/tests/SelectableBox.test.jsx
**Issue:** https://github.com/openedx/paragon/issues/2903
[SelectableBox component](https://deploy-preview-2923--paragon-openedx.netlify.app/components/selectablebox/#without-active-outline)
=> [BD-46] feat: added ability to remove outline-border in SelectableBox component

bin/paragon-scripts.js, lib/version.js
**Issue:** https://github.com/openedx/paragon/issues/2870
=> [BD-46] feat: added Paragon CLI version command

src/Modal/_ModalDialog.scss
**Issue:** https://github.com/openedx/paragon/issues/2850
[MadalDialog component](https://deploy-preview-2925--paragon-openedx.netlify.app/components/modal/modal-dialog/)
=> [BD-46] fix: fixed ModalDialog.Header sizes

www/src/types/types.ts, www/src/utils/getDependentProjectsUsages.tsx
Fixes a bug with types for dependent-usage.json file, see rationale for the solution in [this comment](https://github.com/openedx/paragon/pull/2941#issuecomment-1862280442)
=> chore: enforce correct TypeScript types for dependent-usage.json object

src/Dropzone/index.jsx
Minor fix related to the `className` props of the `Dropzone` component.
When passed `className="some-class"`, the current implementation adds a property `{ className: 'some-class', ...}` to the object passed in the `classNames` function.
This results in the rendered object having the literal `className` as a CSS class, not the actual `some-class`.
Closes:
- #2954
N/A
=> fix: Dropzone className prop

src/ColorPicker/ColorPicker.test.jsx, src/ColorPicker/index.jsx
Fixes https://github.com/openedx/paragon/issues/2524
This updates the picker to have a separate `colorToDisplay` used by the textbox, and `hexColorString` used by the internal picker. This allows us to have invalid color values (which happens with any string that isn't 3 or 6 characters) without blocking user input.
This way users can still:
* paste anything in the textbox (only 6 characters are pasted)
* backspace without issue
https://deploy-preview-2734--paragon-openedx.netlify.app/components/colorpicker/
=> fix: prevent #NaN color picker values

src/Form/FormAutosuggest.jsx, src/Form/form-autosuggest.mdx, src/Form/tests/FormAutosuggest.test.jsx
Fixes https://github.com/openedx/paragon/issues/2436
=> fix: associate labels with autosuggest input

src/DataTable/README.md, src/DataTable/index.jsx, src/DataTable/tablefilters.mdx
- fixed links leading to the 7th version of the React-table package.
**Issue:** https://github.com/openedx/paragon/issues/2934
=> [BD-46] docs: fixed links leading to the 7th version of the React-table

scss/core/_variables.scss, src/Button/README.md, src/Button/_variables.scss, src/Button/index.scss
- updated the `border-radius` on the focus outline radius; 
- verified the `2px` offset for the focus outline; 
- refactoring was carried out in the file `README.md`.
**Issue:** https://github.com/openedx/paragon/issues/2550
[Button component](https://deploy-preview-2786--paragon-openedx.netlify.app/components/button/)
=> [BD-46] fix: fixed border-radius of buttons with sizes lg and sm

src/DataTable/index.jsx, src/DataTable/selection/BaseSelectionStatus.jsx, src/DataTable/tests/DataTable.test.jsx
**Issue:** https://github.com/openedx/paragon/issues/2872
[DataTable component](https://deploy-preview-2929--paragon-openedx.netlify.app/components/datatable/#backend-filtering-and-sorting)
=> [BD-46] fix: fixed the Select all button in the DataTable component

src/Tabs/index.jsx, src/hooks/tests/useIndexOfLastVisibleChild.test.jsx, src/hooks/useIndexOfLastVisibleChild.jsx, src/hooks/useIndexOfLastVisibleChild.mdx
Fixes `useIndexOfLastVisibleChild` hook to observer resizing of container element instead of whole window. This allows to correctly render `More...` tab on theme switch.
https://deploy-preview-2962--paragon-openedx.netlify.app/components/tabs/
=> [BD-46] fix `Tabs` not resizing on theme switch

src/ProductTour/Checkpoint.jsx, src/ProductTour/messages.js, src/i18n/messages/ar.json, src/i18n/messages/ca.json, src/i18n/messages/es_419.json, src/i18n/messages/es_AR.json, src/i18n/messages/es_ES.json, src/i18n/messages/fr.json, src/i18n/messages/he.json, src/i18n/messages/id.json, src/i18n/messages/it_IT.json, src/i18n/messages/ko_KR.json, src/i18n/messages/pl.json, src/i18n/messages/pt_BR.json, src/i18n/messages/pt_PT.json, src/i18n/messages/ru.json, src/i18n/messages/th.json, src/i18n/messages/tr_TR.json, src/i18n/messages/uk.json, src/i18n/messages/zh_CN.json, www/src/components/Menu.tsx
Fixes translations for `ProductTour` component and adds i18n support for additional missed hardcoded string.
https://deploy-preview-2886--paragon-openedx.netlify.app/components/producttour/
=> [BD-46] fix: correctly translate strings in `Checkpoint` component

src/Button/index.jsx, src/Dropzone/index.jsx, src/Icon/index.jsx, src/IconButton/index.jsx, src/Menu/MenuItem.jsx, src/Overlay/README.md, src/Overlay/index.jsx, www/src/components/Menu.tsx
**Issue:** https://github.com/openedx/paragon/issues/2737
=> [BD-46] refactor: corrected PropTypes

package-lock.json, package.json, src/IconButton/__snapshots__/IconButton.test.jsx.snap
Remove browserlist-config
[Issue2501](https://github.com/openedx/paragon/issues/2501)
=> [BD-46] build: remove browserlist-config

src/Hyperlink/index.scss
Fix hyperlink alignment
[Issue2398](https://github.com/openedx/paragon/issues/2398)
[deploy-preview-2971](https://deploy-preview-2971--paragon-openedx.netlify.app/components/hyperlink/)
=> [BD-46] fix: hyperlink alignment

src/DataTable/_variables.scss, src/Pagination/index.scss
Fixed difference with design
[Issue2904](https://github.com/openedx/paragon/issues/2904)
=> [BD-46] fix: tablefooter design differences

.husky/pre-commit, package-lock.json, package.json
- added Husky configuration
**Issue:** https://github.com/openedx/paragon/issues/2864
=> [BD-46] feat: added Husky  configurations

algolia-docsearch/README.md, algolia-docsearch/crawler-config.js, docs/decisions/0020-algolia-docsearch.rst
* Writes ADR about adopting Algolia DocSearch ([preview](https://github.com/openedx/paragon/blob/51f36b1c3e0154221bbb3517f991c80d8190d23c/docs/decisions/0020-algolia-docsearch.rst)).
* Creates `algolia-docsearch` module with a README about its intent.
* Persist the Algolia DocSearch crawler configuration into the `algolia-docsearch` for discoverability, code review, etc.
* Note: any changes made to the crawler configuration in the repo needs to updated in the crawler configuration [here](https://crawler.algolia.com/).
N/A
=> docs: include Algolia DocSearch ADR and crawler config

src/DataTable/filters/TextFilter.jsx
Resolves https://2u-internal.atlassian.net/browse/TNL-11258.
There was a bug where the `FormLabel` in `DataTable`'s `TextFilter` was including a `for` attribute pointing to an ID that does not exist in the DOM (throws an a11y error).
By instead passing `ariaLabel.current` to `<Form.Group>` as its `controlId` prop, we can ensure that all form component within the `Form.Group` rely on a consistent ID. However, previously, we were using the deprecated `Input` instead of `Form.Control`, so the appropriate `id` was not automatically applied to the input field in the DOM.
Resolution:
* Pass `controlId` to `Form.Group`
* Replace `FormLabel` with `Form.Label`.
* Replace `Input` with `Form.Control`.
In the following image, not that the `<label>`'s `for` attribute now refers to the input with the …
=> fix: rely on Form.Control and controlId in Form.Group

.github/workflows/analyze-dependents.yml
Relates to: https://github.com/openedx/paragon/issues/3000
Per discussion in Paragon Working Group, opting to temporarily disable the automation on the failing "Analyze dependents" GitHub Action, which updates metadata for "Usage Insights" until the above linked issue is resolved.
N/A
=> build: temporarily disable cron on failing usage insights github actions

src/Modal/ModalDialog.jsx, src/Modal/_ModalDialog.scss
Resolves https://github.com/openedx/paragon/issues/2938
=> feat: allow consumers to configure ModalDialog to allow overflow

src/Form/FormAutosuggest.jsx
We encountered an issue where the `childChildren` prop passed to the `MenuItem` component was flagged as an unrecognized prop to DOM (locally), leading to a console warning. Simultaneously, this warning caused the occurrence of duplicate API calls within our MFE (frontend-app-authn).
**Resolution:** We renamed the `childChildren` to `childchildren` and the warning stopped appearing and the duplicate API calls issue was resolved.
We are still unsure why we were having duplicate API calls due to this warning. Maybe React was trying to re-render due to invalid props? But we made sure that there was no issue with our implementation and it was due to the unrecognized prop. But we would like to understand the actual reason behind this if possible.
Console Warning screenshot.
In this video, we …
=> fix: unrecognized prop warning in form autosuggest

.github/workflows/analyze-dependents.yml, .husky/pre-commit, package-lock.json, package.json
Fixes #3000 which was caused by adding `prepare` life cycle script to the root package.json file which installs husky. It works fine if you run the script in the root directory but it fails if you run it from somewhere else (e.g. `dependent-usage-analyzer` directory from which `npm ci` is run during the workflow which I assume triggers `npm run prepare` of root package.json because we use workspaces). The reason is that husky is configured to be run from the root directory.
=> build: ignore npm scripts when installing dependencies in dependent analyzer workflow

src/Menu/index.scss
1. Go to the [`MenuItem` with form example](https://paragon-openedx.netlify.app/components/menu/#with-form)
2. Change the last two menu items' code to:
```tsx
<MenuItem as={Form.Checkbox} value="green">Green with super long item text that doesn't get truncated </MenuItem>
<MenuItem value="yellow">Yellow with super long text that does get truncated</MenuItem>
```
| ❌ Before this fix | ✅ After this fix |
|-|-|
| ![Screenshot 2024-03-25 at 1 57 32 PM](https://github.com/openedx/paragon/assets/945577/0f5b19f3-9eea-4508-98eb-80d9904753d7) | ![Screenshot 2024-03-25 at 1 57 52 PM](https://github.com/openedx/paragon/assets/945577/71d4248c-c880-4896-b0c9-f2322d623a0d) |
You can test the fix here: https://deploy-preview-3019--paragon-openedx.netlify.app/components/menu/#with-form
=> fix: display of menu items with checkboxes

.github/pull_request_template.md, src/Modal/AlertModal.jsx, src/Modal/MarketingModal.jsx, src/Modal/ModalDialog.jsx, src/Modal/ModalLayer.jsx, src/Modal/ModalPopup.jsx, src/Modal/tests/ModalLayer.test.jsx
The Paragon modal components (e.g., `AlertModal`) generally rely on the underlying `ModalDialog` component and it's optional props such as `isBlocking`. The intent for `isBlocking` should prevent the modal from being dismissed for use cases where there is a required action to be taken within the modal. However, `isBlocking` only prevents clicking of the modal backdrop from dismissing modal; users may still press the `Escape` key to dismiss the modal, despite the intent to have the modal be blocking.
This PR ensures the `Escape` behavior when `isBlocking` is passed to modal components such as `AlertModal` follows the same behavior as the modal backdrop; that is, when a modal `isBlocking`, neither clicking the modal backdrop _or_ pressing `Escape` key should dismiss the modal. …
=> fix: ensure esc key does not close modals that are blocking

.github/workflows/ci.yml
* This ensures we check that *only* icons generated from svgs are checked in.
* CI on this will fail until https://github.com/openedx/paragon/pull/3035 is merged and this is rebased
=> chore: make icon verification more robust

src/SearchField/SearchFieldAdvanced.jsx, src/SearchField/index.jsx
Bug: Merely using the default [`<SearchField />`](https://paragon-openedx.netlify.app/components/searchfield/) in an MFE without setting the optional `icons` property results in the following console warning:
```
console.error
Warning: Failed prop type: Invalid prop `icons.submit` of type `function` supplied to `SearchFieldAdvanced`, expected a single ReactElement.
at SearchFieldAdvanced (frontend-app-course-authoring/node_modules/@openedx/paragon/src/SearchField/SearchFieldAdvanced.jsx:18:5)
at SearchField (frontend-app-course-authoring/node_modules/@openedx/paragon/src/SearchField/index.jsx:28:5)
```
From [the `SearchField` docs](https://paragon-openedx.netlify.app/components/searchfield/), you can easily verify that the `icons` prop takes `elementType` values, not `element` values by …
=> fix: Wrong propTypes for SearchFieldAdvanced.icons

lib/build-tokens.js, package-lock.json, package.json, styles/css/core/custom-media-breakpoints.css, styles/css/core/variables.css, styles/css/themes/light/variables.css, tokens/src/core/components/Card.json, tokens/src/core/global/breakpoints.json, tokens/style-dictionary.js, tokens/utils.js
1. Integrates `style-dictionary` with `sd-transforms` ([GitHub](https://github.com/tokens-studio/sd-transforms)) from [Tokens Studio](https://tokens.studio/). Enables support for copying exported tokens from the Tokens Studio plugin in Figma and adding them to the Paragon tokens schema.
1. Registers a custom transform group `paragon-css` to abstract away our custom transforms, `sd-transforms`, and the default CSS transforms. The previously excluded `size/rem` filter for the default CSS transforms is added back in.
1. Resolves noisy warnings regarding missing output references in resulting token transforms, by now including the reference token(s) in the output. See screenshots below.
* In Paragon, this use case applies when transforming `light` theme variant tokens that reference `core` …
=> feat: registers sd-transforms; includes refs in source-tokens-only output; resolves refs warnings

src/Modal/ModalDialog.jsx, src/Modal/modal-dialog.mdx, src/Modal/tests/ModalDialog.test.jsx
Removed default value for `isOverflowVisible` in `ModalDialog` component and added usage example.
Issue: https://github.com/openedx/paragon/issues/3116
=> feat: Removed default value for isOverflowVisible in ModalDialog

tokens/src/core/components/Dropdown.json, tokens/src/core/components/Modal.json, tokens/src/core/components/Popover.json, tokens/src/core/components/ProductTour.json, tokens/src/core/components/Sheet.json, tokens/src/core/components/Tooltip.json, tokens/src/core/global/elevation.json, tokens/src/themes/light/components/Button/core.json, tokens/src/themes/light/components/Carousel.json, tokens/src/themes/light/components/Chip.json, tokens/src/themes/light/components/Form/other.json, tokens/src/themes/light/components/SearchField.json, tokens/src/themes/light/components/Tooltip.json, www/theme-config.js
This PR provides some minor improvements:
- `ratio` type changed to `number` in Design tokens
- theme title changed from `edx` to `edx.org`
=> refactor: corrected ratio tokens type and renamed edx theme

src/Card/BaseCard.tsx, src/Card/tests/BaseCard.test.jsx
Hopefully this does the trick for getting https://github.com/openedx/paragon/pull/3318 into `.tsx` land
=> chore: add typescript types for `BaseCard`
