openedx/paragon

.eslintrc.json
.storybook/__snapshots__/Storyshots.test.js.snap
package.json
src/Button/index.jsx
src/CheckBox/CheckBox.test.jsx
src/CheckBox/index.jsx
src/Dropdown/Dropdown.test.jsx
src/Dropdown/index.jsx
src/InputSelect/index.jsx
src/InputText/index.jsx
src/asInput/asInput.test.jsx
src/asInput/index.jsx
src/utils/utils.test.js
yarn.lock

Getting coverage to 100% would require writing noop tests for nonexistent `else` blocks, which imo is a waste of time.

(almost) 100% test coverage

---

README.md

small doc fix

---

.storybook/__snapshots__/Storyshots.test.js.snap
.storybook/config.js
package.json
src/Button/Button.scss
src/Button/index.jsx
src/CssJail/CssJail.scss
src/CssJail/index.jsx
src/Dropdown/Dropdown.scss
src/Dropdown/index.jsx
src/InputSelect/index.jsx
src/InputText/index.jsx
src/Tabs/Tabs.scss
src/Tabs/Tabs.stories.jsx
src/Tabs/Tabs.test.jsx
src/Tabs/index.jsx
src/asInput/asInput.scss
src/asInput/index.jsx
src/utils/paragon-reset.scss
yarn.lock

- kill reactstrap
- make CSS safe spaces explicit with the `CssJail` component
- local stylesheets for each component's CSS modules
- `Tabs` stories
- docs facelift

excise reactstrap

---

.storybook/addons.js
.storybook/config.js
package.json
src/CheckBox/CheckBox.stories.jsx
src/InputText/InputText.stories.jsx
yarn.lock

Adding storybook knobs addon
Currently have knobs setup on three stories:
-Both of the InputText stories
-The disabled checkbox story

Setting up storybook knobs

---

.storybook/__snapshots__/Storyshots.test.js.snap
src/CheckBox/CheckBox.stories.jsx
src/CheckBox/CheckBox.test.jsx
src/CheckBox/README.md
src/CheckBox/index.jsx
src/asInput/index.jsx
yarn.lock

Finishing the checkbox component

Finishing checkbox

---

package.json
src/CheckBox/CheckBox.test.jsx
src/Dropdown/index.jsx

chore(package): update eslint to version 4.5.0

---

package.json

chore(package): update @storybook/react to version 3.2.8

---

package.json

fix(package): update react-transition-group to version 2.0.2

---

.eslintignore
.storybook/addons.js
.storybook/config.js
package.json
src/CheckBox/CheckBox.stories.jsx
src/InputText/InputText.stories.jsx
yarn.lock

Knobs barfs a ton of errors, so I'm going to remove it. Options does also, but it doesn't look like that's going to be fixed anytime soon (https://github.com/storybooks/storybook/issues/1192) so we're going to use the workaround.

revert storybook knobs

---

.eslintignore
.storybook/__snapshots__/Storyshots.test.js.snap
src/Table/README.md
src/Table/Table.scss
src/Table/Table.stories.jsx
src/Table/Table.test.jsx
src/Table/index.jsx
yarn.lock

Adds a very basic table with tests and stories to demo functionality.
Looks like this:
For details on the table's API, check out [the readme](https://github.com/edx/paragon/blob/37a01bc388ca252233d4c24236260b65b7210b66/src/Table/README.md).

table component

---

.storybook/__snapshots__/Storyshots.test.js.snap
src/Dropdown/Dropdown.scss
src/Dropdown/Dropdown.test.jsx
src/Dropdown/index.jsx

No functional change here, just some changes to classnames and markup that were affected by the release of Bootstrap v4 beta.

patch dropdown for bootstrap v4

---

package.json

chore(package): update @storybook/react to version 3.2.11

---

package.json

@efischer19 please review when you get a moment. Thanks!
FYI @arizzitano

Update to edx-bootstrap 0.4.0

---

.storybook/webpack.config.js
package-lock.json
package.json

This might not even be worth it, but here's a quick PR to add notifications for Storybook builds (not that they take that long anyways) using [`webpack-build-notifier`](https://www.npmjs.com/package/webpack-build-notifier).

Implement Storybook Build Notifier

---

.travis.yml

* Automatically publish to GitHub pages

chore(travis): run script commands after success only

---

package-lock.json
package.json
src/Button/Button.test.jsx
src/CheckBox/CheckBox.test.jsx
src/Dropdown/Dropdown.test.jsx
src/Hyperlink/Hyperlink.stories.jsx
src/Modal/Modal.test.jsx
src/RadioButtonGroup/RadioButtonGroup.stories.jsx
src/RadioButtonGroup/index.jsx
src/StatusAlert/StatusAlert.test.jsx
src/Table/Table.test.jsx
src/Table/index.jsx
src/Tabs/Tabs.test.jsx
src/asInput/asInput.test.jsx
src/setupTest.js
src/tempPolyfills.js
src/tempPolyfills.test.js
webpack.config.js

Resolves #45 
cc: @fysheets 
[`edX-platform Sandbox`](https://jaebradley-react-16.sandbox.edx.org/)

patch(dependencies): update to React 16 and Enzyme 3

---

.travis.yml

[Travis HipChat Notifications Documentation](https://docs.travis-ci.com/user/notifications/#Configuring-HipChat-notifications)

chore(travis): add Paragon room notifications

---

package-lock.json

[`FEDX-412`](https://openedx.atlassian.net/browse/FEDX-412)
Was accidentally committed previously, but with our migration to Node 8 (and post-React 16 migration from #45 ) we should keep this file up-to-date.
To generate this file I ran ```rm -rf ./node_modules/ ; npm cache clean; npm i```.

chore(package-lock.json): Update our package-lock.json

---

.storybook/__snapshots__/Storyshots.test.js.snap
src/TextArea/README.md
src/TextArea/TextArea.stories.jsx
src/TextArea/index.jsx

New bootstrap form-control TextArea component - leverages Paragon asInput
Note* based on: https://github.com/edx/paragon/tree/master/src/InputText
Ticket: [EDUCATOR-1824](https://openedx.atlassian.net/browse/EDUCATOR-1824)

feat(TextArea): New TextArea Component

---

.storybook/__snapshots__/Storyshots.test.js.snap
src/InputSelect/index.jsx
src/InputText/InputText.stories.jsx
src/InputText/index.jsx
src/TextArea/index.jsx
src/asInput/asInput.test.jsx
src/asInput/index.jsx

Leverage the ID that is passed through as prop when it's available, allow for InputText to accept a type prop, and allow for input components to be assigned a ref

 fix(input): Use prop.id/prop.type when available and allow for ref on inputs

---

README.md

The additional README documentation hopefully answers questions around `semantic-release` specifically on the structure of commit messages, and why that structure is important from a release perspective.
If we decide that documentation updates need to be consistent between NPM and GitHub, I will change the commit `type` to be a `fix` instead of a `docs`.
I considering putting this in it's own markdown file - let me know if this separation is better. If we decide to put it in it's own markdown then we don't need to change the commit type.

docs(readme): add semantic-release documentation

---

.storybook/__snapshots__/Storyshots.test.js.snap
README.md
package.json
src/Icon/Icon.scss
src/Icon/Icon.stories.jsx
src/Icon/Icon.test.jsx
src/Icon/README.md
src/Icon/index.jsx
src/Modal/Modal.scss
src/Modal/Modal.stories.jsx
src/Modal/Modal.test.jsx
src/Modal/index.jsx
src/utils/constants.js

Add ability to apply a variant to Modal - based on the requirement for a Warning Modal in Studio-Frontend that needs an Icon as well.

feat(modal-icon): Add variant capability to Modal & create Icon

---

.storybook/__snapshots__/Storyshots.test.js.snap
README.md
src/CheckBox/index.jsx
src/CheckBoxGroup/CheckBoxGroup.scss
src/CheckBoxGroup/CheckBoxGroup.stories.jsx
src/CheckBoxGroup/CheckBoxGroup.test.jsx
src/CheckBoxGroup/README.md
src/CheckBoxGroup/index.jsx
src/asInput/index.jsx

feat(checkboxgroup): New CheckBoxGroup, update CheckBox & asInput styles

---

src/index.js

These are a few exports that SFE is using that was missing from the themeable target.

fix(input): add missing exports to index.js

---

.storybook/__snapshots__/Storyshots.test.js.snap
package-lock.json
src/CheckBox/CheckBox.stories.jsx
src/CheckBox/CheckBox.test.jsx
src/CheckBox/README.md
src/CheckBox/index.jsx

BREAKING CHANGE: add a componentWillReceiveProps function to CheckBox to allow for CheckBox to be updated by changes to prop, prop defaultChecked has been replaced by prop checked.

feat(checkbox): change CheckBox to be controllable via props

---

package-lock.json
package.json

Greenkeeper/uglifyjs webpack plugin 1.1.8

---

package-lock.json
package.json

build(dev-dependency): update webpack build notifier

---

src/RadioButtonGroup/README.md

docs(button-group): add documentation

---

src/index.js

So we can write `import { Icon } from '@edx/paragon';`.

fix(index): export Icon from index.jsx

---

.travis.yml

Final step of [`FEDX-450`](https://openedx.atlassian.net/browse/FEDX-450)
New `Notification Bot` in the `Paragon` channel
`#meta`

build(travis): update travis hipchat notification user

---

.storybook/__snapshots__/Storyshots.test.js.snap
src/Button/Button.stories.jsx

docs(button): update Button story

---

.storybook/__snapshots__/Storyshots.test.js.snap
src/MailtoLink/MailtoLink.stories.jsx

docs(mailtolink-story): add storybook addons

---

.storybook/__snapshots__/Storyshots.test.js.snap
src/Icon/Icon.stories.jsx

docs(icon-add-ons): add add-ons

---

.storybook/__snapshots__/Storyshots.test.js.snap
package-lock.json
package.json
src/InputSelect/InputSelect.stories.jsx
src/InputSelect/index.jsx

The InputText component currently cannot be disabled, this PR ensures that the disabled prop gets passed through our component down to the html select element.

Pass Disabled prop down in InputText

---

.storybook/__snapshots__/Storyshots.test.js.snap
src/CheckBox/CheckBox.stories.jsx

docs(checkbox): add addons

---

.storybook/__snapshots__/Storyshots.test.js.snap
src/Dropdown/Dropdown.stories.jsx

docs(dropdown): add updated add-ons

---

.storybook/__snapshots__/Storyshots.test.js.snap

I broke the build (https://travis-ci.org/edx/paragon/jobs/361195051)

build(storyshots): fix storyshots

---

.storybook/__snapshots__/Storyshots.test.js.snap
src/Modal/index.jsx

UX requested these updates:
* Updated 'x' to use FA icon and removed background color
* Updated close button styles
@edx/fedx-team @abbyluke

fix(modal): update close button styles

---

src/asInput/index.jsx

fix(as-input): replace includes with indexOf

---

.storybook/__snapshots__/Storyshots.test.js.snap
src/InputText/InputText.stories.jsx
src/asInput/README.md
src/asInput/asInput.scss
src/asInput/asInput.test.jsx
src/asInput/index.jsx

If either prop is provided, the input will be placed in an `input-group` div with the given addons alongside in `input-group-prepend` and/or `input-group-append` divs.
[Bootstrap docs on input groups](https://getbootstrap.com/docs/4.0/components/input-group/).

feat(asinput): add inputGroupAppend/Prepend props

---

.storybook/__snapshots__/Storyshots.test.js.snap
src/Modal/Modal.scss
src/Modal/Modal.stories.jsx
src/Modal/Modal.test.jsx
src/Modal/README.md
src/Modal/index.jsx

fix(modal): make header close button optional

---

src/Modal/Modal.test.jsx
src/Modal/index.jsx

replaces https://github.com/edx/paragon/pull/214

fix(modal): enable closing modal when click outside it

---

.npmignore

fix(npmignore): add files to npmignore

---

src/Modal/Modal.stories.jsx
src/Modal/Modal.test.jsx
src/Modal/README.md
src/Modal/index.jsx

This addresses #224 for one component: `Modal`. I decided to do this now because it started to cause some extra pain for me in SFE.

fix(modal): allow element in closeText prop

---

.storybook/__snapshots__/Storyshots.test.js.snap
.storybook/addons.js
package-lock.json
package.json
src/Table/Table.stories.jsx

docs(table): update add-ons for Table stories

---

.storybook/__snapshots__/Storyshots.test.js.snap
src/CheckBoxGroup/CheckBoxGroup.stories.jsx

@fysheets any idea what the best solution for the "Ensures related <input type="checkbox"> elements have a group and that that group designation is consistent" accessibility violation is?

docs(checkbox-group): add storybook addons

---

.storybook/__snapshots__/Storyshots.test.js.snap
src/TextArea/TextArea.stories.jsx

docs(text-area): update add-ons for TextArea stories

---

.storybook/__snapshots__/Storyshots.test.js.snap
src/InputSelect/InputSelect.stories.jsx

docs(input-select): add Storybook add-on to input-select

---

.storybook/__snapshots__/Storyshots.test.js.snap
src/InputText/InputText.stories.jsx

docs(input-text): update add-ons for input-text stories

---

.storybook/__snapshots__/Storyshots.test.js.snap
src/Tabs/Tabs.stories.jsx

docs(tabs): update tabs documentation

---

src/Modal/Modal.stories.jsx

docs(modal): update modal add-ons

---

.storybook/__snapshots__/Storyshots.test.js.snap
src/SearchField/SearchField.stories.jsx
src/SearchField/SearchField.test.jsx
src/SearchField/index.jsx

When using the `SearchField` component, I would like to know when the clear button is clicked. Right now, this isn't possible.

fix(searchfield): add onClear callback handler for clear button

---

src/SearchField/index.jsx

This adds the ability to add react elements in SearchFields' aria-label props, which is necessary for our Next Big Thing New Approach to internationalizing such messages.

refactor(search-field): add i18n ability

---

.storybook/__snapshots__/Storyshots.test.js.snap

I think somehow this snapshot didn't get updated

ci(snapshots): update snapshot

---

.storybook/Storyshots.test.js
.storybook/__snapshots__/Storyshots.test.js.snap
README.md
package-lock.json
package.json
src/Collapsible/Collapsible.scss
src/Collapsible/Collapsible.stories.jsx
src/Collapsible/Collapsible.test.jsx
src/Collapsible/README.md
src/Collapsible/index.jsx
src/index.js

feat(collapsible): add collapsible component

---

.storybook/__snapshots__/Storyshots.test.js.snap
src/Dropdown/Dropdown.scss
src/Dropdown/Dropdown.stories.jsx
src/Dropdown/Dropdown.test.jsx
src/Dropdown/README.md
src/Dropdown/index.jsx

[ENT-1104](https://openedx.atlassian.net/browse/ENT-1104)

add icon for dropdown

---

docs/decisions/0002-react-i18n.rst

This is a proposed formalization of a decision that was made on 10/4 (action item in minutes [here](https://openedx.atlassian.net/wiki/spaces/FEDX/pages/845612224/2018-10-04+Meeting+notes?focusedTaskId=3)).
I'm a little apprehensive about the process for adding ADRs with "approved" already in the file; could you weigh in on this tiny point of process, @nasthagiri?
Requesting review from @edx/fedx-team (can I do this from the "Reviewers" cog?)

`react-intl` ADR

---

.storybook/__snapshots__/Storyshots.test.js.snap
package-lock.json
src/Modal/Modal.stories.jsx
src/Modal/Modal.test.jsx
src/Modal/index.jsx

This resolves #360 by making sure the Modal sits on top of all other elements in the DOM.

fix(modal): change the positioning of the modal from relative to fixed

---

.storybook/__snapshots__/Storyshots.test.js.snap
src/InputSelect/InputSelect.stories.jsx
src/InputSelect/README.md
src/InputSelect/index.jsx

fix(inputselect): add aria-label

---

.storybook/__snapshots__/Storyshots.test.js.snap
src/Table/README.md
src/Table/Table.stories.jsx
src/Table/Table.test.jsx
src/Table/index.jsx

Allow users to specify a column to act as a row header

fix(table): add ability to specify row header

---

.storybook/Storyshots.test.js
.storybook/__snapshots__/Storyshots.test.js.snap
src/asInput/asInput.test.jsx
src/utils/newId.js
src/utils/utils.test.jsx

fix(utils): Revert changes to newId

---

.storybook/__snapshots__/Storyshots.test.js.snap
src/Collapsible/Collapsible.test.jsx
src/Collapsible/README.md
src/Collapsible/index.jsx

This change allows users to pass in a custom id to the icon on the
collapsible to avoid id duplication on the Icon component, which is an
issue that should be handled another time.

fix(collapsible): allow custom ids on button icon

---

.storybook/__snapshots__/Storyshots.test.js.snap
src/Hyperlink/Hyperlink.test.jsx
src/Hyperlink/README.md
src/Hyperlink/index.jsx

Add rel="noopener" for new window Hyperlinks

---

.storybook/Paragon.stories.jsx
.storybook/__snapshots__/Storyshots.test.js.snap
.storybook/config.js
.storybook/style.scss
src/Breadcrumb/Breadcrumb.stories.jsx
src/Button/Button.stories.jsx
src/CheckBox/CheckBox.stories.jsx
src/CheckBoxGroup/CheckBoxGroup.stories.jsx
src/Dropdown/Dropdown.stories.jsx
src/Fieldset/Fieldset.stories.jsx
src/Hyperlink/Hyperlink.stories.jsx
src/Icon/Icon.stories.jsx
src/InputSelect/InputSelect.stories.jsx
src/InputText/InputText.stories.jsx
src/MailtoLink/MailtoLink.stories.jsx
src/Pagination/Pagination.stories.jsx
src/RadioButtonGroup/RadioButtonGroup.stories.jsx
src/SearchField/SearchField.stories.jsx
src/Tabs/Tabs.stories.jsx
src/TextArea/TextArea.stories.jsx

- Readme and info is now inline. 
- The sidebar has groupings: Basics, Navigation, User Input, and Other.

Display readme inline and add structure to the sidebar

---

.eslintrc
.storybook/__snapshots__/Storyshots.test.js.snap
package-lock.json
package.json
src/ValidationFormGroup/README.md
src/ValidationFormGroup/ValidationFormGroup.stories.jsx
src/ValidationFormGroup/ValidationFormGroup.test.jsx
src/ValidationFormGroup/__snapshots__/ValidationFormGroup.test.jsx.snap
src/ValidationFormGroup/index.jsx
src/index.js

Handles bootstrap style field validation and handles related aria attributes.
Manages the rendering of bootstrap-style:
- Help text
- Valid and invalid feedback
For children of type input, textarea, and select:
- Appends bootstrap validation class names
- Appends aria-describedby attributes (for help text and feedback)

feat: add ValidationFormGroup component

---

src/index.js

fix: export input component

---

src/Collapsible/Collapsible.stories.jsx
src/Collapsible/index.jsx
src/Modal/index.jsx
webpack.config.js

Removes references to window and sets globalObject

fix: make ssr friendly

---

.storybook/__snapshots__/Storyshots.test.js.snap
package-lock.json
package.json
src/Collapsible/Collapsible.stories.jsx
src/Collapsible/Collapsible.test.jsx
src/Collapsible/index.jsx

We are using the `Collapsible` component in the learner portal but don't currently have a way to change the icon used in the button that toggles the collapsing behavior (other than manual styling). 
This PR adds support to pass in an `icons` prop as shown below:
```jsx
<Collapsible
// ...
icons={{
expanded: <FontAwesomeIcon icon={faChevronCircleUp} />,
collapsed: <FontAwesomeIcon icon={faChevronCircleDown} />,
}}
>
<p>Example content</p>
</Collapsible>
```
If the `icons` prop is not supplied, it will use the following icons as needed: `faAngleUp` & `faAngleDown`.

Support custom icons passed in via props

---

package.json

See https://github.com/semantic-release/semantic-release/issues/381#issuecomment-296246628 for reference.

configure next release tag for semantic release

---

.travis.yml
package.json
www/package.json

Forgot to run npm install on the subdirectory.

docs: fix build and deployment of doc site

---

.babelrc
.travis.yml
package-lock.json
package.json
src/index.js
webpack.config.js

revert(treeshaking): wanted a breaking change

---

src/SearchField/SearchField.scss

Added CSS to remove browser (Chrome and IE) default "X" to clear input search box. 
Added `margin-top` to search field input to match vertical alignment with "search:"
[ARCH-1048](https://openedx.atlassian.net/browse/ARCH-1048).

style: remove browser default clear input search

---

.storybook/__snapshots__/Storyshots.test.js.snap
src/SearchField/SearchField.scss
src/SearchField/SearchField.test.jsx
src/SearchField/index.jsx

1. small fix for SearchField component style and focus

fix(searchfield): small fix for searchfield focus and style

---

.travis.yml

Remove specific node versions. Use latest LTS version.

Update travis.yml to use latest LTS version of node

---

src/Collapsible/index.jsx

Allow custom components to consume the collapsible context

feat: export collapsible context

---

scss/edx/overrides/_grid.scss

Updating to 1140px to fit lowest common denominator of current desktop devices.

Update max container width (per design team)

---

www/src/pages/components/accordion.mdx
www/src/pages/components/alert.mdx
www/src/pages/components/badge.mdx
www/src/pages/components/button-group.mdx
www/src/pages/components/card.mdx
www/src/pages/components/carousel.mdx
www/src/pages/components/figure.mdx
www/src/pages/components/forms.mdx
www/src/pages/components/hyperlink.mdx
www/src/pages/components/image.mdx
www/src/pages/components/input-group.mdx
www/src/pages/components/mailtolink.mdx
www/src/pages/components/navbar.mdx
www/src/pages/components/navs.mdx
www/src/pages/components/overlays.mdx
www/src/pages/components/popover.mdx
www/src/pages/components/progress-bar.mdx
www/src/pages/components/spinner.mdx
www/src/pages/components/toast.mdx
www/src/pages/components/tooltip.mdx
www/src/pages/foundations/layout.mdx

docs: update layout docs

---

README.md
www/src/pages/components/_my-component.mdx
www/src/pages/status.jsx

Also adds a stub page in the documentation for contributors to use as a starting point.

Improve developer documentation in readme

---

docs/decisions/0010-removal-of-edx-assets.rst

This ADR proposes a restructuring of this project. [See the rst file for details.](https://github.com/edx/paragon/blob/835918d02d7f950e89561a7d85f707b6bc46046e/docs/decisions/0010-removal-of-edx-assets.rst)

docs: add adr for removal of edx assets

---

.gitignore
scss/edx/overrides/_modals.scss
src/Modal/index.jsx
www/src/pages/components/modal.mdx

Use of Modal with edx theme styling will need to be updated to left-align the footer buttons

style(modal): add alignButtonsRight and renderDefaultCloseButton options

---

scss/core/_variables.scss
scss/core/mixins/_buttons.scss
scss/core/overrides/_buttons.scss
www/src/pages/components/button.mdx

Companion PR https://github.com/edx/brand-edx.org/pull/20

feat: add inverse variants of buttons

---

www/package-lock.json
www/package.json
www/src/pages/foundations/colors.jsx
www/src/scss/index.scss

Add light, dark, accent a, and accent b to the color ramps.
Fix color measuring so that it accurately labels the colors.

docs: fix color docs

---

scss/core/_variables.scss

fix: setting container-xl max-width to 1600px

---

src/DataTable/TableHeaderRow.jsx

fix: get rid of prop-types error

---

src/DataTable/DataTable.scss

Css fix to trigger upgrade from the last PR.

feat: data table upgrade

---

www/src/components/PropType.jsx
www/src/components/PropsTable.jsx

Fixes a p tag within a p tag error and adds a key to a list of elements

fix: remove errors related to PropType table

---

src/Sheet/Sheet.scss
www/src/pages/components/sheet.mdx

Minor fixes for sheet component re: paragon working group review.

Sheet fixes

---

src/DataTable/SelectionStatus.jsx
src/DataTable/tests/SelectionStatus.test.jsx

Also allows users to pass clear selection text as a prop, to aid i11n

fix: change clear selection to sentence case

---

src/DataTable/ActionDisplay.jsx
src/DataTable/Actions.jsx
src/DataTable/BulkActions.jsx
src/DataTable/CollapsibleButtonGroup.jsx
src/DataTable/DataTable.scss
src/DataTable/TableActions.jsx
src/DataTable/TableControlBar.jsx
src/DataTable/index.jsx
src/DataTable/tests/ActionDisplay.test.jsx
src/DataTable/tests/BulkActions.test.jsx
src/DataTable/tests/TableActions.test.jsx
www/src/components/PropType.jsx
www/src/pages/table/datatable.mdx

Table actions are displayed when no rows are selected
Bulk actions are now only displayed when rows are selected
Updated documentation

feat: Add TableActions component

---

dependent-usage-analyzer/index.js
dependent-usage.json
www/src/components/layout.jsx
www/src/components/navigation.jsx
www/src/pages/insights.jsx

Not perfect, but a first pass:

docs: basic usage insights page

---

src/Badge/_variables.scss

@abutterworth 
Ticket on Jira: https://openedx.atlassian.net/browse/PAR-287
Update badge component according to the new design: https://www.figma.com/file/eGmDp94FlqEr4iSqy1Uc1K/Paragon-2021?node-id=6703%3A52

[BD-35] PAR-285 feat: change styles according to new badge component design

---

src/Breadcrumb/Breadcrumb.scss
src/Breadcrumb/_variables.scss
src/Breadcrumb/index.jsx

@abutterworth 
Ticket on Jira: https://openedx.atlassian.net/browse/PAR-285
Update breadcrumb component according to new design

[BD-35] PAR-285 feat: change breadcrumb component according to new design

---

src/Dropdown/Dropdown.scss
src/Dropdown/_variables.scss

@abutterworth 
Ticket on Jira: https://openedx.atlassian.net/browse/PAR-280
Update dropdown component according to new design

[BD-35] PAR-280 feat: change styles according to new dropdown component design

---

src/Collapsible/Collapsible.scss
src/Collapsible/_variables.scss
src/Collapsible/index.jsx
www/src/pages/components/collapsible.mdx

@abutterworth 
Ticket in jira: https://openedx.atlassian.net/browse/PAR-286
Update collapsible component according to new design.

[BD-35] PAR-286 feat: change collapsible component according to new design

---

src/DataTable/TableCell.jsx
src/DataTable/TableHeaderCell.jsx
src/DataTable/tests/TableCell.test.jsx
src/DataTable/tests/TableHeaderCell.test.jsx

allow users to customize cell styles easily

fix: add headerClassName and cellClassName

---

package-lock.json
package.json

Doesn't seem to be used anywhere.

fix: remove unused sass-loader dependency

---

src/Alert/Alert.scss
src/Alert/README.md
src/Alert/_variables.scss

@abutterworth 
Ticket in Jira: https://openedx.atlassian.net/browse/PAR-291
Change alert component according to new design

[BD-35] PAR-291 feat: change alert component according to new design

---

scss/core/_variables.scss

Update all display font sizes and line heights to match design docs

feat: update display font sizes and line heights

---

src/Popover/Popover.scss
src/Popover/Popover.test.jsx
src/Popover/README.md
src/Popover/_variables.scss
src/Popover/index.jsx

@abutterworth 
Ticket in Jira: https://openedx.atlassian.net/browse/PAR-284
Update popover component according to new design, add success, warning and danger variants

[BD-35] PAR-284 feat: change popover component according to new design

---

src/ProgressBar/ProgressBar.scss
src/ProgressBar/README.md
src/ProgressBar/_variables.scss

@abutterworth 
update variables and override progress-bar

[BD-35] fix: update variables and override progress-bar

---

src/Tooltip/README.md
src/Tooltip/Tooltip.scss
src/Tooltip/Tooltip.test.jsx
src/Tooltip/_variables.scss
src/Tooltip/index.jsx

@abutterworth 
Ticket on Jira: https://openedx.atlassian.net/browse/PAR-282
Add light version tootltip

[BD-35] PAR-282 feat: change tooltip component according to new design

---

src/SearchField/SearchField.test.jsx
src/SearchField/index.jsx

For test ids and hotjar pii suppression

fix: update SearchField to pass props to Input

---

src/Collapsible/README.md
src/Collapsible/index.jsx

https://openedx.atlassian.net/browse/PAR-446
The basic `Collapsible` accepts onToggle onOpen and onClose callbacks. Add them to the props api table and add an example.

docs: document callbacks on collapsible

---

scss/core/_variables.scss

https://openedx.atlassian.net/browse/PAR-442
From 30px gutters to 24px

fix: update grid gutters to match design

---

src/AvatarButton/AvatarButton.scss
src/AvatarButton/README.md
src/AvatarButton/__snapshots__/AvatarButton.test.jsx.snap
src/AvatarButton/index.jsx
src/Button/Button.scss
src/Button/__snapshots__/Button.test.jsx.snap
src/Button/index.jsx
src/Dropdown/Dropdown.scss
src/StatefulButton/StatefulButton.scss
src/StatefulButton/__snapshots__/StatefulButtontest.test.jsx.snap
www/src/components/Header.jsx

Rework Button styles so that it works with Avatar Button and any direct insertions of Icons as children of the Button eg (`<Button><Icon /> Label</Button>`)

fix: improve button icon css so it works with avatar button

---

src/Alert/Alert.scss
src/Alert/Alert.test.jsx
src/Alert/README.md
src/Alert/__snapshots__/Alert.test.jsx.snap
src/Alert/index.jsx

feat: Alert text aligned with heading

---

dependent-usage-analyzer/checkout-dependents.sh
dependent-usage.json
www/src/pages/insights.jsx

Running this script is not automated yet. This is a manual update.

docs: update usage analysis

---

src/Form/_Form.scss

The select box was not showing a visual change when disabled, this fixes it.

fix: show disabled state

---

src/Form/_Form.scss

* remove text wrapping from floating label
* add padding to the icon so it does not overlap text

fix: select dropdown styles

---

src/Alert/Alert.scss
src/Alert/_variables.scss

- Update alert font size, line height and color according to figma design.
**Figma Design:**
https://www.figma.com/file/eGmDp94FlqEr4iSqy1Uc1K/Paragon-Design-System?node-id=1934%3A871
Fixes: VAN-558

fix: update alert style

---

www/gatsby-config.js
www/package-lock.json
www/package.json
www/src/components/IconsTable.jsx
www/src/images/link.svg
www/src/scss/index.scss

Supports auto-linking documentation headings to be able to deep link to specific section of a component's documentation when sharing with others.

docs: autolink headings through MDX plugin

---

src/Alert/Alert.scss
src/Alert/_variables.scss

- update alert heading color and icon size.
**Related Ticket**
https://openedx.atlassian.net/browse/VAN-558

fix: alert style title

---

src/Responsive/README.md
src/Responsive/Responsive.test.jsx
src/Responsive/index.jsx

Changes:
- Added `ExtraExtraLarge` screen size https://getbootstrap.com/docs/5.0/layout/breakpoints/
- Updated tests
- Updated documentation
This change is required for https://openedx.atlassian.net/browse/VAN-560

feat: add extra extra large responsive component

---

src/index.js

A small PR to add the `ExtraExtraLarge` screen to paragon export file

fix: update export for responsive component

---

docs/decisions/0012-css-styling-conventions

Write down conventions or rules that have come up informally in PR reviews over the past several months.

docs: create 0012-css-styling-conventions

---

src/DataTable/FilterStatus.jsx
src/DataTable/tests/FilterStatus.test.jsx

Adding a boolean to FilterStatus in order to give the option of hiding the "Filtered by ___" text. Specifically created as a request for frontend-admin-portal [here](https://openedx.atlassian.net/browse/ENT-4677). 
[Associated paragon ticket.](https://openedx.atlassian.net/browse/PAR-555)

feat: making "Filtered by __" text optional

---

icons/es5/Unread.js
icons/es5/index.js
icons/jsx/Unread.jsx
icons/jsx/index.jsx
icons/package-lock.json
icons/svg/unread.svg

Ticket Id: https://openedx.atlassian.net/browse/TNL-8579

feat: unread icon added in paragon

---

src/IconButton/README.md
src/IconButton/_IconButton.scss
src/IconButton/index.jsx
src/PageBanner/PageBanner.scss
src/PageBanner/PageBanner.test.jsx
src/PageBanner/README.md
src/PageBanner/index.jsx
src/index.js
src/index.scss

[Figma design spec](https://www.figma.com/file/eGmDp94FlqEr4iSqy1Uc1K/Paragon-Design-System?node-id=14061%3A20)

feat: create page banner and add icon button black variant

---

src/Form/_Form.scss
src/Form/_variables.scss

Added a dark-700 color on form fields hover
https://openedx.atlassian.net/browse/VAN-580

fix: added color on form field hover

---

.github/CODEOWNERS

Adding `@edx/paragon-working-group` as the CODEOWNER for this repository. This Github team will automatically get PR review requests. PRs will be require at least one approval from a member of this Github team. Please allow 24-72 hours for an initial review from a member of this team (note that your squad can still review, however the final approval should come from a member of the Paragon Working Group. If a review from this team is not submitted within this timeframe, you may escalate by pinging members of the team directly. We plan to get additional members into this Github team over time to ensure efficient reviews. Internal staff should still post their PRs in the #paragon-working-group Slack channel for broader visibility and to get a review more quickly.
The members of the …

build: add CODEOWNERS file

---

icons/es5/ContactMail.js
icons/es5/index.js
icons/jsx/ContactMail.jsx
icons/jsx/index.jsx
icons/svg/contact_mail.svg

- [[PAR-576] implement icon "contact mail"](https://openedx.atlassian.net/browse/PAR-576)
- https://github.com/openedx/frontend-wg/issues/29

feat: add ContactMail icon

---

src/ActionRow/README.md
src/ActionRow/index.jsx
src/Alert/README.md
src/Alert/index.jsx
src/Avatar/README.md
src/AvatarButton/README.md
src/Modal/AlertModal.jsx
src/Modal/alert-modal.mdx

Improve documentation for Alert, AlertModal, ActionRow, Avatar, AvatarButton components
JIRA: [PAR-578](https://openedx.atlassian.net/browse/PAR-578)

[BD-46] docs: improve documentation for components

---

README.md
src/ActionRow/README.md
src/Alert/README.md
src/Avatar/Avatar.scss
src/Avatar/README.md
src/Avatar/_variables.scss
src/AvatarButton/AvatarButton.scss
src/AvatarButton/README.md
src/AvatarButton/_variables.scss
src/Card/README.md
src/Container/README.md
src/Container/_variables.scss
www/gatsby-node.js
www/src/templates/component-page-template.jsx

- auto-pull theme variables to components pages when creating the pages
- update local development documentation and fix couple of broken links
JIRA: [PAR-364](https://openedx.atlassian.net/browse/PAR-364)

[BD-46] docs: add auto-pulling theme variables to components pages

---

src/Breadcrumb/Breadcrumb.scss
src/Breadcrumb/Breadcrumb.test.jsx
src/Breadcrumb/README.md
src/Breadcrumb/_variables.scss
src/Breadcrumb/index.jsx

- Update mobile variant for Breadcrumb
- Implement dark variant of Breadcrumb
- Update Breadcrumb link color
Preview: https://deploy-preview-926--paragon-edx.netlify.app/
JIRA: 
https://openedx.atlassian.net/browse/PAR-439
https://openedx.atlassian.net/browse/PAR-581
https://openedx.atlassian.net/browse/PAR-582

[BD-46] feat: breadcrumb dark variant and mobile orientation

---

src/Annotation/Annotation.scss
src/Annotation/Annotation.test.jsx
src/Annotation/README.md
src/Annotation/__snapshots__/Annotation.test.jsx.snap
src/Annotation/_variables.scss
src/Annotation/index.jsx
src/index.js
src/index.scss

Implement Annotation component
Preview: https://deploy-preview-921--paragon-edx.netlify.app/components/annotation/
Figma: https://www.figma.com/file/eGmDp94FlqEr4iSqy1Uc1K/?node-id=14061%3A33
JIRA: [PAR-579](https://openedx.atlassian.net/browse/PAR-579)

[BD-46] feat: add Annotation component

---

src/Chip/Chip.scss
src/Chip/Chip.test.jsx
src/Chip/README.md
src/Chip/__snapshots__/Chip.test.jsx.snap
src/Chip/_variables.scss
src/Chip/index.jsx
src/index.js
src/index.scss

added Chip component with tests, description and styles
JIRA: [PAR-437](https://openedx.atlassian.net/jira/software/projects/PAR/boards/654?selectedIssue=PAR-437)

[BD-46] feat: implement Chip component

---

src/DataTable/DataTable.scss
src/DataTable/README.md
src/DataTable/Table.jsx
src/DataTable/index.jsx
src/DataTable/tests/DataTable.test.jsx

Add a loading state for the table that shows a loader spinner
Preview: https://deploy-preview-991--paragon-edx.netlify.app/
JIRA: https://openedx.atlassian.net/browse/PAR-322

[BD-46] feat: add a loading state to the datatable

---

src/DataTable/CollapsibleButtonGroup.jsx
src/DataTable/ExpandRow.jsx
src/DataTable/README.md
src/DataTable/index.jsx

- update DataTable view switching docs to include note about data memoization
- fix console errors regarding prop types
JIRA: [PAR-615](]https://openedx.atlassian.net/browse/PAR-615)

[BD-46] docs: update DataTable view switching docs

---

src/CheckBox/CheckBox.test.jsx
src/CheckBox/index.jsx
src/Fieldset/index.jsx
src/ListBox/index.jsx
src/ListBoxOption/index.jsx
src/Pagination/Pagination.test.jsx
src/Pagination/index.jsx
src/StatusAlert/README.md
src/StatusAlert/StatusAlert.test.jsx
src/StatusAlert/index.jsx
src/asInput/index.jsx

- Refactor Paragon components which are using deprecated lifecycle methods
JIRA: https://openedx.atlassian.net/browse/PAR-345

refactor: [BD-46] components which are using deprecated lifecycle methods

---

src/DataTable/DataTable.scss
src/DataTable/TableControlBar.jsx

- Fix styles of DataTable's TableControlBar component

fix: [BD-46] styles of data table's table control bar component

---

docs/decisions/0015-i18n-support.rst

Add ADR for i18n support.
JIRA: [PAR_412](https://openedx.atlassian.net/browse/PAR-412)

[BD-46] docs: add ADR for i18n support 

---

src/ProductTour/Checkpoint.jsx
src/ProductTour/Checkpoint.scss
src/ProductTour/Checkpoint.test.jsx
src/ProductTour/CheckpointActionRow.jsx
src/ProductTour/CheckpointBody.jsx
src/ProductTour/CheckpointBreadcrumbs.jsx
src/ProductTour/CheckpointTitle.jsx
src/ProductTour/ProductTour.test.jsx
src/ProductTour/README.md
src/ProductTour/_variables.scss
src/ProductTour/index.jsx
src/index.js
src/index.scss

This is a new branch name for https://github.com/openedx/paragon/pull/1045 - moved so that the CLA checker knows it's me, not Carla. She was an employee when she wrote the base of this PR, so the copyright for this PR is fine, but the bot doesn't know that.

feat: new product tour component

---

src/Nav/Nav.scss
src/ProductTour/Checkpoint.scss
src/StatefulButton/README.md
src/StatefulButton/StatefulButton.scss
src/Stepper/Stepper.scss
src/Toast/_Toast.scss
src/Toast/_ToastContainer.scss

- Implement RTL support for all component
- from StandardModal to useWindowSize and ProductTour
- JIRA: https://openedx.atlassian.net/browse/PAR-646

feat: [BD-46] implement rtl for components from StandardModal to useWindowSize and ProductTour

---

src/Breadcrumb/Breadcrumb.scss
src/Button/Button.scss
src/Button/button-group.mdx
src/Card/Card.scss
src/Chip/Chip.scss

- Implement RTL support for all component
- from Breadcrumbs to Chip
- JIRA: https://openedx.atlassian.net/browse/PAR-646

feat: [BD-46] implement rtl for components from Breadcrumbs to Chip

---

src/Stack/README.md
src/Stack/Stack.scss
src/Stack/Stack.test.jsx
src/Stack/__snapshots__/Stack.test.jsx.snap
src/Stack/_variables.scss
src/Stack/index.jsx
src/index.js
src/index.scss

New component `Stack`:
- vertical and horizontal directions
- gap based on `the spacer classes`
- styles are took from the React-Bootstrap `Stack`
JIRA: [PAR-406](https://openedx.atlassian.net/browse/PAR-406)

[BD-46] feat: implement Stack component

---

src/Card/Card.scss
src/Collapsible/Collapsible.scss
src/DataTable/DataTable.scss
src/IconButtonToggle/IconButtonToggle.scss
src/TransitionReplace/TransitionReplace.scss

- Implement RTL support for all component
- from Collapsible to Dropdown
- JIRA: https://openedx.atlassian.net/browse/PAR-646

feat: [BD-46] implement rtl for components from Collapsible to Dropdown

---

src/Figure/Figure.scss
src/Form/README.md
src/Form/_Form.scss
src/Form/_FormControlSet.scss
src/Form/_FormText.scss
src/Form/form-checkbox.mdx
src/Form/form-switch.mdx
src/Hyperlink/Hyperlink.scss
src/Modal/_ModalDialog.scss
src/index.scss

- Implement RTL support for all component
- from Figure to Input Group
- JIRA: https://openedx.atlassian.net/browse/PAR-646

feat: [BD-46] implement rtl for components from Figure to Input Group

---

src/Card/README.md

- Update Card docs with content block empty variants
- JIRA: https://openedx.atlassian.net/browse/PAR-467

feat: [BD-46] update card docs with content block empty

---

scss/core/_variables.scss
src/Alert/Alert.scss

- added new box-shadows structure
- replaced box-shadow parameters in Alert component 
- [PAR-726](https://openedx.atlassian.net/browse/PAR-726)

feat: [BD-46] box shadows toolkit

---

scss/core/_utilities.scss
src/Modal/Modal.scss
src/Modal/ModalDialog.jsx
src/Modal/ModalLayer.jsx

- implemented the solution to support nested modals by default
- JIRA: https://openedx.atlassian.net/browse/PAR-669

feat: [BD-46] added prop to manage modals zIndex

---

www/src/components/Header.jsx

New features:
- removed unused `sticky-top` CSS classes;
- added `sticky-top` header-wrapper.
JIRA: [PAR-758](https://openedx.atlassian.net/browse/PAR-758)

[BD-46] feat: added sticky header

---

src/IconButton/IconButton.test.jsx
src/IconButton/__snapshots__/IconButton.test.jsx.snap
src/IconButton/index.jsx

Default prop cause the issue
`{}` -> `undefined`

[BD-46] feat: icon button prop fix

---

src/Bubble/Bubble.scss
src/Bubble/Bubble.test.jsx
src/Bubble/README.md
src/Bubble/__snapshots__/Bubble.test.jsx.snap
src/Bubble/_variables.scss
src/Bubble/index.jsx
src/Stepper/Stepper.scss
src/Stepper/StepperHeaderStep.jsx
src/index.js
src/index.scss

New Bubble component:
- implement props: `variant`, `disabled`, `className`
- tests
- examples
https://deploy-preview-1205--paragon-openedx.netlify.app/

[BD-46] feat: Bubble component

---

scss/core/_extend.module.scss
scss/core/_variables.scss
src/utils/breakpoints.js
www/src/components/Menu.jsx
www/src/pages/foundations/responsive.jsx

Add `Responsive` page:
- description from the task
- table with breakpoints
JIRA: [PAR-767](https://openedx.atlassian.net/browse/PAR-767)

[BD-46] feat: add responsive page with table

---

.eslintrc
.releaserc
CHANGELOG.md
generate-changelog.js
package-lock.json
package.json
www/gatsby-config.js
www/gatsby-node.js
www/src/components/Header.jsx

Add a `CHANGELOG.md` to the repository along with the script used to generate it. Also add [semantic release changelog package](https://github.com/semantic-release/changelog) to ensure that new releases are automatically added to the changelog.
JIRA: [PAR-785](https://openedx.atlassian.net/browse/PAR-785)
https://deploy-preview-1234--paragon-openedx.netlify.app/changelog

[BD-46] docs: add changelog to the documentation site

---

package.json

Update repository url to point to openedx org in github.

[BD-46] update repository url in package.json

---

.releaserc

build: add semantic-release/github

---

src/Menu/Menu.scss

Fix select popup
[JIRA](https://openedx.atlassian.net/browse/PAR-811)

[BD-46] fix select popup

---

src/Modal/modal-popup.mdx

Update example for `ModalPopup` component to fix positioning of the component.
https://deploy-preview-1344--paragon-openedx.netlify.app/components/modal/modal-popup/

[BD-46] docs: update `ModalPopup` example

---

src/Nav/Nav.scss
www/package-lock.json
www/package.json
www/src/components/Header.jsx
www/src/components/Seach.jsx
www/src/components/Search.scss
www/src/scss/base.scss
www/src/templates/component-page-template.jsx

Add Algolia search to docs site
Preview: https://deploy-preview-1246--paragon-openedx.netlify.app/
JIRA: https://openedx.atlassian.net/browse/PAR-795
Figma: https://www.figma.com/file/UWIyoulVBQ7AfGXCtG4y3q/DocSearch?node-id=0%3A1

[BD-46] feat: algolia search

---

src/ActionRow/README.md

Fixed action row checkbox on the mobile version of the site.
- [Action row](https://deploy-preview-1337--paragon-openedx.netlify.app/components/actionrow/)

[BD-46] docs: fixed action row checkbox

---

scss/core/_utilities.scss
scss/core/_variables.scss
www/package-lock.json
www/package.json
www/src/components/Menu.jsx
www/src/components/_doc-elements.scss
www/src/pages/foundations/elevation.jsx

Added "Elevation" page to "Foundations" section.
[Figma](https://www.figma.com/file/eGmDp94FlqEr4iSqy1Uc1K/Paragon-Design-System?node-id=9076%3A3783)
[Elevation page](https://deploy-preview-1341--paragon-openedx.netlify.app/foundations/elevation)

docs: [BD-46] added "Elevation" page to "Foundations" section

---

.github/workflows/ci.yml
.github/workflows/release.yml

Updating codecov action from v2 to v3 to keep it consistent with all frontend repos

Updating codecov github action

---

Makefile

build: replace language with languages in tx args

---

.tx/config

build: update .tx/config project name

---

.tx/config
Makefile
package.json

[BD-46] build: update i18n script to compile messages pulled from transifex

---

www/package-lock.json
www/package.json

The weird title text on some of the non-component pages which should be removed
https://github.com/openedx/paragon/issues/1387

[BD-46] docs: The weird title text was removed

---

src/index.js

fix: export default export from react-loading-skeleton as Skeleton

---

src/Collapsible/Collapsible.scss
src/index.scss

- remove Card styles import from `Collapsible.scss` file,
- add `Card.scss` import to the `index.scss` file,
- make sure other components' styles also get imported to the `index.scss` file.
[Card component](https://deploy-preview-1522--paragon-openedx.netlify.app/components/card)
[Collapsible component](https://deploy-preview-1522--paragon-openedx.netlify.app/components/collapsible/)

[BD-46] fix: fixed Card import

---

.stylelintrc.json
package-lock.json
package.json
scss/core/_functions.scss
scss/core/_variables.scss
src/Annotation/Annotation.scss
src/IconButton/IconButton.scss

Migrate to shared stylelint config.

[BD-46] feat: stylelint-config-edx connection

---

docs/decisions/0018-typescript-support.md

[BD-46] feat: TypeScript ADR

---

www/src/components/MeasuredItem.tsx

Fix values not being updated on `foundations/` pages during theme switch.

[BD-46] docs: fix theme changer on foundations pages

---

README.md
www/src/components/Menu.jsx
www/src/pages/foundations/design-tokens.mdx

Add documentation for Design Tokens in `README.md` and in the Design Tokens page in the Foundation section

[BD-46] feat: add initial documentation

---

example/babel.config.js
example/package-lock.json
example/package.json
example/src/MyComponent.jsx
example/src/index.scss
example/webpack.dev.config.js

According to Typescript release in Paragon, `example` app started crashing. This PR includes fixes. Also there updates to dependencies in the `example` app.

[BD-46] docs: update and fix example app

---

src/Layout/README.md
www/src/pages/foundations/layout.mdx

Update layout component documentation to link Layout component and Layout foundations with each other.

[BD-46] docs: layout update docs

---

.releaserc

build: remove semantic-release/git plugin

---

catalog-info.yml

In support of: https://open-edx-proposals.readthedocs.io/en/latest/processes/oep-0055-proc-project-maintainers.html
Following: https://docs.openedx.org/en/latest/developers/how-tos/add-a-catalog-file.html
N/A

chore: add catalog-info.yml file

---

catalog-info.yml

Updates to https://backstage.openedx.org/catalog/default/component/paragon

chore: update catalog-info.yml file for Backstage

---

catalog-info.yml

More [Backstage](https://backstage.openedx.org/catalog/default/component/paragon) config updates for Paragon.
N/A

[skip ci] chore: add more links to backstage config

---

src/Truncate/README.md
src/Truncate/Truncate.test.js
src/Truncate/index.jsx
src/Truncate/utils.js

- Implement recursive solution for nested inner tags
- add doc strings for functions
- improve code
- update tests
- update exaple
https://deploy-preview-1702--paragon-openedx.netlify.app/components/truncate/

[BD-46] feat: update truncate v3

---

.github/workflows/manual-publish.yml

feat: add manual publish workflow

---

.github/workflows/release.yml

[BD-46] build: install npm dependencies in www project during release action

---

src/Card/README.md

docs: update default hasOverflowCards on  example

---

README.md

Update README per the specification defined [here](https://open-edx-proposals.readthedocs.io/en/latest/processes/oep-0055/decisions/0003-readme-specification.html) as part of the [Maintainers](https://open-edx-proposals.readthedocs.io/en/latest/processes/oep-0055-proc-project-maintainers.html) Pilot Phase 1.
N/A

docs: Update README per Maintainers Pilot Phase 1

---

package-lock.json
www/package-lock.json
www/src/components/exampleComponents/HipsterIpsum.tsx

- fix critical vulnerabilities in the Paragon project
Paragon
www

[BD-46] feat: fixed vulnerabilities error in paragon/package.json

---

example/package-lock.json

- resolve critical security issues in an example project that come up after doing the `npm install`

[BD-46] fix: vulnerabilities error in an Example folder

---

.github/workflows/sync-alpha-master.yml

Attempts to open an auto-merged PR to keep `alpha` branch in sync with `master` whenever commits are merged to `master`.

build: update sync workflow for alpha

---

.github/workflows/sync-alpha-master.yml

Another attempt to sync `alpha` with `master` on commits to `master`.

build: include fetch-depth: 0 to checkout

---

.github/workflows/sync-alpha-master.yml

Another attempt to sync commits to `master` with `alpha` to ensure the `alpha` branch stays up-to-date.

build: setup git user in sync branches workflow

---

.github/workflows/sync-alpha-master.yml

Possibly final attempt (?) to sync `alpha` with changes on `master` as they are committed.

build: add a branch for generated workflow PR

---

.github/workflows/sync-alpha-master.yml

Try rebasing `alpha` with `master` instead of merging.

build: rebase instead of merge for syncing changes

---

.github/workflows/sync-alpha-master.yml

Used an incorrectly supported version tag in the `tretuna/sync-branches@v1` Github Action usage.
N/A

build: 1 to v1 in sync-branches workflow

---

.github/workflows/sync-alpha-master.yml

Run `git pull origin alpha` after switching to `alpha` branch to ensure it has latest changes before we attempt to rebase with `master`
N/A

build: pull from alpha before rebase master

---

.github/workflows/sync-alpha-master.yml

Try using `git checkout alpha` instead of `git switch alpha`

build: git checkout instead of git switch

---

.github/workflows/sync-alpha-master.yml

try using `devmasx/merge-branch` https://github.com/devmasx/merge-branch
N/A

build: try using devmasx/merge-branch

---

.github/workflows/sync-alpha-master.yml

Update merge-branch version number...
N/A

build: update merge-branch version number

---

.github/workflows/sync-alpha-master.yml

Now try `action-sync-branch` 🐻 

build: try action-sync-branch

---

.github/workflows/sync-master-alpha.yml

Add `workflow_dispatch` to sync-master-alpha.yml GH Action workflow to allow it to be manually dispatched.
N/A

build: allow manually dispatch sync alpha

---

dependent-usage.json
package-lock.json
package.json
src/ColorPicker/ColorPicker.scss
src/ColorPicker/ColorPicker.test.jsx
src/ColorPicker/README.md
src/ColorPicker/__snapshots__/ColorPicker.test.jsx.snap
src/ColorPicker/_variables.scss
src/ColorPicker/index.jsx
src/index.js
src/index.scss

Addition of a new component (ColorPicker) which is a button that allows users to preview and select a color. 
[Local testing link
](http://localhost:8000/components/colorpicker/)

feat: create new ColorPicker component

---

src/Form/_Form.scss
src/Form/_variables.scss

feat: add success and danger checked svgs

---

dependent-usage-analyzer/index.js
www/src/components/insights/ComponentUsageExamples.tsx
www/src/components/insights/ProjectUsageExamples.tsx
www/src/components/insights/SummaryUsageExamples.tsx
www/src/components/insights/UsagesList.tsx
www/src/pages/insights.tsx

[BD-46] docs: fixed paragon version view in dependent usage analyzer

---

package-lock.json
package.json
www/package.json

- added `query-string` package in the project

[BD-46] fix: added query-string package in the project

---

netlify.toml

[BD-46] build: upgrade netlify node version to 18

---

www/src/components/LeaveFeedback.scss
www/src/components/LeaveFeedback.tsx
www/src/components/PageLayout.tsx
www/src/scss/base.scss

Issue: https://github.com/openedx/paragon/issues/2243

[BD-46] docs: added Leave Feedback link

---

src/MailtoLink/index.jsx

Issue: https://github.com/openedx/paragon/issues/2278

[BD-46] fix: fixed the Mailtolink variant in the Button component

---

src/Figure/README.md
www/src/components/LeaveFeedback.scss
www/src/components/LeaveFeedback.tsx

Issue: https://github.com/openedx/paragon/issues/2343

[BD-46] docs: fixed issue feedback error

---

.github/workflows/analyze-dependents.yml

Usage Insights hasn't been updated in a month due to changes to the analyze-dependents.yml file in [this PR](https://github.com/openedx/paragon/pull/2227).
These changes should make the workflow file have a valid format and run successfully again.
n/a

build: fix analyze-dependents workflow

---

docs/decisions/0019-scaling-styles-with-design-tokens.rst

Meant to update this to "accepted" on merge of the design tokens ADR.
n/a

docs: update design tokens ADR status to accepted

---

src/Card/index.scss

Issue: https://github.com/openedx/paragon/issues/2473
[Card component](https://deploy-preview-2496--paragon-openedx.netlify.app/components/card/)

[BD-46] fix: fixed rounded corners for Card.ImageCap component

---

www/gatsby-config.js

[BD-46] fix: fixed Gatsby local build

---

src/Card/index.scss

fix: resolve stylelint

---

www/playroom/scope.js

Exposes `lodash.debounce` in the [Paragon Playground](https://paragon-openedx.netlify.app/playground?code=N4Igxg9gJgpiBcIA8AhArgFwxAdgPgAkYAbYiAAgHcIAnYqJAenS1zxAF8g) code editor. Will be useful for rapid prototyping with async operations in textarea input form controls.
`lodash.debounce` documentation: https://lodash.com/docs/4.17.15#debounce
Example rapid prototype with debounce: [Demo](https://deploy-preview-2596--paragon-openedx.netlify.app/playground?code=N4Igxg9gJgpiBcJgApkEoAEBeAfB4AOgHYYaREDOALhgMIDyAqgEoDKAogPoAKzAkrXbYMARgAsATgkBuYqXLUMAQQBqSvgBklAIQ1dtSrQDlBwgEwAGKxdkkyESjQBmEAE4BbAIZVurgJZgMMLIAA7%2BgZi4%2BHKk9o4YjKwAIhAANqmersJEMADuGHxEVKkAdEYAru4ARjCuAGJuXlTIBCAwRAC0ia0ANNF2sRjUAJ6pMPAYrWDlrq7tYMO9MYPTs-PDE62JSUsDGAC%2BaLaDc1QzJNtpGa4lLh7eoeEwRzH7x3GKANp%2BFAAqwyE-EQAOZ9CgwKh …

docs: expose lodash.debounce function in playroom

---

src/Form/FormAutosuggest.jsx
src/Form/FormAutosuggestOption.jsx
src/Form/tests/FormAutosuggest.test.jsx

- switch data-testid to kebab case for consistency
- moved import to setuptest.js

chore: switch data-testid to kebab case for consistency

---

icons/es5/CheckCircleLightOutline.js
icons/es5/index.js
icons/jsx/CheckCircleLightOutline.jsx
icons/jsx/index.jsx

[INF-1054](https://2u-internal.atlassian.net/browse/INF-1054)
added new icon in es5 and jsx folder of icon

feat: added new icon in es5 and jsx

---

src/Layout/README.md

- corrected valid color contrasts for the Layout component (according to [WCAG](https://webaim.org/resources/contrastchecker/)).
**Issue:** https://github.com/openedx/paragon/issues/2637
[Layout component](https://deploy-preview-2668--paragon-openedx.netlify.app/components/layout/)

[BD-46] docs: changing Layout colors

---

.github/workflows/analyze-dependents.yml

[BD-46] chore: increase sleep time between merge attempts in analyze dependents action

---

src/Tabs/README.md

**Issue:** https://github.com/openedx/paragon/issues/2878
[Tabs component](https://deploy-preview-2918--paragon-openedx.netlify.app/components/tabs/#conditional-rendering)

[BD-46] docs: added an example of conditional rendering for the Tabs component

---

.github/workflows/ci.yml
.github/workflows/manual-publish.yml
.github/workflows/release.yml

build: update codecov action to v4 and use token

---

www/playroom.config.js

Resolves https://github.com/openedx/paragon/issues/2794

docs: allow-modals in playground
